<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><!--
<META http-equiv=Page-Exit content=progid:DXImageTransform.Microsoft.Fade(duration=.5)>!-->
<title>Phần mềm DH & QLVB</title>
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl?>style/style.css">
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl?>style/menu.css">

<link rel="icon" href="../../favicon.ico" type="image/x-icon" />

<?= $this->JSPublicConst;?>
<!--Menu-->
<script src="<?= $this->baseUrl?>js/util.js" type="text/javascript"></script>
<script type="text/javascript" src="<?= $this->baseUrl?>js/tiny_mce/tiny_mce.js"></script>
<!--Calendar-->
<!--<script src="<?= $this->baseUrl?>zapatec/utils/zapatec.js" type="text/javascript"></script>
<script src="<?= $this->baseUrl?>zapatec/zpcal/src/calendar.js" type="text/javascript"></script>
<script src="<?= $this->baseUrl?>zapatec/zpcal/lang/calendar-en.js" type="text/javascript"></script>
<link href="<?= $this->baseUrl?>zapatec/zpcal/themes/wood.css" rel="stylesheet" />-->
<!--Load javascript va Css cho Tung module-->


<script src="<?= $this->baseUrl?>js/jdialog.js" type="text/javascript"></script>
<script src="<?= $this->baseUrl?>js/jmenuTop.js" type="text/javascript"></script>

<?php
	echo $this->LoadAllFileJsCss;
?>
<SCRIPT type=text/javascript>
var t_id = setInterval(animate,1);
var pos=0;
var dir=2;
var len=0;
function animate(){
	var elem = document.getElementById('progress');
	if(elem != null) {
	if (pos==0) len += dir;
	if (len>32 || pos>79) pos += dir;
	if (pos>79) len -= dir;
	if (pos>79 && len==0) pos=0;
	elem.style.left = pos;
	elem.style.width = len;
}
}
function remove_loading() {
this.clearInterval(t_id);
var targelem = document.getElementById('loader_container');
targelem.style.display='none';
targelem.style.visibility='hidden';

}
</SCRIPT>

<STYLE type=text/css>
	#interface1 {Z-INDEX: 1;}
	#loader_container {WIDTH: 100%; POSITION: absolute; TOP: 40%; left:0%; TEXT-ALIGN: center}
	#loader {
			height:auto;
			PADDING-RIGHT: 0px; 
			DISPLAY: block; PADDING-LEFT: 0px; 
			FONT-SIZE: 11px; Z-INDEX: 2; 
			PADDING-BOTTOM: 16px; MARGIN: 0px auto;
			WIDTH: 130px; COLOR: #000000; 
			PADDING-TOP: 10px; 
			FONT-FAMILY: Tahoma, Helvetica, sans; 
			BACKGROUND-COLOR: #ffffff; 
			TEXT-ALIGN: center;}
	
</STYLE>
<DIV id=loader_container>
<DIV id=loader>
<DIV align=center id=contentload class="Loading">Loading...</DIV>
<div class="img_load_process"></div>
</DIV>
</DIV>
<DIV id=interface1 style="DISPLAY: inline; VISIBILITY: visible">
<DIV style="LEFT: 1px; VISIBILITY: hidden; POSITION: absolute; TOP: 1px"></DIV>
<DIV style="DISPLAY: none; LEFT: 0px; POSITION: absolute; TOP: 0px">
</DIV>
<!--ket thuc-->
</head>
<body  topmargin="0" leftmargin="0" marginheight="0" marginwidth="0" rightmargin="0" width="100%">
<table class='body_interface' cellpadding="0" cellspacing="0" topmargin="0" leftmargin="0" marginheight="0" marginwidth="0" rightmargin="0" >
	<tr>		
		<td class='margin_center'>	
	<?php 
		if ($this->showModelDialog != 1) {?>
		<div class="Banners">
			<table cellpadding="0"  cellspacing="0" class="box_search">	
			<tr>
				<td  class="box_search_text">
				<input class="textbox" style="width: 300px;" type="textbox" name="FullTextSearchLeft" value="Tìm kiếm văn bản" id="FullTextSearchLeft" onclick="addEnter();">
				</td>
				
	            <td>
	          	 &nbsp;  <input class="add_large_button" style="margin-top: -5px;" type="button" name="SearchFullTextSearch" id="SearchFullTextSearch" value="Tìm kiếm" onclick="checkvalue1();">
	            </td>
			</tr>
		</table>				
		</div>	
	 <?php }?>
	<div id="all">
    <table width="100%" border="0" cellpadding="0" cellspacing="0"  height="100%" align="center">
        <tr>
			<td valign="top">
				<table width="100%" cellpadding="0" cellspacing="0"  align="center" id="header">
					  <tr>
							<?
							if ($this->hideDisplayMenuHeader != ""){?>
		    					<td colspan="10" width="20%" valign="top" bgcolor="#dbdee9" style="display:none">
									<?=$this->layout()->header;?></td>
		    				<?}else{?>
		    					<td  colspan="10" width="5%" valign="top">
									<?=$this->layout()->header;?>

								</td>
		    				<?}?>				    			
					  </tr>
					  <tr>
					    <td width="100%" valign="top" >
					    	<table  width="100%" cellpadding="0" cellspacing="0" class="body1" border="0">
					    		<tr>
					    			<? 					    			
				    				$statusLeftMenu = "block";
				    				if ($this->hideDisplayMeneLeft == ""){
				    					$statusLeftMenu = "none";
				    				}?>
			    				 	<td width="5%" valign="top" style="display:<?=$statusLeftMenu;?>;" id="Iddiv_leftmenu">
										<?=$this->layout()->left;?>
									</td>								 		
									<?php 
									 //if ($this->showModelDialog != 1) {?>	
				    					 <!-- <td valign="middle" class="anmenu"><img id="pictureShowHileMenu" src="<? //=$this->ShowHideimageUrlPath;?>" onclick="showHideMenuLeft('showHideMenu');" title="Ẩn hoặc hiện menu"></td>-->										    		
					    			<?php // }  ?>
				    				<td  width="100%" style="background:#fff;" valign="top">
					    				<?=$this->layout()->content;?>
					    			</td>
					    		</tr>						    		
					    	</table>		    	
						</td>
					  </tr>
					  <tr>
							<?
							if ($this->hideDisplayMenuFooter != ""){?>
		    					<td colspan="10" width="20%" valign="top" bgcolor="#dbdee9" style="display:none">
									<?=$this->layout()->footer;?>
								</td>
		    				<?}else{?>
		    					<td  colspan="10" width="5%" valign="top">
									<?=$this->layout()->footer;?>
								</td>
		    				<?}?>
				      </tr>					
				</table>

			</td>
		</tr>
	</table>
    </div>
   </td>
		
</tr>

</table> 
	<SCRIPT type="text/javascript"> 
		remove_loading();
	</SCRIPT>
</body>
</html>
