<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><!--
<META http-equiv=Page-Exit content=progid:DXImageTransform.Microsoft.Fade(duration=.5)>!-->
<title>Phần mềm DH & QLVB</title>
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl?>style/style.css">
<link rel="icon" href="../../favicon.ico" type="image/x-icon" />

<?= $this->JSPublicConst;?>
<!--Menu-->
<script src="<?= $this->baseUrl?>js/util.js" type="text/javascript"></script>
<!--Calendar-->
<!--<script src="<?= $this->baseUrl?>zapatec/utils/zapatec.js" type="text/javascript"></script>
<script src="<?= $this->baseUrl?>zapatec/zpcal/src/calendar.js" type="text/javascript"></script>
<script src="<?= $this->baseUrl?>zapatec/zpcal/lang/calendar-en.js" type="text/javascript"></script>
<link href="<?= $this->baseUrl?>zapatec/zpcal/themes/wood.css" rel="stylesheet" />-->
<!--Load javascript va Css cho Tung module-->
<?php
	echo $this->LoadAllFileJsCss;
?>
<!--Ket thuc load -->

<!--Doan process-->
<SCRIPT type=text/javascript>
var t_id = setInterval(animate,1);
var pos=0;
var dir=2;
var len=0;
function animate(){
	var elem = document.getElementById('progress');
	if(elem != null) {
	if (pos==0) len += dir;
	if (len>32 || pos>79) pos += dir;
	if (pos>79) len -= dir;
	if (pos>79 && len==0) pos=0;
	elem.style.left = pos;
	elem.style.width = len;
}
}
function remove_loading() {
this.clearInterval(t_id);
var targelem = document.getElementById('loader_container');
targelem.style.display='none';
targelem.style.visibility='hidden';

}
</SCRIPT>

<STYLE type=text/css>
	#interface1 {Z-INDEX: 1}
	#loader_container {WIDTH: 100%; POSITION: absolute; TOP: 40%; left:0%; TEXT-ALIGN: center}
	#loader {BORDER-RIGHT: #6a6a6a 1px solid; PADDING-RIGHT: 0px; BORDER-TOP: #6a6a6a 1px solid; DISPLAY: block; PADDING-LEFT: 0px; FONT-SIZE: 11px; Z-INDEX: 2; PADDING-BOTTOM: 16px; MARGIN: 0px auto; BORDER-LEFT: #6a6a6a 1px solid; WIDTH: 130px; COLOR: #000000; PADDING-TOP: 10px; BORDER-BOTTOM: #6a6a6a 1px solid; FONT-FAMILY: Tahoma, Helvetica, sans; BACKGROUND-COLOR: #ffffff; TEXT-ALIGN: left}
	#progress {FONT-SIZE: 1px; LEFT: 0px; WIDTH: 1px; POSITION: relative; TOP: 1px; HEIGHT: 5px; BACKGROUND-COLOR: #7B79C7}
	#loader_bg {FONT-SIZE: 1px; LEFT: 8px; WIDTH: 113px; POSITION: relative; TOP: 8px; HEIGHT: 7px; BACKGROUND-COLOR: #ebebe4}
</STYLE>
<DIV id=loader_container>
<DIV id=loader>
<DIV align=center id=contentload>&#272;ang x&#7917; l&#253; d&#7919; li&#7879;u...<br>
	&#7844;n <b><font color="#FF0000">F5</font></b> N&#7871;u x&#7917; l&#253; qu&#225; l&#226;u

</DIV>
<DIV id=loader_bg>
<DIV id=progress></DIV></DIV></DIV></DIV>
<DIV id=interface1 style="DISPLAY: inline; VISIBILITY: visible">
<DIV style="LEFT: 1px; VISIBILITY: hidden; POSITION: absolute; TOP: 1px"></DIV>
<DIV style="DISPLAY: none; LEFT: 0px; POSITION: absolute; TOP: 0px">
</DIV>
<!--ket thuc-->
</head>
<body topmargin="0" leftmargin="0" marginheight="0" marginwidth="0" rightmargin="0" width="100%">
    <table width="100%" border="0" cellpadding="0" cellspacing="0"  height="100%" align="center">
        <tr>
            <td  width="95%" valign="top">
                <?=$this->layout()->content;?>
            </td>
        </tr>						    		
	</table>
	<SCRIPT type="text/javascript"> 
		remove_loading();
	</SCRIPT>

</body>
</html>
