<form action="index" method="POST" id="frmAddReceived" enctype="multipart/form-data" autocomplete="off"><?php 	
	$urlCalendar = $this->urlCalendar; 
	$arrCount = $this->arrCount;
	$arrSendReceived = $this->arrSendReceived;
	$sOwnerCode  = $this ->Owner;
	if($arrReceived[0]['C_NUM_DOCUMENT'] =='' || $arrReceived[0]['C_NUM_DOCUMENT'] == null){
		$arrReceived[0]['C_RECEIVE_BOOK'] = '';
	}?>
	<table cellpadding="0" cellspacing="0" width="100%" border="0">
		<!--tao tac hidden!-->
		<tr>
			<td>
				<?php echo $this->formHidden("hdnCode","",null); ?>
				<!--Sinh mot hidden luu ID loai danh muc!-->
				<?php echo $this->formHidden("hdn_object_id",$this->pSendReceiveDocumentId,null); ?>		
				<!--Bien hdn_xml_tag_list dung de luu danh sach cac THE XML tuong ung voi cac THUOC TINH cua mot doi tuong dang duoc cap nhat-->			
				<?php echo $this->formHidden("hdn_xml_tag_list",'',null); ?>			
				<!--Bien hdn_xml_value_list dung de luu danh sach cac gia tri cua cac THE XML tuong ung voi cac THUOC TINH cua mot doi tuong-->			
				<?php echo $this->formHidden("hdn_xml_value_list",'',null); ?>			
				<!--Sinh mot hidden luu list ID ma NSD chon!-->
				<?php echo $this->formHidden("hdn_object_id_list","",null); ?>	
				<!--Hidden luu gia tri cua list tag va list value (TagList|{*^*}|ValueList) -->
				<?php echo $this->formHidden("hdn_XmlTagValueList",$this->XmlTagValueList,null); ?>
				<!--Bien hdn_page dung de luu chi so trang hien thi hien thoi-->			
				<?php echo $this->formHidden("hdn_current_page",$this->currentPage,null); ?>	
				<!--Sinh mot hidden luu gia tri xac dinh so ban ghi / 1 trang!-->	
				<?php echo $this->formHidden("hdn_record_number_page",$this->numRowOnPage,null); ?>	
				<!--Bien hdn_filter_xml_tag_list dung de luu danh sach cac THE XML tuong ung voi cac tieu thuc loc tren giao dien DANH SACH DOI TUONG-->
				<?php echo $this->formHidden("hdn_filter_xml_tag_list",$this->filterXmlTagList,null); ?>
				<!--Bien hdn_filter_xml_tag_list dung de luu gia tri cua cac THE XML tuong ung voi cac tieu thuc loc tren giao dien DANH SACH DOI TUONG-->	
				<?php echo $this->formHidden("hdn_filter_xml_value_list",$this->filterXmlValueList,null); ?>
				<!--Bien hdn_deleted_new_file_id_list dung de luu Id cua nhung doi tuong file dinh kem se xoa-->	
				<?php echo $this->formHidden("hdn_deleted_new_file_id_list","",null); ?>	
				<!--Bien hdn_deleted_exist_file_id_list dung de ...-->	
				<?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null); ?>	
				<?php echo $this->formHidden("hdh_option",$this->option,null); ?>	
				<?php echo $this->formHidden("hdn_doc_type","",null); ?>
				<?php echo $this->formHidden("hdn_signer_position_name","",null); ?>
				<?php echo $this->formHidden("hdn_staff_id_list","",null); ?>
				<?php echo $this->formHidden("hdn_unit_id_list","",null); ?>
				<?php echo $this->formHidden("htn_leftModule",$this->currentModulCodeForLeft,null); ?>	
			</td>
		</tr>
	</table>

	<!--HIen thi tieu de man hinh danh sach!-->
	<div id ="content">
		<table style="width:100%;">
			<tr>
				<td class="large_title" style="padding-left:0px;text-align:left; width:40%;">
						<?=$this->bodyTitle;?>
					</td>
					<td style="text-align:right; float:right; width:auto;">
						<a class="small_link" onClick="document.getElementById('hdh_option').value='GHI_THEMMOI';btn_save_sendreceived(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'','<?=date("d/m/Y");?>');"><?=$arrCount['_GHI_THEM_MOI']?></a> 
						<a class="small_link" onClick="document.getElementById('hdh_option').value='GHI_THEMTIEP';btn_save_sendreceived(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'','<?=date("d/m/Y");?>');"><?=$arrCount['_GHI_THEM_TIEP']?></a> 
						<a class="small_link" onClick="document.getElementById('hdh_option').value='GHI_QUAYLAI';btn_save_sendreceived(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'','<?=date("d/m/Y");?>');"><?=$arrCount['_GHI_QUAY_LAI']?></a> 
						<a class="small_link" onClick="document.getElementById('hdh_option').value='GHI_TAM';btn_save_sendreceived(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'','<?=date("d/m/Y");?>');"><?=$arrCount['_GHI_TAM']?></a> 
						<a class="small_link" onclick="document.getElementById('hdh_option').value='QUAY_LAI';document.getElementsByTagName('form')[0].action = '';document.getElementsByTagName('form')[0].submit();"><?=$arrCount['_QUAY_LAI']?></a>	
					</td>
			</tr>
	</table>	
		<div id="body_conten1">
				<div id ="body_conten1_left">
					<div style="margin-top:5px;">
						<label>1. &nbsp;<?=$arrCount['_LOAI_VAN_BAN']?><span class="requiein">*</span></label>
						<input class="textbox" tabindex="1" style="width:64%" value="<?=$arrSendReceived[0]['C_DOC_TYPE']?>" id ="C_DOC_TYPE" name="C_DOC_TYPE" type="text"  option = "false"  xml_tag_in_db="" xml_data="false" column_name="C_DOC_TYPE" message="<?php echo "Phai xac dinh LOAI VAN BAN!";?>" onKeyDown="change_focus(document.forms[0],this)" onblur="showinvation(this);">
					</div>
					<div>
						<label>2. &nbsp;<?=$arrCount['_NGAY_PHAT_HANH']?><span class="requiein">*</span></label>
						<input class="textbox" tabindex="2" style="width:20%;"  value="<?=Sys_Library::_yyyymmddToDDmmyyyy($arrSendReceived[0]['C_RELEASE_DATE'])?>" id ="C_RELEASE_DATE" name="C_RELEASE_DATE" type="text" isdate="true" option = "false"  xml_tag_in_db="" xml_data="false" column_name="C_RELEASE_DATE" message="<?php echo "NGAY PHAT HANH khong dung dinh dang ngay/thang/nam!";?>" onKeyDown="change_focus(document.forms[0],this)">						
					</div>
					<div>
						<label>3. &nbsp;<?=$arrCount['_SO_KY_HIEU'] ?></label>
						<input class="textbox" tabindex="3" style="width:64%;" value="<?=$arrSendReceived[0]['C_SYMBOL']?>" id ="C_SYMBOL" name="C_SYMBOL" type="text"  optional = "true"  xml_tag_in_db="" xml_data="false" column_name="C_SYMBOL" onKeyDown="change_focus(document.forms[0],this)">
					</div>
					<?php
						$sdocType = $arrSendReceived[0]['C_DOC_TYPE'];
						$bdspGM = "none";
						if($sdocType == 'Giấy mời'){
							$bdspGM = 'block';
						}
					 ?>
					<div id="thoigianhop" style="display:<?=$bdspGM?>;">
							<label>4. &nbsp;<?=$arrCount['_THOI_GIAN_HOP']?><span class="requiein">*</span> </label>
							<input class="textbox" tabindex="4" style="width:18%;" type="text" value="<?=$arrSendReceived[0]['C_HOURS']?>" name="C_HOURS" id="C_HOURS" option ="" optional = "true"  xml_tag_in_db="" xml_data="false" column_name="C_HOURS" message="<?php echo "Phai xac dinh THOI GIAN HOP!";?>" onKeyDown="change_focus(document.forms[0],this)" />
							<label style="float:none;clear:none; display:inline;">5. &nbsp;<?=$arrCount['_NGAY_HOP']?><span class="requiein">*</span> </label>
							<input class="textbox" tabindex="5" style="width:16%;" value="<?=Sys_Library::_yyyymmddToDDmmyyyy($arrSendReceived[0]['C_DATE'])?>" id ="C_DATE" name="C_DATE" type="text" isdate="false" option ="" optional = "true"  xml_tag_in_db="" xml_data="false" column_name="C_DATE" message="<?php echo "NGAY HOP khong dung dinh dang ngay/thang/nam!";?>" onKeyDown="change_focus(document.forms[0],this)">
							<img src="<?= $this->baseUrl?>images/calendar.gif" border="0" onclick="DoCal('<?= $urlCalendar;?>',document.getElementById('C_DATE'));" style="cursor:pointer">	 
					</div>
					<?php
						if($bdspGM == 'none')
							$iindex = 3;
						else
							$iindex = 6;
					?>
					<div id="diadiem" style="display:<?=$bdspGM?>;">
						<label>6. &nbsp;<?=$arrCount['_DIA_DIEM_HOP']?><span class="requiein">*</span> </label>
						<input class="textbox" tabindex="6" style="width:64%;" type="text" value="<?=$arrSendReceived[0]['C_ADDRESS']?>" name="C_ADDRESS" id="C_ADDRESS" option ="" optional = "true"  xml_tag_in_db="" xml_data="false" column_name="C_ADDRESS" message="<?php echo "Phai xac dinh DIA DIEM HOP!";?>" onKeyDown="change_focus(document.forms[0],this)" />
					</div>
					<div>
						<label id="1"><?=$iindex +=1;?>. &nbsp;<?=$arrCount['_TRICH_YEU']?><span class="requiein">*</span> </label>
						<textarea tabindex="7" style="width:64%" class="textbox normal_textarea" id="C_SUBJECT" option = "false" rows="2" name="C_SUBJECT" xml_tag_in_db="" xml_data="false" column_name="C_SUBJECT" message="<?php echo "Phai xac dinh TRICH YEU van ban!";?>"><?=$arrSendReceived[0]['C_SUBJECT']?></textarea>
					</div>
					<div>
						<label id="2"><?=$iindex +=1;?>. &nbsp;<?=$arrCount['_DO_KHAN']?><span class="requiein">*</span> </label>
						<select class="textbox" tabindex="8" id="C_TEXT_OF_EMERGENCY" name="C_TEXT_OF_EMERGENCY" option = "false" class="textbox normal_label"  xml_tag_in_db="" xml_data="false" column_name="C_TEXT_OF_EMERGENCY" message="<?php echo "Phai xac dinh DO KHAN van ban!";?>">
							<option id="" name = "" value="">-- Chọn độ khẩn --</option><?php
							$arrUrgent = $this->arrUrgent;
							echo Sys_Library::_generateSelectOption($arrUrgent,'C_CODE','C_CODE','C_NAME',Sys_Library::_getCodeByName($arrUrgent,$arrSendReceived[0]['C_TEXT_OF_EMERGENCY'],'C_CODE'));?>
						</select>
					</div>
					<div>
						<label id="3"><?=$iindex +=1;?>. &nbsp;<?=$arrCount['_NGUOI_KY']?><span class="requiein">*</span> </label>
						<input class="textbox" tabindex="9" style="width:64%" value="<?=$arrSendReceived[0]['C_SIGNER_POSITION_NAME']?>" id ="C_SIGNER_POSITION_NAME" name="C_SIGNER_POSITION_NAME" type="text"  option = "false"  xml_tag_in_db="" xml_data="false" column_name="C_SIGNER_POSITION_NAME" message="<?php echo "Phai xac dinh NGUOI KY van ban!";?>" onKeyDown="change_focus(document.forms[0],this)">
					</div>
					<div>
						<label id="4"><?=$iindex +=1;?>. &nbsp;<?=$arrCount['_SO_BAN']?></label>
						<input class="textbox" tabindex="10" style="width:20%;" value="<?=$arrSendReceived[0]['C_NUMBER_SHEET']?>" id ="C_NUMBER_SHEET" name="C_NUMBER_SHEET" type="text" isnumeric = "false"  option = "true"  xml_tag_in_db="" xml_data="false" column_name="C_NUMBER_SHEET" message="<?php echo "SO BAN phai la so nguyen duong (1,2,3,…)!";?>"  onKeyDown="change_focus(document.forms[0],this)">
					
						<label style="float:none;clear:none; display:inline;" id="5"><?=$iindex +=1;?>. &nbsp;<?=$arrCount['_SO_TRANG']?></label>
						<input class="textbox" tabindex="11" style="width:21%;" value="<?=$arrSendReceived[0]['C_NUMBER_PAGE']?>" id ="C_NUMBER_PAGE" name="C_NUMBER_PAGE" type="text" isnumeric = "false"  option = "true"  xml_tag_in_db="" xml_data="false" column_name="C_NUMBER_PAGE" message="<?php echo "SO TRANG phai la so nguyen duong (1,2,3,…)!";?>" onKeyDown="change_focus(document.forms[0],this)">
					</div>
				</div><!-- End #body_conten1_left-->
				<div id="body_conten1_right">
					<div>
						<label id="6"><?=$iindex +=1;?>. &nbsp;<?=$arrCount['_THONG_TIN_KHAC']?></label>
						<textarea tabindex="12" style="width:98%; margin-left:1%;" class="textbox normal_textarea" id="C_OTHER" optional = "true" rows="2" cols="3" name="C_OTHER" ><?=$arrSendReceived[0]['C_OTHER']?></textarea>
					</div>
					<div>
						<label id="7"><?=$iindex +=1;?>. <?=$arrCount['_CAN_BO_NHAN']?></label>
						<textarea tabindex="13" style="width:98%;margin-left:1%;" class="textbox normal_textarea" id="C_STAFF_ID_LIST" optional = "true" rows="2" name="C_STAFF_ID_LIST"><?php
							if($arrSendReceived[0]['C_STAFF_ID_LIST'] != '')
								echo $arrSendReceived[0]['C_STAFF_NAME_LIST'];
						?></textarea>
					</div>
					<div>
						<label style="width:55%;" id="8"><?=$iindex +=1;?>. <?=$arrCount['_DON_VI_PHONG_BAN_NHAN']?></label>
						<textarea tabindex="14" style="width:98%;margin-left:1%;" class="textbox normal_textarea" id="C_UNIT_ID_LIST" optional = "true" rows="2" name="C_UNIT_ID_LIST"><?=$arrSendReceived[0]['C_UNIT_NAME_LIST']?></textarea>
					</div>
					<div>
						<label style="width:98%;" id="9"><?=$iindex +=1;?>. <?=$arrCount['_FILE_DINH_KEM']?></label>
					</div>		
					<div id="viewStatusDeleteAttachment"></div>		
					<?=$this->AttachFile;?>
				</div><!-- End #body_conten1_right-->
				<div id="clear"></div>
		</div><!-- End #body_conten1-->
		
	</div><!-- End #content-->	
	
	<!--Hien thi nut!-->		
	<table style="margin-top:10px; border-top: #3399FF 1px solid;" width='98%'  border='0' cellspacing='0' cellpadding='0' align='center' class='normal_label'>
		<tr>
			<td align="center" style="padding:10px 0;">	
				<button name="btn_ghivathemmoi" id="btn_ghivathemmoi" type="button" value="Ghi&amp;Thêm mới" class="add_large_button" onClick="document.getElementById('hdh_option').value='GHI_THEMMOI';btn_save_sendreceived(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'','<?=date("d/m/Y");?>');"><?=$arrCount['_GHI_THEM_MOI']?></button>
				<button name="btn_ghivathemtiep" id="btn_ghivathemtiep" type="button" value="Ghi&amp;Thêm tiếp" class="add_large_button" onClick="document.getElementById('hdh_option').value='GHI_THEMTIEP';btn_save_sendreceived(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'','<?=date("d/m/Y");?>');"><?=$arrCount['_GHI_THEM_TIEP']?></button>
				<button name="btn_ghivaquaylai" id="btn_ghivaquaylai" type="button" value="Ghi&amp;Quay lại" class="add_large_button" onClick="document.getElementById('hdh_option').value='GHI_QUAYLAI';btn_save_sendreceived(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'','<?=date("d/m/Y");?>');"><?=$arrCount['_GHI_QUAY_LAI']?></button>
				<button name="btn_ghitam" id="btn_ghitam" type="button" value="Ghi tạm" class="add_large_button" onClick="document.getElementById('hdh_option').value='GHI_TAM';btn_save_sendreceived(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'','<?=date("d/m/Y");?>');"><?=$arrCount['_GHI_TAM']?></button>
				<input type="submit" name="quaylai" id="quaylai" value="<?=$arrCount['_QUAY_LAI']?>" onClick="document.getElementById('hdh_option').value='QUAY_LAI';document.getElementsByTagName('form')[0].action = ''" class="add_large_button">
			</td>
		</tr>			
	</table>	
</form>
<?php echo $this->search_textselectbox_doc_type; ?>
<?php echo $this->search_textselectbox_signer; ?>
<?php echo $this->search_textselectbox_staff; ?>
<?php echo $this->search_textselectbox_unit; ?>
<script type="text/javascript">


//Bat su kien khi NSD nhan cac phim tat sau
shortcut.add("Ctrl+M",function() {
	document.getElementById('hdh_option').value='GHI_THEMMOI';
	btn_save_sendreceived(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'','<?=date("d/m/Y");?>');
});

shortcut.add("Ctrl+E",function() {
	document.getElementById('hdh_option').value='GHI_THEMTIEP';
	btn_save_sendreceived(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'','<?=date("d/m/Y");?>');
});
shortcut.add("Ctrl+Q",function() {
	document.getElementById('hdh_option').value='GHI_QUAYLAI';
	btn_save_sendreceived(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'','<?=date("d/m/Y");?>');
});

shortcut.add("Ctrl+G",function() {
	document.getElementById('hdh_option').value='GHI_TAM';
	btn_save_sendreceived(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'','<?=date("d/m/Y");?>');
});
shortcut.add("Ctrl+B",function() {
	document.getElementById('hdh_option').value='QUAY_LAI';
	document.getElementsByTagName('form')[0].action = '';
	document.getElementsByTagName('form')[0].submit();
});
shortcut.add("Tab",function() {
	alert(tabindex)
});

if("<?=$arrReceived[0]['C_DOC_TYPE']?>" == "MH"){
	document.getElementById('divMoiHop').style.display = "block";
}

//Hien thi form truong hop loai van ban la giay moi
function showinvation(obj){
		if(obj.value =='Giấy mời'){
			document.getElementById('thoigianhop').style.display = "block";
			document.getElementById('diadiem').style.display = "block";
			
			document.getElementById('C_HOURS').setAttribute("option","false");
			document.getElementById('C_HOURS').setAttribute("optional","");
			
			document.getElementById('C_DATE').setAttribute("option","false");
			document.getElementById('C_DATE').setAttribute("optional","");
			document.getElementById('C_DATE').setAttribute("isdate","true");
			
			document.getElementById('C_ADDRESS').setAttribute("option","false");
			document.getElementById('C_ADDRESS').setAttribute("optional","");
			var start = 6;
			for(var i = 1; i<=9; i++){
				start +=1;
				var str = start +'. '+ document.getElementById(i).innerHTML.slice(3);
				document.getElementById(i).innerHTML = str;
			}
		}
		else{
			var start = 3;
			for(var i = 1; i<=9; i++){
				start +=1;
				var str = start +'. '+ document.getElementById(i).innerHTML.slice(3);
				document.getElementById(i).innerHTML = str;
			}
			document.getElementById('thoigianhop').style.display = "none";
			document.getElementById('diadiem').style.display = "none";
			
			document.getElementById('C_HOURS').setAttribute("option","");
			document.getElementById('C_HOURS').setAttribute("optional","true");
			
			document.getElementById('C_DATE').setAttribute("option","");
			document.getElementById('C_DATE').setAttribute("optional","true");
			document.getElementById('C_DATE').setAttribute("isdate","false");
			
			document.getElementById('C_ADDRESS').setAttribute("option","");
			document.getElementById('C_ADDRESS').setAttribute("optional","true");
		}
}

</script>
<script type = "text/javascript">
$(function() {
	$( "#C_RELEASE_DATE" ).datepicker({
		changeMonth: true,
		gotoCurrent: true,
		maxDate: '+1m +1w',
		minDate: new Date(1945, 1 - 1, 1),
		changeYear: true
	});	
});
</script>
