<script src="/Sys-doc-boxd/public/Sys-js/jquery-1.4.2.min.js" type="text/javascript"></script>
<form action="index" method="POST" id="frmsheduleStaff" autocomplete="off">
	<?php echo $this->formHidden("hdn_type","",null); ?>
	<!--Cac doi tuong hidden tren form-->	
	<?php echo $this->formHidden("hdn_object_id_list","",null); ?>	
	<?php echo $this->formHidden("hdn_object_id",$this->scheduleID,null); ?>
	<?php echo $this->formHidden("hdn_doc_id",$this->pDocId,null); ?>	
	<?php echo $this->formHidden("htn_leftModule",$this->currentModulCodeForLeft,null); ?>				
	<?php echo $this->formHidden("htn_schedule_update",$this->currentUpdate,null); ?>		
	<?php echo $this->formHidden("hdn_week",$this->$v_week); ?>		
	<?php echo $this->formHidden("hdn_year",$this->$v_year); ?>
	<?php echo $this->formHidden("hdn_pb_name","",null); ?>	
	<?php echo $this->formHidden("hdn_exporttype","1"); ?>	
	<?php
		$arrCount = $this->arrCount;		
		$arryWekk = $this->arryWekk;
		$arryYear = $this->arryYear;	
		$arrDateInWeek = $this->arrDateInWeek;
		$arry_date_in_week = explode('!@#',$arrDateInWeek);				
		$arrySchedule_Staff = $this->arrySchedule_Staff;
		$arrDepartmentLeader = $this->arrDepartmentLeader;
		$arrVp = $this->arrVp;		
		$objDocFun = new Sys_Function_DocFunctions();
		//KIEM TRA NEU LA CV TRONG VAN PHONG THI SE LAY LANH DAO CUA VP
		if($arrDepartmentLeader == ''){
			
			$arrDepartmentLeader = $arrVp;
		}
		$p_year = date('Y');
		$v_count_leader = sizeof($arrDepartmentLeader);
		$v_list_id_leader ='';
		$v_col_string = '<col width="12%"><col width="8%">';
		$v_col_width = 80/$v_count_leader;
		for($i=0;$i<$v_count_leader;$i++){
			$v_col_string = $v_col_string.'<col width="'.$v_col_width.'%">';	
			$v_list_id_leader = $v_list_id_leader.$arrDepartmentLeader[$i]['id'].',';
			
			$arr_mon[$i] = explode('!~~!',$arrySchedule_Staff[$i]['C_MON']); // THU 2
			$arr_mon_am[$i] = $arr_mon[$i][0];
			$arr_mon_pm[$i] = $arr_mon[$i][1];	
						
			$arr_tue[$i] = explode('!~~!',$arrySchedule_Staff[$i]['C_TUE']); // THU 3
			$arr_tue_am[$i] = $arr_tue[$i][0];
			$arr_tue_pm[$i] = $arr_tue[$i][1];
	
			$arr_wed[$i] = explode('!~~!',$arrySchedule_Staff[$i]['C_WED']); // THU 4
			$arr_wed_am[$i] = $arr_wed[$i][0];
			$arr_wed_pm[$i] = $arr_wed[$i][1];
			
			$arr_thu[$i] = explode('!~~!',$arrySchedule_Staff[$i]['C_THU']); // THU 5
			$arr_thu_am[$i] = $arr_thu[$i][0];
			$arr_thu_pm[$i] = $arr_thu[$i][1];
	
			$arr_fri[$i] = explode('!~~!',$arrySchedule_Staff[$i]['C_FRI']); // THU 6
			$arr_fri_am[$i] = $arr_fri[$i][0];
			$arr_fri_pm[$i] = $arr_fri[$i][1];
	
			$arr_sat[$i] = explode('!~~!',$arrySchedule_Staff[$i]['C_SAT']); // THU 7
			$arr_sat_am[$i] = $arr_sat[$i][0];
			$arr_sat_pm[$i] = $arr_sat[$i][1];
	
			$arr_sun[$i] = explode('!~~!',$arrySchedule_Staff[$i]['C_SUN']); // CN
			$arr_sun_am[$i] = $arr_sun[$i][0];
			$arr_sun_pm[$i] = $arr_sun[$i][1];
		}
	?>		
	<table>
		<tr>
			<td class="large_title" style="padding-left:7px;text-align:left;">
				<?=$this->bodyTitle;?>				
			</td>
		</tr>
	</table>
	<!--Phan hien thi Tuan trong nam va Nam -->
	<div class="box container c1">
		<div class="pad">			
			<table cellpadding="0" cellspacing="0" width="100%" border="0" style="padding-left:0%;">				
				<tr>
					<td width="4%" class="normal_label" valign="middle"><?=$arrCount['_TUAN']?>	</td>
					<td  valign="top" width="20%" valign="top">
						
					<select name="cbo_week" id="cbo_week" style="width:auto;" class="textbox" onchange="document.getElementById('hdn_week').value = this.value; document.forms['frmsheduleStaff'].submit();" >					
						<? echo $arryWekk; ?>				
					</select>
			 </td>
			<td width="3%" class="normal_label" valign="middle"><?=$arrCount['_NAM']?></td>
						<td  style="padding-left:10px;">
							<select name="cbo_year" id="cbo_year" class="textbox" valign="top" style="width:auto;" onchange="document.getElementById('hdn_year').value = this.value;  document.forms['frmsheduleStaff'].submit();" >
								<? echo $arryYear;?>
							</select>											
					</td>
				</tr>
			</table>
		</div>
	</div>	
	<!--Phan hien thi Link cap nhat -->	
	
<!--Phan hien thi Noi dung cap nhat lich -->	
<table class="schedule_staff" cellpadding="0" cellspacing="0" width="98%" id="table1" style="margin-top: 10px;"> 
<!-- Hien thi so Col-->
<?php echo 	$v_col_string;?>
  <tr>
    <th colspan="2" scope="col">Thời gian</th>    
    <?
	if($arrDepartmentLeader !=''){
    foreach ($arrDepartmentLeader as $Result) {?>
    	<th scope="col"><? echo  $Result['position_code'];?> - <? echo  $Result['name'];?></th>	
    <?} } ?>       
  </tr>
  <tr>
    <td rowspan="2"><? echo $arry_date_in_week[0];?></td>
    <td><?=$arrCount['_SANG']?></td>
    <?php echo $objDocFun->write_td($v_count_leader,$arr_mon_am,''); ?>
  </tr>
  
  <tr >
    <td><?=$arrCount['_CHIEU']?></td>
	<?php echo $objDocFun->write_td($v_count_leader,$arr_mon_pm,''); ?>
  </tr>  
  <tr class="newBackgroud">
    <td rowspan="2"><? echo $arry_date_in_week[1];?></td>
    <td><?=$arrCount['_SANG']?></td>
    <?php echo $objDocFun->write_td($v_count_leader,$arr_tue_am,''); ?>
  </tr>
  <tr>
    <td class="newBackgroud"><?=$arrCount['_CHIEU']?></td>
    <?php echo $objDocFun->write_td($v_count_leader,$arr_tue_pm,'1'); ?>
  </tr>
  
  <tr>
    <td rowspan="2"><? echo $arry_date_in_week[2];?></td>
    <td><?=$arrCount['_SANG']?></td>
    <?php echo $objDocFun->write_td($v_count_leader,$arr_wed_am,''); ?>
  </tr>
  <tr>
    <td><?=$arrCount['_CHIEU']?></td>
    <?php echo $objDocFun->write_td($v_count_leader,$arr_wed_pm,''); ?>
  </tr>
  <tr class="newBackgroud">
    <td rowspan="2"><? echo $arry_date_in_week[3];?></td>
    <td><?=$arrCount['_SANG']?></td>
    <?php echo $objDocFun->write_td($v_count_leader,$arr_thu_am,''); ?>
  </tr>
  <tr>
    <td class="newBackgroud"><?=$arrCount['_CHIEU']?></td>
      <?php echo $objDocFun->write_td($v_count_leader,$arr_thu_pm,'1'); ?>
  </tr>
  <tr>
    <td rowspan="2"><? echo $arry_date_in_week[4];?></td>
    <td><?=$arrCount['_SANG']?></td>
   <?php echo $objDocFun->write_td($v_count_leader,$arr_fri_am,''); ?>
  </tr>
  <tr>
    <td><?=$arrCount['_CHIEU']?></td>
    <?php echo $objDocFun->write_td($v_count_leader,$arr_fri_pm,''); ?>
  </tr>
  <tr class="newBackgroud">
    <td rowspan="2"><? echo $arry_date_in_week[5];?></td>
    <td><?=$arrCount['_SANG']?></td>
    <?php echo $objDocFun->write_td($v_count_leader,$arr_sat_am,''); ?>
  </tr>
  <tr>
    <td class="newBackgroud"><?=$arrCount['_CHIEU']?></td>
    <?php echo $objDocFun->write_td($v_count_leader,$arr_sat_pm,'1'); ?>
  </tr>
  <tr>
    <td rowspan="2"><? echo $arry_date_in_week[6];?></td>
    <td><?=$arrCount['_SANG']?></td>
    <?php echo $objDocFun->write_td($v_count_leader,$arr_sun_am,''); ?>
  </tr>
  <tr>
    <td><?=$arrCount['_CHIEU']?></td>
    <?php echo $objDocFun->write_td($v_count_leader,$arr_sun_pm,''); ?>
  </tr>
</table>

	<table width='100%'  border='0' cellspacing='0' cellpadding='0' align="center">		
		<tr>
			<td style="padding-top: 10px; padding-bottom: 10px;" align="center" valign="middle">								
				<input type="button" class="add_large_button" value="<?=$arrCount['_IN_DANG_WEB']?>"  onclick=" btn_print_schedule_onclick('../printleader/',document.getElementById('hdn_week').value,document.getElementById('hdn_year').value,document.getElementById('cbo_week').options[document.getElementById('cbo_week').selectedIndex].text,'LICH_LANH_DAO_PB','1');">
				<input type="button" class="add_large_button" value="<?=$arrCount['_IN_DANG_WORD']?>" onclick=" btn_print_schedule_onclick('../printleader/',document.getElementById('hdn_week').value,document.getElementById('hdn_year').value,document.getElementById('cbo_week').options[document.getElementById('cbo_week').selectedIndex].text,'LICH_LANH_DAO_PB','2');">				
			</td>	
		</tr>
	</table>	
</div>
</form>
<script type="text/javascript">
shortcut.add("Ctrl+K",function() {
	document.getElementById('txtfullTextSearch').focus();
	document.getElementById('txtfullTextSearch').select();
});
function ResetSearch(){
	document.getElementById('hdn_current_page').value = "1";
	
}
function checkvalue(){
	if(document.getElementById('txtfullTextSearch').value != ""){
		actionUrl('');
	}
}

	document.getElementById('hdn_week').value = document.getElementById('cbo_week').value ;
	document.getElementById('hdn_year').value = document.getElementById('cbo_year').value; 
	document.getElementById('hdn_object_id').value ='<? echo $arrySchedule_Staff[0]['PK_SCHEDULE_STAFF']; ?>' 	
</script>

