 <table width="100%" cellpadding="0" cellspacing="0" align="center" height="50" class="footer_info_table" id="tbl_footer">
	<tr id="tr_footer">
		 <TD class="detail"><b>Trung Tâm CNTT Tây Bắc - Sở TT&TT tỉnh Phú Thọ</b>
				<br/>	Địa chỉ: <a style="color: #047FA5;" href="#">đường Nguyễn Tất Thành, Phường Tân Dân, thành phố Việt Trì, tỉnh Phú Thọ.</a>&nbsp;&nbsp;&nbsp;
			</TD>		
		</tr>			
</table>	
<br/><br/>