<base target=_self>
<form action="index" method="POST" id="frmReceived" autocomplete="off">
<div>
	<!--Cac doi tuong hidden tren form-->
	<?php echo $this->formHidden("hdn_docrelate_id_list","",null); ?>
	<?php echo $this->formHidden("hdn_filter_xml_tag_list",$this->filterXmlTagList,null); ?>
	<?php echo $this->formHidden("hdn_filter_xml_value_list",$this->filterXmlValueList,null); ?>
	<?php echo $this->formHidden("hdn_object_id",$this->sReceiveDocumentId,null); ?>
	<?php echo $this->formHidden("hdn_save","",null); ?>
	<?php echo $this->formHidden("hdn_XmlTagValueList",$this->XmlTagValueList,null); ?>
	<?php echo $this->formHidden("hdn_current_page",$this->iCurrentPage,null); ?>
	<?php echo $this->formHidden("cbo_nuber_record_page",$this->iNumRowOnPage,null); ?>
	<?php echo $this->formHidden("hdn_record_number_page",$this->iNumRowOnPage,null); ?>
	<?php echo $this->formHidden("hdn_advande_search",$this->sadvandeSearch,null); ?>
	<?php echo $this->formHidden("hdn_option_search",$this->iOptionSearch,null); ?>
	<?php echo $this->formHidden("hdn_type","",null); ?>
	<?php
		$arrConst 				= $this->arrConst;
		$objFunction 			= new Sys_Function_DocFunctions();
		$iLeaderId 				= $this->iLeaderId;
		if ($iLeaderId != '')
			$sLeaderPositionName	= Sys_Publib_Library::_getItemAttrById($_SESSION['arr_all_staff'],$iLeaderId,'position_code').' - '.Sys_Publib_Library::_getItemAttrById($_SESSION['arr_all_staff'],$iLeaderId,'name');
		else $sLeaderPositionName = '';
	?>
	<table>
		<tr>
			<td class="large_title" style="padding-left:7px;text-align:left;">
				<?=$this->bodyTitle;?>				
			</td>
		</tr>
	</table>
	<div class="box container c1">
		<div class="pad" style="padding:4px;">			
			<table align="center" cellpadding="0" cellspacing="0" width="98%" border="0" style="padding-left:0%;">
				<col width="30%" /><col width="10%" /><col width="60%" />
				<tr>
					<td><input tabindex ="7" style="width:97%;" type="text" id="txtfullTextSearch" name="txtfullTextSearch" size="40%" value="<?=$this->sFullTextSearch?>" onchange="ResetSearch();"/></td>
					<td>
						<select style="height:22px;margin-top:-3px;" tabindex ="2" id="year" name="year" onchange="ResetSearch();page_record_number_onchange(this,'')">
							<?php 
								for($i = 2000; $i <= 2020; $i++)
									echo '<option value='.$i.'>'.$i.'</option>';
							?>
						</select>
					</td>
					<td align="left"><input tabindex ="9" style="margin-top:-2px;" tabindex ="6" type="button" name="timkiem" id="timkiem" value="Tìm Kiếm" class="add_large_button"  onclick="document.getElementById('hdn_option_search').value = 1;actionUrl('../index/');"></td>
				</tr>
			</table>
		</div>
	</div>
	<div style="height:20px;"></div>
	<table cellpadding="0" cellspacing="0" border="0" width="98%" align="center" class="list_table2" id="table1">
		<?php			
		$delimitor = $this->delimitor;//Lay ky tu phan cach giua cac phan tu
		//Hien thi cac cot cua bang hien thi du lieu
		$StrHeader = explode("!~~!",$this->GenerateHeaderTable("12%". $delimitor ."15%". $delimitor . "53%" . $delimitor . "20%"
										,$arrConst['_NGAY_BAN_HANH']. $delimitor . $arrConst['_SO_KY_HIEU'] . $delimitor . $arrConst['_TRICH_YEU'] . $delimitor . $arrConst['_NOI_BAN_HANH']
										,$delimitor));
		echo $StrHeader[0];					
		echo $StrHeader[1]; //Hien thi <col width = 'xx'><...		
			//Dinh nghia URL
			$sUrlView  = "../view/";
			$v_current_style_name = "round_row";
			$arrDoc = $this->arrDoc;	
			for($index = 0;$index < sizeof($arrDoc);$index++){
				$sDocumentId 		= $arrDoc[$index]['PK_DOC'];		
				$sReleaseDate		= $objFunction->searchCharColor($this->sFullTextSearch,$arrDoc[$index]['C_RELEASE_DATE']) .'&nbsp;';								
				$sSymbol			= $objFunction->searchCharColor($this->sFullTextSearch,$arrDoc[$index]['C_SYMBOL']) .'&nbsp;';			
				$strFileName 		= $arrDoc[$index]['C_FILE_NAME'];
				$sFile 				= Sys_Library::_getAllFileAttach($strFileName,"!#~$|*","!~!",$this->baseUrl . "attach-file/");
				if($strFileName == '' || $strFileName == null){
					$sSubject		= $objFunction->searchStringColor($this->sFullTextSearch,$arrDoc[$index]['C_SUBJECT']) .'&nbsp;';	
				}else {
					$sSubject		= $objFunction->searchStringColor($this->sFullTextSearch,$arrDoc[$index]['C_SUBJECT']) .'<br>'. $sFile;
					$sFile 			= "";
				}
				$sAgentcyName	 	= $objFunction->searchStringColor($this->sFullTextSearch,$arrDoc[$index]['C_AGENTCY_NAME']) .'&nbsp;';	
				$sType			 	= $objFunction->searchStringColor($this->sFullTextSearch,$arrDoc[$index]['C_TYPE']);
				if ($v_current_style_name == "odd_row"){
					$v_current_style_name = "round_row";
				}else{
					$v_current_style_name = "odd_row";					
				}?>
				<tr class="<?=$v_current_style_name?>">	
					<td style="display:none;" align="center" style="padding-left:3px;padding-right:3px;" class="normal_label">
						<?=$this->formCheckbox('chk_item_id',$arrDoc[$index]['PK_DOC'], array('checked' => false,'onclick' =>'selectrow(this)'));?>					
					</td>
					<td ondblclick="item_onclick('<?=$sDocumentId?>','<?=$sUrlView?>')" onclick="document.getElementById('hdn_type').value = '<?=$sType?>';set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$sDocumentId?>');" align="center" valign="middle"  style="padding-left:3px;padding-right:3px;" class="normal_label"><?=$sReleaseDate;?></td>
					<td ondblclick="item_onclick('<?=$sDocumentId?>','<?=$sUrlView?>')" onclick="document.getElementById('hdn_type').value = '<?=$sType?>';set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$sDocumentId?>');" align="center" style="padding-left:3px;padding-right:3px;" class="normal_label"><?=$sSymbol?></td>	
					<td ondblclick="item_onclick('<?=$sDocumentId?>','<?=$sUrlView?>')" onclick="document.getElementById('hdn_type').value = '<?=$sType?>';set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$sDocumentId?>');" align="left" valign="middle" style="padding-left:3px;padding-right:3px;" class="normal_label"><?=$sSubject?></td>	
					<td ondblclick="item_onclick('<?=$sDocumentId?>','<?=$sUrlView?>')" onclick="document.getElementById('hdn_type').value = '<?=$sType?>';set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$sDocumentId?>');" align="left" valign="middle" style="padding-left:3px;padding-right:3px;" class="normal_label"><?=$sAgentcyName?></td>		
				</tr><?php
			}					
			//Tu dien cac dong trang trong truong hop du lieu tra ve < so row _CONST_NUMBER_OF_ROW_PER_LIST		
			if(sizeof($arrDoc) < 15){	
				echo $this->addEmptyRow($this->iCountElement,15 - sizeof($arrDoc),$v_current_style_name,4);		
			}	
		?>			
	</table>	
	<!--Hien thi trang can xem!-->
	
	<table width="100%" cellpadding="0" cellspacing="0" border="0">
		<tr>
			<td style="color:red;width:30%;padding-left:1%;" class="small_label">
				<small class="small_starmark"><?=$this->sdocpertotal;?></small>
			</td>
			<td align="center" style="width="50%">
				<table width="10%"><?php
					//Hien thi danh sach so trang
					echo $this->generateStringNumberPage;?>
				</table>
			</td>
			<td width="30%" align="right" style="font-size:13px; padding-right:1%; font:tahoma" class="normal_label"><?php
				//Hien thi so trang
				echo $this->generateHtmlSelectBoxPage;?>
			</td>
		</tr>
	</table>
	<table width='100%'  border='0' cellspacing='0' cellpadding='0' align="center">
		<tr>
			<td style="padding-top: 10px; padding-bottom: 10px;" align="center" valign="middle">
				<?php 
					$iLeaderId	 = $objFunction->convertStaffNameToStaffId($sLeaderPositionName);
					$iUnitId 	 = $objFunction->convertUnitNameListToUnitIdList($this->iUnitId);
				?>
				<!-- 
				<input type="button" class="add_large_button" value="&nbsp;&nbsp;&nbsp;<?=$arrConst['_IN']?>&nbsp;&nbsp;&nbsp;" onclick="btn_print_doclist_onclick('../print/')">
				 -->
			</td>	
		</tr>
	</table>
</div>
</form>
<?php echo $this->search_textselectbox_doc_type;?>
<?php echo $this->search_textselectbox_doc_cate;?>
<?php echo $this->search_textselectbox_leader;?>
<?php
	if($_SESSION['arrStaffPermission']['THEO_DOI_KQXL_VBDEN'] == 1)
		echo $this->search_textselectbox_unit;
?>
<script type="text/javascript">
$(document).ready(function() {
	var year = '<?=$this->iYear?>';
	if(year != '')
		document.getElementById('year').value = '<?=$this->iYear?>';
	else
		document.getElementById('year').value = '<?=date("Y")?>';
});

shortcut.add("Ctrl+K",function() {
	document.getElementById('txtfullTextSearch').focus();
	document.getElementById('txtfullTextSearch').select();
});
function ResetSearch(){
	document.getElementById('hdn_current_page').value = "1";
}
function checkvalue(){
	document.getElementById('timkiem').focus();
	document.getElementById('hdn_option_search').value = 1;
	actionUrl('../index/')
}
function btn_print_doclist_onclick(p_url){
	p_url = p_url + '?txtfullTextSearch=' + '<?=$this->sFullTextSearch?>' + '&hdn_year=' + '<?=$this->iYear?>';
	sRtn = showModalDialog(p_url,"","dialogWidth=1px;dialogHeight=1px;status=no;scroll=no;dialogCenter=yes");			
    if (sRtn!=""){
		window.open(sRtn);
    }
}
</script>
