<form action="index" method="POST" id="frmReceived">
<div>
	<table width='100%'  border='0' cellspacing='0' cellpadding='0' class="table_title">
		<tr>
			<td class="large_title" style="padding-left:7px;text-align:left;">
				<!--Cac doi tuong hidden tren form-->
				<?php echo $this->formHidden("hdn_object_id_list","",null); ?>
				<?php echo $this->formHidden("hdn_filter_xml_tag_list",$this->filterXmlTagList,null); ?>
				<?php echo $this->formHidden("hdn_filter_xml_value_list",$this->filterXmlValueList,null); ?>
				<?php echo $this->formHidden("hdn_object_id","",null); ?>
				<?php echo $this->formHidden("hdn_move_order","",null); ?>
				<?php echo $this->formHidden("hdn_move","",null); ?>
				<?php echo $this->formHidden("hdn_XmlTagValueList",$this->XmlTagValueList,null); ?>
				<?php echo $this->formHidden("hdn_history_back",$this->sUrl,null); ?>
				
				<?php echo $this->formHidden("hdn_status","",null); ?>
				<?php echo $this->formHidden("hdn_current_page",$this->iCurrentPage,null); ?>
				<?php echo $this->formHidden("hdn_record_number_page",$this->iNumRowOnPage,null); ?>
				
				<?php echo $this->formHidden("hdn_filter_xml_value_list",$this->filterXmlValueList,null); ?>
				
				<?=$this->bodyTitle;?>	
				
			</td>
		</tr>
	</table>
	<?php
		$arrConst = $this->arrConst;
		//var_dump($this->arrMenu);
	?>
	<div class="box container c1">
		<div class="pad">			
			<table cellpadding="0" cellspacing="0" width="98%" border="0">
				<col width="15%"/><col width="35%"/><col width="40%"/><col width="10%"/>
				<tr>
					<td class="normal_label" align="left">
						&nbsp;<?=$arrConst['_CHUYEN_MUC'] ?>
					</td>
					<td>
						<select style="width:90%;" id="C_MENU" name="C_MENU" onchange="actionUrl('');" class="textbox normal_label" >
						<option id="" name = "" value="">-- Chọn chuyên mục --</option>
						<?php
							echo Sys_Library::_generateSelectOption($this->arrMenu,'PK_WEB_MENU','PK_WEB_MENU','C_NAME',$this->sMenuID);?>
						</select>
					</td>
					<td>
						<input class="textbox c1" id="FullTextSearch" name="FullTextSearch" value="<?=$this->FullTextSearch?>" class="textbox c2">
					</td>
					<td>
						<input type="button" value="<?=$arrConst['_TIM_KIEM'] ?>" class="add_large_button" size="100%" onclick="actionUrl('');">
					</td>
				</tr>
			</table>
		</div>
	</div>
	<table cellpadding="0" cellspacing="0" border="0" width="98%" align="center" class="list_table2" id="table1">
		<?php			
		$delimitor = $this->delimitor;//Lay ky tu phan cach giua cac phan tu
		//Hien thi cac cot cua bang hien thi du lieu
		$StrHeader = explode("!~~!",$this->GenerateHeaderTable("5%" . $delimitor . "55%" . $delimitor . "20%". $delimitor . "20%" 
										,'<input type="checkbox" name="chk_all_item_id" value="" onclick="checkbox_all_item_id(document.forms[0].chk_item_id);">' . $delimitor .$arrConst['_TIEU_DE'] . $delimitor . 'Ngày tạo' . $delimitor . 'Người tạo'
										,$delimitor));
		echo $StrHeader[0];						
		echo $StrHeader[1]; //Hien thi <col width = 'xx'><...		
			//Dinh nghia URL
			$arrResul = $this->arrResul;
			//var_dump($arrResul);
			$objFunction =	new	Sys_Function_DocFunctions()	;
			$v_current_style_name = "round_row";
			$iCount = sizeof($arrResul) - 1;
			//echo $sDocumentIdEnd;
			for($index = 0;$index <= $iCount;$index++){
				$sDocumentId 				= $arrResul[$index]['PK_ARTICLE'];
				$sTitle						= $objFunction->searchCharColor($this->FullTextSearch,$arrResul[$index]['C_TITLE']);
				$sCreateID 					= $objFunction->searchCharColor($this->FullTextSearch,$arrResul[$index]['FK_CREATE_STAFF']);
				$sCreateName				= $objFunction->searchCharColor($this->FullTextSearch,$objFunction->getNamePositionStaffByIdList($sCreateID));
				$sDate						= $arrResul[$index]['C_CREATE_DATE'];
				if ($v_current_style_name == "odd_row"){
					$v_current_style_name = "round_row";
				}else{
					$v_current_style_name = "odd_row";					
				}
				?>
				<tr class="<?=$v_current_style_name?>">	
					<td align="center" style="padding-left:3px;padding-right:3px;" class="normal_label">
						<?=$this->formCheckbox('chk_item_id',$sDocumentId.'|!~!|'.$sTitle, array('checked' => false,'onclick' =>'selectrow(this)'));?>					
					</td>													
					<td ondblclick="" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$sDocumentId?>');" align="left"  style="padding-left:3px;padding-right:3px;" class="normal_label"><?=$sTitle.'&nbsp;';?></td>
					<td ondblclick="" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$sDocumentId?>');" align="center" style="padding-left:3px;padding-right:3px;" class="normal_label"><?=$sDate.'&nbsp;';?></td>		
					<td ondblclick="" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$sDocumentId?>');" align="left" style="padding-left:3px;padding-right:3px;" class="normal_label"><?=$sCreateName.'&nbsp;';?></td>
				</tr><?php
			}		
			//Tu dien cac dong trang trong truong hop du lieu tra ve < so row _CONST_NUMBER_OF_ROW_PER_LIST		
			if(sizeof($arrResul) < 15){	
				echo $this->addEmptyRow($this->iCountElement,15 - sizeof($arrResul),$v_current_style_name,4);		
			}				
		?>			
	</table>	
	<!--Hien thi trang can xem!-->	
	<table width="100%" cellpadding="0" cellspacing="5" border="0">
		<tr>
			<td width="30%" style="color:red;padding-left:1%;" class="normal_label">
				<?=$this->sdocpertotal;?>
			</td>
			<td align="center" style="width="50%">
				<table width="10%"><?php
					//Hien thi danh sach so trang
					echo $this->generateStringNumberPage;?>
				</table>
			</td>
			<td width="30%" align="right" style="font-size:13px; padding-right:1%; font:tahoma" class="normal_label"><?php
				//Hien thi so trang
				echo $this->generateHtmlSelectBoxPage;?>
			</td>
		</tr>
	</table>
	<table width='100%'  border='0' cellspacing='0' cellpadding='0' align="center">
		<tr>
			<td style="padding-top: 10px; padding-bottom: 10px;" align="center" valign="middle">				
				<input type="button" class="add_large_button" value="Chọn" onclick="btn_select_article_onclick(document.getElementsByName('chk_item_id'));">
				<input type="button" class="add_large_button" value="Quay lại" onclick="window.close();">
			</td>	
		</tr>
	</table>
</div>
</form>
<script type="text/javascript">
</script>