<script src="/Sys-doc-boxd/public/Sys-js/jquery-1.4.2.min.js" type="text/javascript"></script>
<form action="index" method="POST" id="frmsheduleStaff" autocomplete="off">
	<?php echo $this->formHidden("hdn_type","",null); ?>
	<!--Cac doi tuong hidden tren form-->	
	<?php echo $this->formHidden("hdn_object_id_list","",null); ?>	
	<?php echo $this->formHidden("hdn_object_id",$this->scheduleID,null); ?>
	<?php echo $this->formHidden("hdn_doc_id",$this->pDocId,null); ?>		
	<?php echo $this->formHidden("htn_leftModule",$this->currentModulCodeForLeft,null); ?>		
	<?php echo $this->formHidden("htn_schedule_update",$this->currentUpdate,null); ?>		
	<?php echo $this->formHidden("hdn_week",$this->$v_week); ?>
	<?php echo $this->formHidden("hdn_week_text",$this->$v_week_text); ?>
	<?php echo $this->formHidden("hdn_year",$this->$v_year); ?>
	<?php echo $this->formHidden("hdn_exporttype","1"); ?>		
	<?php
		$arrCount = $this->arrCount;
		$arryWekk = $this->arryWekk;
		$arryYear = $this->arryYear;	
		$arrDateInWeek = $this->arrDateInWeek;
		$arry_date_in_week = explode('!@#',$arrDateInWeek);				
		$arrySchedule_Staff = $this->arrySchedule_Staff;				
		//LAY GIA TRI CUA NGAY	
		$v_mon = explode('!~~!',$arrySchedule_Staff[0]['C_MON']); // THU 2
		$v_tue = explode('!~~!',$arrySchedule_Staff[0]['C_TUE']); // THU 3
		$v_wed = explode('!~~!',$arrySchedule_Staff[0]['C_WED']); // THU 4
		$v_thu = explode('!~~!',$arrySchedule_Staff[0]['C_THU']); // THU 5
		$v_fri = explode('!~~!',$arrySchedule_Staff[0]['C_FRI']); // THU 6
		$v_sat = explode('!~~!',$arrySchedule_Staff[0]['C_SAT']); // THU 7
		$v_sun = explode('!~~!',$arrySchedule_Staff[0]['C_SUN']); // CN
		$p_year = date('Y');		
	?>
	<table>
		<tr>
			<td class="large_title" style="padding-left:7px;text-align:left;">
				<?=$this->bodyTitle;?>				
			</td>
		</tr>
	</table>
	<!--Phan hien thi Tuan trong nam va Nam -->
	<div class="box container c1">
		<div class="pad">			
			<table cellpadding="0" cellspacing="0" width="100%" border="0" style="padding-left:0%;">				
				<tr>
					<td width="4%" class="normal_label" valign="middle"><?=$arrCount['_TUAN']?>	</td>
					<td  valign="top" width="20%" valign="top">
						
					<select name="cbo_week" id="cbo_week" style="width:auto;" class="textbox"  onchange="document.getElementById('hdn_week').value = this.value; document.forms['frmsheduleStaff'].submit();" >					
						<? echo $arryWekk; ?>				
					</select>
			 </td>
			<td width="3%" class="normal_label" valign="middle"><?=$arrCount['_NAM']?></td>
						<td  style="padding-left:10px;">
							<select name="cbo_year" id="cbo_year" class="textbox" valign="top" style="width:auto;" onchange="document.getElementById('hdn_year').value = this.value;  document.forms['frmsheduleStaff'].submit();" >
								<? echo $arryYear;?>
							</select>											
					</td>
				</tr>
			</table>
		</div>
	</div>	
	<!--Phan hien thi Link cap nhat -->	
	<table width='99%'  border='0' cellspacing='0' cellpadding='0' class="table_title" height="23px">
		<col width="85%" align="left"/><col width="15%" align="right"/>
		<tr>
			<td align="right" colspan="2">				
			</td>
		</tr>
	</table>
	<!--Phan hien thi Noi dung cap nhat lich -->			
	<table class="schedule_staff" cellpadding="0" cellspacing="0" width="98%" id="table1">		
		  <tr>
		    <th colspan="2" scope="col">Thời gian</th>
		    <th width="839" scope="col">Nội dung công việc</th>
		  </tr>
		  <tr>
		    <td width="70" rowspan="2"><? echo $arry_date_in_week[0];?></td>
		    <td width="75">Sáng</td>
		    <td><textarea  optional="true" rows="3" name="C_MON_AM" id="C_MON_AM"><? echo $v_mon[0]; ?></textarea></td>
		  </tr>
		  <tr>
		    <td>Chiều</td>
		     <td><textarea  optional="true" rows="3" name="C_MON_PM" id="C_MON_PM"><? echo $v_mon[1]; ?></textarea></td>
		  </tr>
		  <tr class="newBackgroud">
		    <td rowspan="2"><? echo $arry_date_in_week[1];?></td>
		    <td width="75">Sáng</td>
		    <td class="newBackgroud"><textarea class="newBackgroud" optional="true" rows="3" name="C_TUE_AM" id="C_TUE_AM"><? echo $v_tue[0];?></textarea></td>
		  </tr>
		  <tr class="newBackgroud">
		    <td>Chiều</td>
		    <td><textarea class="newBackgroud" optional="true" rows="3" name="C_TUE_PM" id="C_TUE_PM"><? echo $v_tue[1];?></textarea></td>
		  </tr>
		  <tr>
		    <td rowspan="2"><? echo $arry_date_in_week[2];?></td>
		    <td width="75">Sáng</td>
		    <td><textarea  optional="true" rows="3" name="C_WED_AM" id="C_WED_AM"><? echo $v_wed[0];?></textarea></td>
		  </tr>
		  <tr>
		   <td>Chiều</td>
		    <td><textarea  optional="true" rows="3" name="C_WED_PM" id="C_WED_PM"><? echo $v_wed[1];?></textarea></td>
		  </tr>
		  <tr class="newBackgroud">
		    <td rowspan="2"><? echo $arry_date_in_week[3];?></td>
		    <td width="75">Sáng</td>
		    <td><textarea  class="newBackgroud" optional="true" rows="3" name="C_THU_AM" id="C_THU_AM"><? echo $v_thu[0];?></textarea></td>
		  </tr>
		  <tr class="newBackgroud">
		   <td>Chiều</td>
		    <td><textarea class="newBackgroud" optional="true" rows="3" name="C_THU_PM" id="C_THU_PM"><? echo $v_thu[1];?></textarea></td>
		  </tr>
		  <tr>
		    <td rowspan="2"><? echo $arry_date_in_week[4];?></td>
		   <td width="75">Sáng</td>
		    <td><textarea  optional="true" rows="3" name="C_FRI_AM" id="C_FRI_AM"><? echo $v_fri[0];?></textarea></td>
		  </tr>
		  <tr>
		    <td>Chiều</td>
		    <td><textarea  optional="true" rows="3" name="C_FRI_PM" id="C_FRI_PM"><? echo $v_fri[1];?></textarea></td>
		  </tr>
		  <tr class="newBackgroud">
		    <td rowspan="2"><? echo $arry_date_in_week[5];?></td>
		   <td width="75">Sáng</td>
		    <td><textarea class="newBackgroud"  optional="true" rows="3" name="C_SAT_AM" id="C_SAT_AM"><? echo $v_sat[0];?></textarea></td>
		  </tr>
		  <tr class="newBackgroud">
		   <td>Chiều</td>
		    <td><textarea class="newBackgroud"  optional="true" rows="3" name="C_SAT_PM" id="C_SAT_PM"><? echo $v_sat[1];?></textarea></td>
		  </tr>
		  <tr>
		    <td rowspan="2"><? echo $arry_date_in_week[6];?></td>
		    <td width="75">Sáng</td>
		    <td><textarea  optional="true" rows="3" name="C_SUN_AM" id="C_SUN_AM"><? echo $v_sun[0];?></textarea></td>
		  </tr>
		  <tr>
		    <td>Chiều</td>
		    <td><textarea  optional="true" rows="3" name="C_SUN_PM" id="C_SUN_PM"><? echo $v_sun[1];?></textarea></td>
		  </tr>	
	</table>	
	<table width='100%'  border='0' cellspacing='0' cellpadding='0' align="center">		
		<tr>
			<td style="padding-top: 10px; padding-bottom: 10px;" align="center" valign="middle">				
				<input id="btn_schedule_staff" name="btn_schedule_staff" type="button" class="add_large_button" value="<?=$arrCount['_CAP_NHAT']?>" onclick="document.getElementById('htn_schedule_update').value='SCHEDULE_STAFF_UPDATE'; document.getElementsByName(document.forms['frmsheduleStaff'].submit(), '../index/');">
				<input type="button" class="add_large_button" value="<?=$arrCount['_IN_DANG_WEB']?>" onclick=" btn_print_schedule_onclick('../printtodoc/',document.getElementById('hdn_week').value,document.getElementById('hdn_year').value,document.getElementById('cbo_week').options[document.getElementById('cbo_week').selectedIndex].text,'LICH_CA_NHAN','1');">
				<input type="button" class="add_large_button" value="<?=$arrCount['_IN_DANG_WORD']?>" onclick=" btn_print_schedule_onclick('../printtodoc/',document.getElementById('hdn_week').value,document.getElementById('hdn_year').value,document.getElementById('cbo_week').options[document.getElementById('cbo_week').selectedIndex].text,'LICH_CA_NHAN','2');">				
			</td>	
		</tr>
	</table>
</div>
</form>
<script type="text/javascript">
shortcut.add("Ctrl+K",function() {
	document.getElementById('txtfullTextSearch').focus();
	document.getElementById('txtfullTextSearch').select();
});
function ResetSearch(){
	document.getElementById('hdn_current_page').value = "1";	
}
function checkvalue(){
	if(document.getElementById('txtfullTextSearch').value != ""){
		actionUrl('');
	}
}
//document.getElementById('hdn_week_text').value = document.getElementById('cbo_week').options[document.getElementById('cbo_week').selectedIndex].text;
document.getElementById('hdn_week').value = document.getElementById('cbo_week').value ;
document.getElementById('hdn_year').value = document.getElementById('cbo_year').value; 
document.getElementById('hdn_object_id').value ='<? echo $arrySchedule_Staff[0]['PK_SCHEDULE_STAFF']; ?>' 

</script>
