<form action="index" method="POST" id="frmAddSent" enctype="multipart/form-data" autocomplete="off">
	<table cellpadding="0" cellspacing="0" width="100%" border="0">
		<!--tao tac hidden!-->
		<tr>
			<td>
				<?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null); ?>
				<?php echo $this->formHidden("hdn_deleted_new_file_id_list","",null); ?>
				<?php echo $this->formHidden("hdnCode","",null); ?>
				<?php echo $this->formHidden("hdn_xml_tag_list","",null); ?>
				<?php echo $this->formHidden("hdn_xml_value_list","",null); ?>
				<?php echo $this->formHidden("hdn_XmlTagValueList","",null); ?>
				<?php echo $this->formHidden("hdh_option",$this->option,null); ?>
				<!--Bien hdn_deleted_new_file_id_list dung de luu Id cua nhung doi tuong file dinh kem se xoa-->	
				<?php echo $this->formHidden("hdn_deleted_new_file_id_list","",null); ?>	
				<!--Bien hdn_deleted_exist_file_id_list dung de ...-->	
				<?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null); ?>	
				<?php echo $this->formHidden("hdnListId","",null); ?>	
				<?php echo $this->formHidden("number",'',null); ?>
				<?php echo $this->formHidden("hdnNhomChinh","",null); ?>				
				<?php echo $this->formHidden("hdn_received_place","",null); ?>
				<?php echo $this->formHidden("hdn_signer_position_name","",null); ?>
				<?php echo $this->formHidden("hdn_doc_cate_name","",null); ?>
				<?php echo $this->formHidden("hdn_doc_type_name","",null); ?>
				<?php echo $this->formHidden("hdn_function_modul",$this->getModulLeft,null);?>
			</td>
		</tr>
	</table>
	<?php 
		$arrSent = $this->arrSent;
		$arrSigner = $this->arrSigner;
		//var_dump($arrSent);
		$urlCalendar = $this->urlCalendar;
		$arrConst = $this->arrConst;
	?>
	<!--HIen thi tieu de man hinh danh sach!-->
	<div id ="content">
		<div id="header_conten" style="height: 35px;padding-bottom:15px;">
			<h1 class="large_label"><?=$this->bodyTitle;?></h1>
			<div style="text-align:right;">
				<a class="small_link" onClick="document.getElementById('hdh_option').value='GHI_THEMMOI';btn_save_period(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'');"><?=$arrConst['_GHI_THEM_MOI'] ?>&nbsp;</a> 
				<a class="small_link" onClick="document.getElementById('hdh_option').value='GHI_THEMTIEP';btn_save_period(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'');">&nbsp;<?=$arrConst['_GHI_THEM_TIEP'] ?>&nbsp;</a> 
				<a class="small_link" onClick="document.getElementById('hdh_option').value='GHI_QUAYLAI';btn_save_period(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'');">&nbsp;<?=$arrConst['_GHI_QUAY_LAI'] ?>&nbsp;</a> 
				<a class="small_link" onClick="document.getElementById('hdh_option').value='GHI_TAM';btn_save_period(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'');">&nbsp;<?=$arrConst['_GHI_TAM'] ?>&nbsp; </a> 
				<a class="small_link" onClick="document.getElementById('hdh_option').value='DANGKY_PHATHANH';btn_save_period(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'');"><?=$arrConst['_DANG_KY_PHAT_HANH'] ?>&nbsp;</a> 
				<a class="small_link" onclick="actionUrl('../../index/modul/<?=$this->getModulLeft ?>');">&nbsp;<?=$arrConst['_QUAY_LAI'] ?>&nbsp;</a>
			</div>
		</div>
		<div id="body_conten1">
				<div id ="body_conten1_left">
					<div>
						<label>1.&nbsp;<?=$arrConst['_LOAI_VAN_BAN'] ?><span class="requiein">*</span></label>
						<input style="width:65%" id ="C_DOC_TYPE" name="C_DOC_TYPE" type="text"  option = "false"  xml_tag_in_db="" xml_data="false" value="<?= $arrSent[0]['C_DOC_TYPE']?>" column_name="C_DOC_TYPE" message="<?php echo "Phai xac dinh LOAI van ban!";?>" onKeyDown="change_focus(document.forms[0],this)">			
					</div>
					<div>
						<label>2. &nbsp;<?=$arrConst['_NGAY_DANG_KY'] ?><span class="requiein">*</span></label>
						<input style="width:20%;" class="textbox c2" id ="C_SENT_DATE" name="C_SENT_DATE" value="" type="text" isdate="true" option = "false"  xml_tag_in_db="" xml_data="false" column_name="C_SENT_DATE" onkeyup = "DateOnkeyup('C_SENT_DATE',this,event)" message="<?php echo "NGAY DANG KY khong dung dinh dang ngay/thang/nam!";?>" onKeyDown="change_focus(document.forms[0],this)">	 						
					</div>
					<div>
						<label>3. &nbsp;<?=$arrConst['_TRICH_YEU'] ?><span class="requiein">*</span></label>
						<textarea style="width:65%"  class="normal_textarea" id="C_SUBJECT"  option = "true" rows="2" name="C_SUBJECT"  xml_tag_in_db="" xml_data="false" column_name="C_SUBJECT" message="<?php echo "Phai nhap vao TRICH YEU van ban!";?>"><?= $arrSent[0]['C_SUBJECT']?></textarea>
					</div>
					<div>
						<label>4. &nbsp;<?=$arrConst['_LINH_VUC'] ?><span class="requiein">*</span></label>
						<input style="width:65%" id ="C_DOC_CATE" name="C_DOC_CATE" type="text"  option = "false"  xml_tag_in_db="" xml_data="false" value="<?= $arrSent[0]['C_DOC_CATE'] ?>" column_name="C_DOC_CATE" message="<?php echo "Phai xac dinh LINH VUC van ban!";?>" onKeyDown="change_focus(document.forms[0],this)">
					</div>
				</div><!-- End #body_conten1_left-->
				<div id="body_conten1_right">
					<div>
						<label>5. &nbsp;<?=$arrConst['_TINH_CHAT'] ?></label>
						<select id="C_NATURE" name="C_NATURE"  optional = "true"  style="width:59%;" class="textbox normal_label" xml_tag_in_db="" xml_data="false" column_name="C_NATURE" message="<?php echo "Ban phai chon TINH CHAT VB!";?>">
								<option id="" name = "" value="">-- chọn &nbsp;<?=$arrConst['_TINH_CHAT'] ?> --</option><?php
								$arrNature = $this->arrNature;
								echo Sys_Library::_generateSelectOption($arrNature,'C_CODE','C_CODE','C_NAME',$arrSent[0]['C_NATURE']);?>
						</select>
					</div>
					<div>
						<label >6. &nbsp;<?=$arrConst['_DO_KHAN'] ?></label>
						<select id="C_TEXT_OF_EMERGENCY" name="C_TEXT_OF_EMERGENCY"  optional = "true"  style="width:59%;" class="textbox normal_label" xml_tag_in_db="" xml_data="false" column_name="C_TEXT_OF_EMERGENCY" message="">
								<option id="" name = "" value="">-- chọn &nbsp;<?=$arrConst['_DO_KHAN'] ?> --</option><?php
								$arrTextOfEmergency = $this->arrTextOfEmergency;
								echo Sys_Library::_generateSelectOption($arrTextOfEmergency,'C_NAME','C_NAME','C_NAME',$arrSent[0]['C_TEXT_OF_EMERGENCY']);?>
						</select>	
					</div>
					<div>
						<label>7. &nbsp;<?=$arrConst['_SO_BAN'] ?></label>
						<input style="width:20%;" id ="so_ban" name="so_ban" type="text"  isnumeric = "false" optional = "false"  xml_tag_in_db="so_ban"  xml_data="true" column_name=""  onKeyDown="change_focus(document.forms[0],this)" value="<?=$arrSent[0]['SO_BAN'] ?>">				
						<label style="float:none;clear:none; display:inline;"><?=$arrConst['_SO_TRANG'] ?></label>
						<input style="width:21%;" id ="so_trang" name="so_trang" type="text"  optional = "false"   xml_tag_in_db="so_trang"  xml_data="true" column_name="" onKeyDown="change_focus(document.forms[0],this)" value="<?=$arrSent[0]['SO_TRANG'] ?>">
					</div>
					<div>
						<label>8. &nbsp;<?=$arrConst['_FILE_DINH_KEM'] ?></label>
						<?=$this->AttachFile;?>
					</div>			
				</div>
				<div id="clear"></div>
		</div>
		<div id="body_conten4"> 
			<div style="float:left; width:50%">
					<label style="width:160px;">9.&nbsp;<?=$arrConst['_PHONG_BAN_SOAN_THAO'] ?><span class="requiein">*</span></label>
					<select id="FK_UNIT_SOANTHAO" name="FK_UNIT_SOANTHAO" disabled onchange="getAllStaff(document.getElementById('objView'),this,<?=$_SESSION["arr_all_staff"] ?>);" option = "true" style="width:200px;" class="textbox normal_label" xml_tag_in_db="" xml_data="false" column_name="FK_UNIT_SOANTHAO" message = "Ban phai chon DON VI SOAN THAO van ban!">
						<option id="" name = "" value="">-- chọn phòng ban --</option><?php
						$arrUnit = $_SESSION['arr_all_unit'];//$this->arrAllDonVi;
						echo Sys_Library::_generateSelectOption($arrUnit,'id','id','name',$this->iDepartmentId);?>
					</select>	
			</div>
			<div style="float:left; width:50%">
				<label style="width:150px;">10.&nbsp;<?=$arrConst['_CAN_BO_SOAN_THAO'] ?> <span class="requiein">*</span></label>
				<div id="objView">
					<select id="FK_STAFF" name="FK_STAFF" disabled option = "true" style="width:200px;" class="textbox normal_label" xml_tag_in_db="" xml_data="false" column_name="FK_STAFF" message = "Ban phai chon CHUYEN VIEN SOAN THAO van ban!">
						<option id="" name = "" value="">-- chọn chuyên viên--</option><?php
						$arrDraff = array();
						$k = 0;
						foreach ($_SESSION['arr_all_staff'] as $staff){
							if($staff['unit_id'] == $this->iDepartmentId){
								$arrDraff[$k]['C_CODE'] = $staff['id'];
								$arrDraff[$k]['C_NAME'] = $staff['position_code'] . " - ".$staff['name'];
								$k ++;
							}
						}
						echo Sys_Library::_generateSelectOption($arrDraff,'C_CODE','C_CODE','C_NAME',$this->iUserId);?>
					</select>	
				</div>
			</div>
			<div style="float:left; width:50%">
				<label style="width:160px;">11.&nbsp;<?=$arrConst['_NGUOI_KY'] ?> <span class="requiein">*</span></label>
				<div id="objApproval">
					<select id="FK_SIGNER" name="FK_SIGNER" option = "true" style="width:200px;" class="textbox normal_label" xml_tag_in_db="" xml_data="false" column_name="FK_SIGNER" message = "Ban phai chon CHUYEN VIEN SOAN THAO van ban!">
						<option id="" name = "" value="">-- Chọn người ký--</option><?php
						echo Sys_Library::_generateSelectOption($arrSigner,'C_CODE','C_CODE','C_NAME',$arrSent[0]['FK_SIGNER']);?>
					</select>	
				</div>
			</div>
			<div>
				<label style="width:160px;">12. &nbsp;<?=$arrConst['_NOI_NHAN'] ?></label>
				<textarea style="width:77%" id="C_RECEIVE_PLACE" name="C_RECEIVE_PLACE" optional="true"  autocomplete="on" class="textbox normal_textarea" ><?= $arrSent[0]['C_RECEIVE_PLACE'] ?></textarea>
			</div>
			<br clear="all">
		</div>
	</div>	
	<!--Hien thi nut!-->			
	<table 	width='99%'  border='0' cellspacing='0' cellpadding='0' align="center" class="table_title">
		<tr><td style="height:20px;"><hr width='100%' color='#3399FF' size='1'></td></tr>			
		<tr>
			<td align="center" style="padding-bottom:10px;">	
				<button name="btn_ghivathemmoi" id="btn_ghivathemmoi" type="button" value="<?=$arrConst['_GHI_THEM_MOI'] ?>" class="add_large_button" onClick="document.getElementById('hdh_option').value='GHI_THEMMOI';btn_save_period(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'');"><?=$arrConst['_GHI_THEM_MOI'] ?></button>
				<button name="btn_ghivathemtiep" id="btn_ghivathemtiep" type="button" value="<?=$arrConst['_GHI_THEM_TIEP'] ?>" class="add_large_button" onClick="document.getElementById('hdh_option').value='GHI_THEMTIEP';btn_save_period(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'');"><?=$arrConst['_GHI_THEM_TIEP'] ?></button>
				<button name="btn_ghivaquaylai" id="btn_ghivaquaylai" type="button" value="<?=$arrConst['_GHI_QUAY_LAI'] ?>" class="add_large_button" onClick="document.getElementById('hdh_option').value='GHI_QUAYLAI';btn_save_period(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'');"><?=$arrConst['_GHI_QUAY_LAI'] ?></button>
				<button name="btn_ghinhan" id="btn_ghinhan" type="button" value="<?=$arrConst['_GHI_TAM'] ?>" class="add_large_button" onClick="document.getElementById('hdh_option').value='GHI_TAM';btn_save_period(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'');"><?=$arrConst['_GHI_TAM'] ?></button>
				<button name="btn_dkph" id="btn_dkph" type="button" value="<?=$arrConst['_DANG_KY_PHAT_HANH'] ?>" class="add_large_button" onClick="document.getElementById('hdh_option').value='DANGKY_PHATHANH';btn_save_period(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'');"><?=$arrConst['_DANG_KY_PHAT_HANH'] ?></button>			
				<?=$this->formsubmit('button','Quay lại',array("onClick"=>"actionUrl('../../index/modul/".$this->getModulLeft."');","class"=>"add_large_button"))?>
			</td>
		</tr>			
	</table>
	<div id="getSysbolforNowYear" style="display:none;"></div>
</div>		
</form>
<?php 
	// echo $this->search_textselectbox_signer;  
	 echo $this->search_doc_cate_name; 
	 echo $this->search_doc_type_name; 
	 
?>
<script type="text/javascript">
	//bat phim tat
	shortcut.add("Ctrl+M",function() {
		document.getElementById('hdh_option').value='GHI_THEMMOI';
		btn_save_period(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'');
	});
	
	shortcut.add("Ctrl+E",function() {
		document.getElementById('hdh_option').value='GHI_THEMTIEP';
		btn_save_period(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'');
	});
	shortcut.add("Ctrl+Q",function() {
		document.getElementById('hdh_option').value='GHI_QUAYLAI';
		btn_save_period(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'');
	});
	
	shortcut.add("Ctrl+G",function() {
		document.getElementById('hdh_option').value='GHI_TAM';
		btn_save_period(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'');
	});


	//lay ngay/thang/nam hien tai cua he thong
	document.getElementById('C_SENT_DATE').value = '<?=date("d/m/Y");?>';
	var key='date=' + document.getElementById('C_SENT_DATE').value + '&sysbol=';
	postAJAXHTTPText('<?=$this->UrlAjax;?>' + '/sent/generatehtml/documents/getSysbol.php', key, document.getElementById('getSysbolforNowYear'), null);
	//ham lay ra cac lanh dao theo nhom
	function getLeader(rdoLeader, objView){	
		document.getElementById('nhom_LD').value = rdoLeader.value;
		var key = "groupLeader=" + rdoLeader.value;
		postAJAXHTTPText('<?=$this->UrlAjax;?>' + '/sent/generatehtml/documents/getLeader.php', key, objView, null);
	}	
	if(document.getElementById('C_NATURE').value == ''){
		document.getElementById('C_NATURE').value = 'THUONG';
	}
	//ham lay ra danh sach nhan vien trong mot don vi hien thoi cua selectbox don vi
	function getAllStaff(objView, unitID){
		var strAllStaffUnitID = '';
		var strAllStaffID = '';
		var strAllStaffName = '';<?php
		$strAllDepartment = '';
		$strParentUnitID = '';
		for($j =0; $j < sizeof($_SESSION['arr_all_unit']); $j ++){
			$strAllDepartment .= $_SESSION['arr_all_unit'][$j]['id'] . '@~@';
			$strParentUnitID .= $_SESSION['arr_all_unit'][$j]['parent_id'] . '@~@';
		}
		$strAllStaffID = "";
		$strAllStaffName = "";
		for($i =0; $i <sizeof($_SESSION['arr_all_staff']); $i ++){
			$strAllStaffID .= $_SESSION['arr_all_staff'][$i]['id'] . '@~@';
			$strAllStaffUnitID .= $_SESSION['arr_all_staff'][$i]['unit_id'] . '@~@';
			$strAllStaffName .= $_SESSION['arr_all_staff'][$i]['position_name'] . ' - ' . $_SESSION['arr_all_staff'][$i]['name'] . '@~@';
		}?>
		var key = 'unitID=' + unitID.value + '&arr_all_unit=' + '<?=$strAllDepartment?>' + '!@@!' + '<?=$strParentUnitID?>';
		key += '&arr_all_staff=' + '<?=$strAllStaffID?>' + '!@@!' + '<?=$strAllStaffUnitID?>' + '!@@!' + '<?=$strAllStaffName?>';
		postAJAXHTTPText('<?=$this->UrlAjax;?>' + '/sent/generatehtml/documents/getStaff.php', key, objView, null);	
	}	
	
	//ham lay nhom ky duyet
	function getAllApproval(objView,positionGroupCode,unitID){
		
		var strAllStaffUnitID = '';
		var strAllStaffID = '';
		var strAllStaffName = '';<?php
		$strAllStaffID = "";
		$strAllStaffName = "";
		$strAllStaffUnitID = "";
		$strAllPositionCode = "";
		for($i =0; $i <sizeof($_SESSION['arr_all_staff']); $i ++){
			$strAllStaffID  .= $_SESSION['arr_all_staff'][$i]['id'] . '@~@';
			$strAllStaffName    .= $_SESSION['arr_all_staff'][$i]['name'] . '@~@';
			$strAllStaffUnitID  .= $_SESSION['arr_all_staff'][$i]['unit_id'] . '@~@';
			$strAllPositionCode .= $_SESSION['arr_all_staff'][$i]['position_group_code'] . '@~@';
			$strAllCode .= $_SESSION['arr_all_staff'][$i]['position_code'] . '@~@';
		}?>
		var key = 'unitID=' + unitID + '&positionGroupCode=' + positionGroupCode.value ;
		key += '&arr_all_staff=' + '<?=$strAllStaffID?>' + '!@@!' + '<?=$strAllStaffName?>' + '!@@!' + '<?=$strAllStaffUnitID?>' + '!@@!' + '<?=$strAllPositionCode?>' + '!@@!' + '<?=$strAllCode?>';
		postAJAXHTTPText('<?=$this->UrlAjax;?>' + '/sent/generatehtml/registration/getSigner.php', key, objView, null);	
	}		
</script>
<script type = "text/javascript">
$(function() {
	$( "#C_SENT_DATE" ).datepicker({
		changeMonth: true,
		gotoCurrent: true,
		maxDate: '+1m +1w',
		minDate: new Date(1945, 1 - 1, 1),
		changeYear: true
	});
});
</script>