<form action="index" method="POST" id="frmAddReceived" enctype="multipart/form-data">
<table cellpadding="0" cellspacing="0" width="100%" border="0">
		<!--tao tac hidden!-->
		<tr>
			<td>
				<?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null); ?>
				<?php echo $this->formHidden("hdn_deleted_new_file_id_list","",null); ?>
				<?php echo $this->formHidden("hdnCode","",null); ?>
				<?php echo $this->formHidden("hdn_xml_tag_list","",null); ?>
				<?php echo $this->formHidden("hdn_xml_value_list","",null); ?>
				<?php echo $this->formHidden("hdn_XmlTagValueList","",null); ?>
				<?php echo $this->formHidden("hdh_option",$this->option,null); ?>
				<!--Sinh mot hidden luu ID VB!-->
				<?php echo $this->formHidden("hdn_object_id",$this->sentID,null); ?>	
				<!--Bien hdn_deleted_new_file_id_list dung de luu Id cua nhung doi tuong file dinh kem se xoa-->	
				<?php echo $this->formHidden("hdn_deleted_new_file_id_list","",null); ?>	
				<!--Bien hdn_deleted_exist_file_id_list dung de ...-->	
				<?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null); ?>	
				<?php echo $this->formHidden("hdnListId","",null); ?>
				<?php echo $this->formHidden("hdn_doc_type","",null); ?>
				<?php echo $this->formHidden("hdn_signer_position_name","",null); ?>
				<?php echo $this->formHidden("showModalDialog","",null); ?>
				<?php echo $this->formHidden("fromDate",$this->fromDate,null);?>
				<?php echo $this->formHidden("toDate",$this->toDate,null);?>
				<?php echo $this->formHidden("FullTextSearch",$this->sFullTextSearch,null);?>
			</td>
		</tr>
	</table>
	<?php 
		$urlCalendar = $this->urlCalendar; 
		$arrSent = $this->arrSent;
		$arrConst = $this->arrConst;
		if($this->getStatusLeftMenu == 'QUAN')
				$sUrlBack = '../index/modul/QUAN';
		else 	$sUrlBack = '../index/modul/DONVI';
	?>
	<!--HIen thi tieu de man hinh danh sach!-->
	<div id ="content" >
		<div id="header_conten" style="height: 30px;border:none;border-bottom:1px solid #3399FF;">
			<h1 class="large_label"><?=$this->bodyTitle;?></h1>
		</div>
		<div  id="body_conten1">
				
			<div id ="body_conten1_left" >
					<ul >
						<li>
							<span >1. &nbsp;<?=$arrConst['_LOAI_VAN_BAN'] ?> </span>
							<?= $arrSent[0]['C_DOC_TYPE'] ?>&nbsp; 						
						</li>
						<li> 
							<span><?=$arrConst['_SO'] ?>/<?=$arrConst['_KY_HIEU'] ?></span>
							<?=$arrSent[0]['C_NUMBER'].$arrSent[0]['C_SYMBOL'] ?>
						</li>
						<li>
							<span>2. &nbsp; <?=$arrConst['_NGAY_PHAT_HANH'] ?></span>
							<?=$arrSent[0]['C_SENT_DATE'] ?>&nbsp;					
						</li>
						<li>
							<span>3. &nbsp; <?=$arrConst['_TRICH_YEU'] ?> </span>
							<?= $arrSent[0]['C_SUBJECT'] ?>			
						</li>
						<li>
							<span>4.&nbsp; <?=$arrConst['_LINH_VUC'] ?></span>
							<?= $arrSent[0]['C_DOC_CATE'] ?>	
						</li>
					</ul>
				</div><!-- End #body_conten1_left-->
				<div id="body_conten1_right" >
					<ul style="">
						<li>
							<span >5.&nbsp; <?=$arrConst['_SO_VAN_BAN'] ?></span>
							<?= $arrSent[0]['C_TEXT_BOOK_NAME'] ?>&nbsp;
						</li>
						<li>
							<span >6. &nbsp; <?=$arrConst['_TINH_CHAT'] ?></span>
							<?= $arrSent[0]['C_NATURE_NAME'] ?>&nbsp;	
						</li>
						<li>
							<span >7. &nbsp; <?=$arrConst['_DO_KHAN'] ?></span>
							<?= $arrSent[0]['C_TEXT_OF_EMERGENCY'] ?>&nbsp;
						</li>
						
						<li>						
							<span >8. &nbsp; <?=$arrConst['_SO_BAN']?></span>		
							<?= $arrSent[0]['SO_BAN'] ?> 			
							<span style="float:none;clear:none;display:inline;margin:0 30px ;"><?=$arrConst['_SO_TRANG'] ?> </span>	
							<?= $arrSent[0]['SO_TRANG'] ?>					
						</li>
						<li>
							<span >9. &nbsp; <?=$arrConst['_FILE_DINH_KEM'] ?></span>
							<?php	
								$strFileName 	= $arrSent[0]['C_FILE_NAME'];
								$sFile = Sys_Library::_getAllFileAttach($strFileName,"!#~$|*","!~!",$this->baseUrl . "attach-file/");
								echo $sFile;
							?>
						</li>						
					</ul>
				</div><!-- End #body_conten1_right-->
		</div>
		<div id="body_conten4">
			<div style="float:left; padding:5px 0 0 0; width:100%">	
				<label style="width:180px;">10.&nbsp; <?=$arrConst['_NGUOI_KY'] ?></label>
				<?= $arrSent[0]['C_SIGNER_POSITION_NAME'] ?>
			</div>		
			<div style="float:left;padding:5px 0 0 0; width:50%">
				<label style="width:180px;">11.&nbsp;<?=$arrConst['_PHONG_BAN_SOAN_THAO']?></label>
					<?php
						$arrUnit = $_SESSION['arr_all_unit'];
						echo Sys_Library::_getItemAttrById($arrUnit,$arrSent[0]['FK_UNIT'],'name');
					?>	
			</div>
			<div style="float:left; padding:5px 0 0 0; width:50%">
				<label style="width:220px;">12.&nbsp;<?=$arrConst['_CAN_BO_SOAN_THAO'] ?></label>
					<?php
						$arrStaff = $_SESSION['arr_all_staff'];
						echo Sys_Library::_getItemAttrById($arrStaff,$arrSent[0]['FK_STAFF'],'name');
					?>
			</div>
			<div style="float:left; padding:5px 0 5px 0; width:100%">
					<label style="width:180px;">13.&nbsp; <?=$arrConst['_NOI_NHAN'] ?></label>
					<?= $arrSent[0]['C_RECEIVE_PLACE'] ?>
			</div>		
			<br clear="all">
		</div>
		<div class="normal_label" style="padding:5px;"><b>LƯU TRỮ HỒ SƠ</b></div>
		<div style="float:left; width:50% ;padding:5px 0 0 0;" class="normal_label">
			<label style="width:160px;">1. &nbsp;<?=$arrConst['_GIA_SO'] ?></label>
			<?= $arrSent[0]['GIA_SO'] ?>
		</div>
		<div style="float:left; width:50%; padding:5px 0 0 0;" class="normal_label">
			<label style="width:200px;">2. &nbsp;<?=$arrConst['_HOP_CAP_SO'] ?></label>
			<?= $arrSent[0]['CAP_SO'] ?>
		</div>
	</div>	
	<!--Hien thi nut!-->		
	<table width='99%'  border='0' cellspacing='0' cellpadding='0' align='center' class='normal_label'>
		<tr><td style="height:20px;"><hr width='100%' color='#3399FF' size='1'></td></tr>		
		<tr>
			<td align="center" style="padding-bottom:10px;">	
				<input id="btn_print" name="btn_print" type="button" class="add_large_button" value="In" onclick="btn_print_infor_onclick(document.getElementById('hdn_object_id'),'../printdoc');">
				<?=$this->formsubmit('button','Quay lại',array("onClick"=>"document.getElementById('hdh_option').value='QUAY_LAI';actionUrl('$sUrlBack');","class"=>"add_large_button"))?>
			</td>
		</tr>			
	</table>	
</form>
<script type="text/javascript">
	$(function(){$('#body_conten1').equalHeights();});
</script>
