<?php 
$arrPermission = $_SESSION['arrStaffPermission'];
if($arrPermission['PCXL_CONG_VIEC_PHONG_BAN'])
{
?>
<form action="index" method="POST" id="frmAddReceived" enctype="multipart/form-data" autocomplete="off" onsubmit="return checkform()">
<?php 
	
?>
	<table cellpadding="0" cellspacing="0" width="100%" border="0">
		<!--tao tac hidden!-->
		<tr>
			<td>
				<?php echo $this->formHidden("hdnCode","",null); ?>
				<?php echo $this->formHidden("hdn_xml_tag_list","",null); ?>
				<?php echo $this->formHidden("hdn_xml_value_list","",null); ?>
				<?php echo $this->formHidden("hdn_XmlTagValueList","",null); ?>
				<!--Sinh mot hidden luu ID VB!-->
				<?php echo $this->formHidden("hdn_object_id",$this->sWorkId,null); ?>		
				<!--Bien luu loai VB"!-->
				<?php echo $this->formHidden("hdn_doc_type","",null); ?>
				<?php echo $this->formHidden("hdn_signer_position_name","",null); ?>
				<?php echo $this->formHidden("hdn_staff_id_list","",null); ?>
				<?php echo $this->formHidden("hdn_unit_id_list","",null); ?>
			</td>
		</tr>
	</table>
	<?php 
		$urlCalendar = $this->urlCalendar; 
		$arrConst = $this->arrConst;
		$arrWork  = $this->arrWork;
	?>
	<!--HIen thi tieu de man hinh danh sach!-->
	<div style="margin:auto;padding-top:10px 0px;width:98%;">
		<div>
			<h1 class="info"><?=$this->infowork?></h1>
		</div>
		<table class="table_detail_doc" border="1">
			<col width="14%"><col width="11%"><col width="20%"><col width="55%">
			<tr>
				<td><?=$arrConst['_NGAY_GIAO_VIEC']?></td>
				<td><?=$arrWork[0]['C_APPROVE_DATE'].'&nbsp;'?></td>
				<td><?=$arrConst['_LANH_DAO_GIAO_VIEC']?></td>
				<td><?=$arrWork[0]['C_LEADER_POSITION_NAME'].'&nbsp;'?></td>
			</tr>
			<tr>
				<td><?=$arrConst['_NOI_DUNG_CONG_VIEC']?></td>
				<td colspan="3"><?=$arrWork[0]['C_WORK_CONTENT'].'&nbsp;'?></td>
			</tr>
			<tr>
				<td><?=$arrConst['_GHI_CHU']?></td>
				<td colspan="3"><?=$arrWork[0]['C_NOTES'].'&nbsp;'?></td>
			</tr>
			<?php
				$strFileName 				= $arrWork[0]['C_FILE_NAME'];
				if($strFileName != ""){
					$sFile 					= Sys_Library::_getAllFileAttach($strFileName,"!#~$|*","!~!",$this->baseUrl . "attach-file/");
					$dsp = '';
				}else{
					$sFile = "";
					$dsp = 'none';
				}
			?>
			<tr style="display:<?=$dsp?>;">
				<td><?=$arrConst['_FILE_DINH_KEM']?></td>
				<td colspan="3"><?=$sFile?></td>
			</tr>
		</table>
	</div>
	<div id ="content">
		<div id="header_conten" style="height: 10px;padding-bottom:15px;border-bottom:none;">
			<h1 class="info" style="color:#CA1010;text-align:left;"><?=$this->infoassign;?></h1>
		</div>
		<div id="body_conten1">
					<div style ="margin-top:5px;">
						<label><?=$arrConst['_NGAY_THUC_HIEN']?><span class="requiein">*</span></label>
						<input class="textbox" style="width:10%;"  id ="C_ASSIGN_DATE" name="C_ASSIGN_DATE" type="text" isdate="true" option = "false"  xml_tag_in_db="" xml_data="false" column_name="C_ASSIGN_DATE" message="<?php echo "NGAY THUC HIEN khong dung dinh dang ngay/thang/nam!";?>" onKeyDown="change_focus(document.forms[0],this)" onkeyup="DateOnkeyup('C_APPROVE_DATE',this,event)" />
						<img src="<?= $this->baseUrl?>images/calendar.gif" border="0" onclick="DoCal('<?= $urlCalendar;?>',document.getElementById('C_ASSIGN_DATE'));" style="cursor:pointer">	 
					</div>
					<div>
						<label><?=$arrConst['_Y_KIEN_CHI_DAO']?><span class="requiein">*</span></label>
						<textarea style="width:67%;"  class="textbox normal_textarea" id="C_IDEA" option = "false" rows="2" name="C_IDEA" message="Phai xac dinh Y KIEN CHI DAO!"></textarea>
					</div>
					<div>
						<label><?=$arrConst['_CAN_BO_XU_LY']?><span class="requiein">*</span></label>
						<textarea style="width:67%;"  class="textbox normal_textarea" id="C_STAFF_NAME_LIST" option = "false" rows="2" name="C_STAFF_NAME_LIST" message="Phai xac dinh CAN BO XU LY!"></textarea>
					</div>
					<div>
						<label style="float:left; clear:right;display:block;"><?=$arrConst['_HAN_XU_LY']?></label> 
						<label style="float:left; clear:right;display:block;margin-left:0;width:7%;"><?=$arrConst['_SO_NGAY']?></label>
						<input style="width:5%;clear:right;float:left;" class="textbox c3" type="text" id="limit_date" name="limit_date" align="right" optional = "true" xml_tag_in_db="limit_date" xml_data="true" column_name="" message="SO NGAY phai la so nguyen duong (1, 2, ...)!" onblur="appointed_date(document.getElementById('C_ASSIGN_DATE').value,document.getElementById('limit_date'),document.getElementById('C_APPOINTED_DATE'));">
						<label style="float:left; clear:right;display:block;margin-left:10px;width:5%;"><?=$arrConst['_NGAY']?></label>				
						<input style="width:10%;" class="textbox c3" id ="C_APPOINTED_DATE" name="C_APPOINTED_DATE" type="text" isdate="true" optional = "true" message="HAN XU LY khong dung dinh dang ngay/thang/nam!" onKeyDown="change_focus(document.forms[0],this)" onkeyup="DateOnkeyup('C_APPOINTED_DATE',this,event)" />
						<img src="<?= $this->baseUrl?>images/calendar.gif" border="0" onclick="DoCal('<?= $urlCalendar;?>',document.getElementById('C_APPOINTED_DATE'));" style="cursor:pointer">	 	
					</div>
				<div id="clear"></div>
		</div>
		
	</div>	
	<!--Hien thi nut!-->		
	<table style="margin-top:10px;" width='98%'  border='0' cellspacing='0' cellpadding='0' align='center' class='normal_label'>	
		<tr>
			<td align="center" style="padding:10px 0;">	
				<button name="btn_ghitam" id="btn_ghitam" type="button" value="Ghi tạm" class="add_large_button" onClick="btn_save_work(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'','<?=date("d/m/Y");?>',document.getElementById('C_ASSIGN_DATE'),'NGÀY THỰC HIỆN không thể là ngày tương lai');"><?=$arrConst['_GHI']?></button>
				<input type="button" style="margin-left:0px;" name="quaylai" id="quaylai" value="<?=$arrConst['_QUAY_LAI']?>" onClick="btn_back_onclick('../index/modul/CHO_PHAN_CONG')" class="add_large_button">
			</td>
		</tr>			
	</table>
</form>
<?php echo $this->search_textselectbox_staff; ?>

<script type="text/javascript"> 
document.getElementById('C_ASSIGN_DATE').value = '<?=date('d/m/Y')?>'
//Bat su kien khi NSD nhan cac phim tat sau
shortcut.add("Ctrl+G",function() {
	btn_save_work(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'','<?=date("d/m/Y");?>',document.getElementById('C_ASSIGN_DATE'),'NGÀY THỰC HIỆN không thể là ngày tương lai');
});
function checkform(){
	if(!verify(document.forms[0])){
		return false;
	}
}
function checkvalue(){
}
</script>
<style>
	h1.info{
		color:#CA1010;
		font-size:16px;
		font-weight:bold;
		vertical-align:middle;
		font-family:Arial;
		padding:0px 0px;
		margin:5px 0px;
	}
</style>
<?php } 
else 
	echo 'Bạn không có quyền truy cập chức năng này';
?>