<form action="index" method="POST" id="frmAddReceived" enctype="multipart/form-data" autocomplete="off">
<?php 
	$arrReceived = $this->arrReceived;
	$urlCalendar = $this->urlCalendar;
	$arrConst = $this->arrConst; 
	//echo 'cate:'.$arrReceived[0]['C_DOC_CATE'];
	//Linh vuc
	$sDocCate = $arrReceived[0]['C_DOC_CATE'];
	$sLeaderApprove = $arrReceived[0]['C_LEADER_POSITION_NAME_LIST'];
	if ($sDocCate == "Công nghệ thông tin" || $sDocCate == "Nghiên cứu khoa học" || $sDocCate == "Khoa học công nghệ"){
		if (trim($sLeaderApprove) == ""){
			//Lanh dao UBND tinh
			if ($_SESSION['OWNER_CODE'] == "UBTINH"){
				$sLeaderApprove = "PCT - Nguyễn Văn Linh;CT - Bùi Văn Hải;";
			}		
		}
	}
	//echo $_SESSION['OWNER_CODE'];
?>
	<table cellpadding="0" cellspacing="0" width="100%" border="0">
		<!--tao tac hidden!-->
		<tr>
			<td>
				<?php echo $this->formHidden("hdn_xml_tag_list","",null); ?>
				<?php echo $this->formHidden("hdn_xml_value_list","",null); ?>
				<?php echo $this->formHidden("hdn_XmlTagValueList","",null); ?>
				<!--Sinh mot hidden luu ID VB!-->
				<?php echo $this->formHidden("hdn_object_id",$this->sReceiveDocumentId,null); ?>		
				<!--Bien hdn_deleted_new_file_id_list dung de luu Id cua nhung doi tuong file dinh kem se xoa-->	
				<?php echo $this->formHidden("hdn_deleted_new_file_id_list","",null); ?>	
				<!--Bien hdn_deleted_exist_file_id_list dung de ...-->	
				<?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null); ?>	
				<?php echo $this->formHidden("hdn_leader_id_list","",null); ?>
		
				<?php echo $this->formHidden("hdn_current_page",$this->currentPage,null); ?>
				<?php echo $this->formHidden("hdn_record_number_page",$this->numRowOnPage,null); ?>
				 
				<?php echo $this->formHidden("FullTextSearch",$this->FullTextSearch,null); ?>
				<?php echo $this->formHidden("status",$this->sStatus,null); ?>
			</td>
		</tr>
	</table>
	<!--HIen thi tieu de man hinh danh sach!-->
	<div style="margin:auto;padding:10px 5px;width:98%;"><?= Sys_Function_DocFunctions::DocShowInfoDocument($this->sReceiveDocumentId);?></div>
	<div id ="content">
		<div id="header_conten" style="height:20px;">
			<div class="large_title" style="padding-left:1px;text-align:left;float:left;"> <?=$this->bodyTitle;?> </div>
			<div style="text-align:right; float:right;">
				<a style="cursor:pointer;" class="small_link" onClick="btn_save_doc_received_distribution(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'','<?=date("d/m/Y");?>');"><?=$arrConst['_GHI'] ?>&nbsp;|</a> 
				<a style="cursor:pointer;" class="small_link" onClick="btn_back_onclick('<?=$this->historyBack?>')">&nbsp;<?=$arrConst['_QUAY_LAI']?></a>
			</div>
		</div>
		<div id="body_conten1" style="padding-top:5px;">
			<div>
				<label>1.&nbsp;<?=$arrConst['_NGAY_THUC_HIEN']?><span class="requiein">*</span></label> 
				<input id ="C_DISTRIBUTION_DATE" name="C_DISTRIBUTION_DATE" type="text" isdate="true" value="<?=$arrReceived[0]['C_DISTRIBUTION_DATE'];?>" option = "true"  xml_tag_in_db="" xml_data="false" column_name="C_DISTRIBUTION_DATE" message="NGAY THUC HIEN khong dung dinh dang ngay/thang/nam!" onKeyDown="change_focus(document.forms[0],this)">
				<img src="<?= $this->baseUrl?>images/calendar.gif" border="0" onclick="DoCal('<?= $urlCalendar;?>',document.getElementById('C_DISTRIBUTION_DATE'));" style="cursor:pointer">	 						
			</div>				
			<div>
				<label>2.&nbsp;<?=$arrConst['_YK_LD_VP']?></label>
				<textarea  class="textbox normal_textarea" id="C_LEADER_OFFICE_IDEA" name="C_LEADER_OFFICE_IDEA"  optional = "true"  rows="2" message="" ><?=$arrReceived[0]['C_LEADER_OFFICE_IDEA'];?></textarea>
			</div>
			<div>
				<label>3.&nbsp;<?=$arrConst['_LANH_DAO_NHAN_VB']?><span class="requiein">*</span></label>
				<textarea class="normal_textarea" id="C_LEADER_POSITION_NAME_LIST" option = "true"  rows="2" name="C_LEADER_POSITION_NAME_LIST" message="Phai xac dinh thong tin LANH DAO NHAN VAN BAN!"><?=$sLeaderApprove;?></textarea>
			</div>
		<?php
		$arrPermission = $_SESSION['arrStaffPermission'];
		if($arrPermission['CAP_NHAT_PCXL_VB_DV']){?>
			<div>
				<label>4.&nbsp;<?=$arrConst['_DON_VI_PHONG_BAN_NHAN']?></label>
				<textarea class="normal_textarea" id="C_UNIT_NAME_LIST" optional = "true"  rows="2" name="C_UNIT_NAME_LIST" message=""><?=$arrReceived[0]['C_UNIT_NAME_LIST'];?></textarea>
			</div>	
			<div>
				<label>5.&nbsp;<?=$arrConst['_CAN_BO_NHAN']?></label>
				<textarea class="normal_textarea" id="C_STAFF_NAME_LIST" optional = "true"  rows="2" name="C_STAFF_NAME_LIST" message=""><?=$arrReceived[0]['C_STAFF_NAME_LIST'];?></textarea>
			</div>
			<div id = "AppointedDate">
				<label style="float:none; clear:right;display:inline;">6.&nbsp;<?=$arrConst['_HAN_XU_LY']?></label> 
				<label style="float:none; clear:none;display:inline;margin-left:23.5%"><?=$arrConst['_SO_NGAY']?></label>
				<input style="width:6%;" class="textbox" type="text" id="limit_date" name="limit_date" value="<?=$arrReceived[0]['C_LIMIT_DATE'];?>" align="right" optional = "true" xml_tag_in_db="limit_date" xml_data="true" column_name="" message="" onblur="appointed_date(document.getElementById('C_DISTRIBUTION_DATE').value,document.getElementById('limit_date'),document.getElementById('C_APPOINTED_DATE'));">														
				<label style="float:none; clear:none;display:inline;margin-left:0%"><?=$arrConst['_NGAY']?></label>				
				<input style="width:10%;" class="textbox" id ="C_APPOINTED_DATE" name="C_APPOINTED_DATE" type="text" isdate="true" value="<?=$arrReceived[0]['C_APPOINTED_DATE'];?>" optional = "true" message="HAN XU LY khong dung dinh dang ngay/thang/nam!" onKeyDown="change_focus(document.forms[0],this)">
				<img src="<?= $this->baseUrl?>images/calendar.gif" border="0" onclick="DoCal('<?= $urlCalendar;?>',document.getElementById('C_APPOINTED_DATE'));" style="cursor:pointer">	 										
			</div><?php 
		}?>	
		</div>
		
	</div>	
	<!--Hien thi nut!-->		
	<table width='99%'  border='0' cellspacing='0' cellpadding='0' align='center' class='normal_label'>
		<tr><td style="height:20px;"><hr width='100%' color='#3399FF' size='1'></td></tr>		
		<tr>
			<td align="center" style="padding-bottom:10px;">	
				<button name="btn_ghivaquaylai" id="btn_ghivaquaylai" type="button" value="Ghi" class="add_large_button" onClick="btn_save_doc_received_distribution(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'','<?=date("d/m/Y");?>');"><?=$arrConst['_GHI'] ?></button>
				<?=$this->formsubmit('button',$arrConst['_QUAY_LAI'],array("onClick"=>"btn_back_onclick('" . $this->historyBack . "')","class"=>"add_large_button"))?>
			</td>
		</tr>			
	</table>	
</form>
<?php echo $this->search_textselectbox_leader; 
	  if($arrPermission['CAP_NHAT_PCXL_VB_DV']){
	  	echo $this->search_textselectbox_unit;
	  	echo $this->search_textselectbox_staff;
	  }
?>
<script type="text/javascript"> 
if(document.getElementById('C_DISTRIBUTION_DATE').value == ''){
	document.getElementById('C_DISTRIBUTION_DATE').value = '<?=date("d/m/Y");?>';		
}	
</script>


