<form action="index" method="POST" id="frmAddReceived" enctype="multipart/form-data" autocomplete="off">
<?php 
	$arrReceived = $this->arrReceived;
	$urlCalendar = $this->urlCalendar;
	$arrConst = $this->arrConst;
	$arrAuthori = $this->arrAuthori;
	$ojbSysLib = new Sys_Library();
	
	//var_dump($arrAuthori);
	$i = 1;
?>
	<table cellpadding="0" cellspacing="0" width="100%" border="0">
		<!--tao tac hidden!-->
		<tr>
			<td>
				<?php echo $this->formHidden("hdn_xml_tag_list","",null); ?>
				<?php echo $this->formHidden("hdn_xml_value_list","",null); ?>
				<?php echo $this->formHidden("hdn_XmlTagValueList","",null); ?>
				<!--Sinh mot hidden luu ID VB!-->
				<?php echo $this->formHidden("hdn_object_id",$this->sReceiveDocumentId,null); ?>		
				<!--Bien hdn_deleted_new_file_id_list dung de luu Id cua nhung doi tuong file dinh kem se xoa-->	
				<?php echo $this->formHidden("hdn_deleted_new_file_id_list","",null); ?>	
				<!--Bien hdn_deleted_exist_file_id_list dung de ...-->	
				<?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null); ?>	
				<?php echo $this->formHidden("hdn_staff_id_list","",null); ?>
				<?php echo $this->formHidden("hdn_unit_id_list","",null); ?>
				
				<?php echo $this->formHidden("hdn_current_page",$this->currentPage,null); ?>
				<?php echo $this->formHidden("hdn_record_number_page",$this->numRowOnPage,null); ?>
				<?php echo $this->formHidden("fromDate",$this->fromDate,null); ?>	
				<?php echo $this->formHidden("toDate",$this->toDate,null); ?> 
				<?php echo $this->formHidden("FullTextSearch",$this->FullTextSearch,null); ?>

			</td>
		</tr>
	</table>
	<!--HIen thi tieu de man hinh danh sach!-->
	<div id ="content">
		<?php if($arrAuthori){
			//echo getdate();
			//if($arrAuthori[0]['C_END_DATE'] < getdate()){
			?>
		<div style="font-family:tahoma; border: solid 1px #ccc; margin-top:10px; height: 20px; width: 100%; padding: 4px;  border-radius: 4px 4px 4px 4px; background-color: #FAFAFA; color:red;">
			Thông báo ủy quyền: đ/c <?php echo $arrAuthori[0]['C_NAME']; ?> được Ủy quyền xử lý các công việc từ ngày <b><?php echo $ojbSysLib->_yyyymmddToDDmmyyyyhhmmss($arrAuthori[0]['C_START_DATE']); ?></b> đến ngày <b><?php echo $ojbSysLib->_yyyymmddToDDmmyyyyhhmmss($arrAuthori[0]['C_END_DATE']);?></b>		
		</div>
		<?php } //} ?>
		<!-- 
		<div id="header_conten" style="height:30px;">
			<h1 style="float:left;margin-left:30%;" class="large_label"><?=$this->bodyTitle;?></h1>
			<div style="text-align:right;float:right;margin:10px 0 5px;">
				<a style="cursor:pointer;" class="small_link" onClick="btn_doc_distribution_assign_onclick(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'');"><?=$arrConst['_GHI'] ?>&nbsp;</a> 
				<a style="cursor:pointer;" class="small_link" onClick="btn_back_onclick('../index/')">&nbsp;<?=$arrConst['_QUAY_LAI']?></a>
			</div>
		</div>
		 -->
		 <br/>
		<div id="body_conten1">
					<div>
						<label><?=$i++?>.&nbsp;<?=$arrConst['_NGAY_THUC_HIEN']?><span class="requiein">*</span></label>
						<input style="width:10%;margin-top:8px;margin-left:-1%;" id ="C_PROCESSION_DATE" name="C_PROCESSION_DATE" type="text" isdate="true" value="<?=$arrReceived[0]['C_PROCESSION_DATE'];?>" option = "true"  xml_tag_in_db="" xml_data="false" column_name="C_PROCESSION_DATE" message="NGAY THUC HIEN khong dung dinh dang ngay/thang/nam!" onKeyDown="change_focus(document.forms[0],this)">
							 						
					</div>
				<?php 
				if($_SESSION['OWNER_ID'] == Sys_Init_Config::_setParentOwnerId()){?>	
					<div>
						<label style="height:13px;line-height:12px;width:29%;"><?=$i++?>.&nbsp;<?=$arrConst['_YK_LD_VP']?></label>
						<textarea style="width:68.38%;margin-left:1%;" class="normal_textarea" id="C_LEADER_OFFICE_IDEA" optional = "true" rows="2" name="C_LEADER_OFFICE_IDEA"><?=$arrReceived[0]['C_LEADER_OFFICE_IDEA'];?></textarea>
					</div><?php
				}else {?>
					<div style="height:3px;"></div><?
				}?>		
						
							<?php
								//Danh sach LANH DAO DAO DON VI
								$arrLeader = $this->arrLeader;				
								//Danh sach LANH DAO DAO DON VI da cho Y KIEN CHI DAO
								$sLeaderIdList = $arrReceived[0]['FK_LEADER_ID_LIST_ALL'];			
								//Danh sach Y KIEN CHI DAO		
								$sLeaderIdeaList = $arrReceived[0]['C_IDEA_LIST_ALL'];				
								echo Sys_Function_DocFunctions::generateUnitLeaderList($arrLeader,$sLeaderIdList,$sLeaderIdeaList);
								//echo htmlspecialchars(Sys_Function_DocFunctions::generateUnitLeaderList($arrLeader));
							?>
					
				<?php 
				//if($_SESSION['OWNER_ID'] == Sys_Init_Config::_setParentOwnerId()){?>	
					<div>
						<label style="height:13px;line-height:12px;width:29%;margin-top:10px;"><?=$i++?>.&nbsp;<?=$arrConst['_CHUYEN_PHONG_BAN']?></label>
						<textarea style="width:68.38%;margin-left:1%;margin-top:10px;"  class="normal_textarea" id="C_UNIT_ID_LIST" optional = "true" rows="2" name="C_UNIT_ID_LIST"><?=$arrReceived[0]['C_UNIT_NAME_LIST'];?></textarea>
					</div><?php
				//}else {?>
					<div style="height:3px;"></div><?
				//}?>				
					<div>
						<label style="height:13px;line-height:12px;width:29%;"><?=$i++?>.&nbsp;<?=$arrConst['_CHUYEN_CAN_BO']?></label>
						<textarea style="width:68.38%;margin-left:1%;" class="normal_textarea" id="C_STAFF_ID_LIST" optional = "true" rows="2" name="C_STAFF_ID_LIST"><?=$arrReceived[0]['C_STAFF_POSITION_NAME_LIST'];?></textarea>
					</div>
					<div>
						<label style="float:none; clear:right;display:inline;"><?=($i++)?>.&nbsp;<?=$arrConst['_HAN_XU_LY']?></label> 
						<label style="float:none; clear:none;display:inline;margin-left:23%"><?=$arrConst['_SO_NGAY']?></label>
						<input style="width:5%;" class="textbox c3" type="text" id="limit_date" name="limit_date" value="<?=$arrReceived[0]['C_LIMIT_DATE'];?>" align="right" optional = "true" xml_tag_in_db="limit_date" xml_data="true" column_name="" message="SO NGAY phai la so nguyen duong (1, 2, ...)!" onblur="appointed_date(document.getElementById('C_PROCESSION_DATE').value,document.getElementById('limit_date'),document.getElementById('C_APPOINTED_DATE'));">
						<label style="float:none; clear:none;display:inline;margin-left:0%"><?=$arrConst['_NGAY']?></label>				
						<input style="width:10%;" class="textbox c3" id ="C_APPOINTED_DATE" name="C_APPOINTED_DATE" type="text" isdate="true" value="<?=$arrReceived[0]['C_APPOINTED_DATE'];?>" optional = "true" message="HAN XU LY khong dung dinh dang ngay/thang/nam!" onKeyDown="change_focus(document.forms[0],this)">							 										
					</div>
		</div>
		
	</div>	
	<!--Hien thi nut!-->		
	<br/>
	<table width='99%'  border='0' cellspacing='0' cellpadding='0' align='center' class='normal_label'>			
		<tr>
			<td align="center" style="padding-bottom:10px;">	
				<button name="btn_ghivaquaylai" id="btn_ghivaquaylai" type="button" value="Ghi" class="add_large_button" onClick="btn_doc_distribution_assign_onclick(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'');"><?=$arrConst['_GHI'] ?></button>
				<?=$this->formsubmit('button',$arrConst['_QUAY_LAI'],array("onClick"=>"btn_back_onclick('" . $this->historyBack . "')","class"=>"add_large_button"))?>
			</td>
		</tr>			
	</table>	
</form>
<?php echo $this->search_textselectbox_staff; ?>
<?php //if($_SESSION['OWNER_ID'] == Sys_Init_Config::_setParentOwnerId())
echo $this->search_textselectbox_unit; ?>
<script type="text/javascript"> 
if(document.getElementById('C_PROCESSION_DATE').value == ''){
	document.getElementById('C_PROCESSION_DATE').value = '<?=date("d/m/Y");?>';		
}	
//
function test(obj){
	//value = obj.value;
	n = obj.length;
	if (n > 0){
		alert("OK");
	}
}
</script>
<script type = "text/javascript">
$(function() {
	$( "#C_PROCESSION_DATE" ).datepicker({
		changeMonth: true,
		gotoCurrent: true,
		maxDate: '+1m +1w',
		minDate: new Date(1945, 1 - 1, 1),
		changeYear: true
	});
	$( "#C_APPOINTED_DATE" ).datepicker({
		changeMonth: true,
		gotoCurrent: true,
		maxDate: '+1m +1w',
		minDate: new Date(1945, 1 - 1, 1),
		changeYear: true
	});
});
</script>

