<base target=_self>
<form action="index" method="POST" id="frmReceived" autocomplete="off">
<div>
	<!--Cac doi tuong hidden tren form-->
	<?php echo $this->formHidden("hdn_docrelate_id_list","",null); ?>
	<?php echo $this->formHidden("hdn_filter_xml_tag_list",$this->filterXmlTagList,null); ?>
	<?php echo $this->formHidden("hdn_filter_xml_value_list",$this->filterXmlValueList,null); ?>
	<?php echo $this->formHidden("hdn_object_id",$this->sReceiveDocumentId,null); ?>
	<?php echo $this->formHidden("hdn_save","",null); ?>
	<?php echo $this->formHidden("hdn_doc_type","",null); ?>
	<?php echo $this->formHidden("hdn_leader_id_list","",null); ?>
	<?php echo $this->formHidden("hdn_unit_id_list","",null); ?>
	<?php echo $this->formHidden("hdn_XmlTagValueList",$this->XmlTagValueList,null); ?>
	<?php echo $this->formHidden("hdn_current_page",$this->iCurrentPage,null); ?>
	<?php echo $this->formHidden("cbo_nuber_record_page",$this->iNumRowOnPage,null); ?>
	<?php echo $this->formHidden("hdn_record_number_page",$this->iNumRowOnPage,null); ?>
	<?php echo $this->formHidden("hdn_advande_search",$this->sadvandeSearch,null); ?>
	<?php echo $this->formHidden("hdn_subModulLeft",$this->getStatusLeftMenu,null); ?>
	<?php
		$arrConst 				= $this->arrConst;
		$arrResul 				= $this->arrResul;
		$objFunction 			= new Sys_Function_DocFunctions();
		$iLeaderId 				= $this->iLeaderId;
		if ($iLeaderId != '')
			$sLeaderPositionName	= Sys_Publib_Library::_getItemAttrById($_SESSION['arr_all_staff'],$iLeaderId,'position_code').' - '.Sys_Publib_Library::_getItemAttrById($_SESSION['arr_all_staff'],$iLeaderId,'name');
		else $sLeaderPositionName = '';
		if ($_SESSION['arrStaffPermission']['THEO_DOI_KQXL_VB_DEN_PB'] != 1 && $_SESSION['arrStaffPermission']['THEODOI_XLVBDEN_PX'] !=1 && $_SESSION['arrStaffPermission']['THEO_DOI_KQXL_VBDEN'] != 1)
				$disablebtn = 'disabled ="true"';
		else 	$disablebtn = "";
	?>
	<table>
		<tr>
			<td class="large_title" style="padding-left:7px;text-align:left;">
				<?=$this->bodyTitle;?>				
			</td>
		</tr>
	</table>
	<div class="box container c1">
		<div class="pad" style="padding:4px;">			
			<table align="center" cellpadding="0" cellspacing="0" width="98%" border="0" style="padding-left:0%;">
				<col width="7%" /><col width="7%" /><col width="7%" /><col width="8%" /><col width="14%" /><col width="13%" /><col width="16%" /><col width="17%" /><col width="11%" />
				<tr id="1">
					<td colspan="2" align="left"><label class="normal_label"><?=$arrConst['_LANH_DAO_GIAO_VIEC']?></label></td>
					<td colspan="3"><input tabindex ="1" style="width:97%;" type="text" id="C_LEADER_ID" name="C_LEADER_ID" class="textbox"value="<?=$sLeaderPositionName ?>" onchange="ResetSearch();"/></td>
					<td align="left"><label style="margin-left:25%;" class="normal_label"><?=$arrConst['_TRANG_THAI']?></label></td>
					<td>
						<select tabindex ="3" style="width:100%;" id="C_STATUS" name="C_STATUS">
							<option value="">Chọn trạng thái</option>
							<option value="DANG_XU_LY">Đang xử lý</option>
							<option value="DA_XU_LY">Đã xử lý</option>
							<option value="QUA_HAN">Quá hạn</option>
						</select>
					</td>
				</tr>
				<tr id="2">
					<td colspan="2" align="left"><label class="normal_label"><?=$arrConst['_LOAI_VAN_BAN']?></label></td>
					<td colspan="3"><input tabindex ="2" style="width:97%;" type="text" id="C_DOC_TYPE" name="C_DOC_TYPE" class="textbox"value="<?= $this->sDocType ?>" onchange="ResetSearch();"/></td>
					<td align="left"><label style="margin-left:25%;" class="normal_label"><?=$arrConst['_DON_VI_XU_LY']?></label></td>
					<?php 
						if($_SESSION['arrStaffPermission']['THEO_DOI_KQXL_VB_DEN_PB'] == 1 || $_SESSION['arrStaffPermission']['THEODOI_XLVBDEN_PX'] == 1){ ?>
							<td colspan="3"><input readonly="true" tabindex ="4" style="width:75%;" type="text" id="C_UNIT_ID" name="C_UNIT_ID" class="textbox"value="<?= $objFunction->getNameUnitByIdUnitList($this->iUnitId,'') ?>" onchange="ResetSearch();"/></td>
					<?php }else {?>
							<td colspan="3"><input tabindex ="4" style="width:75%;" type="text" id="C_UNIT_ID" name="C_UNIT_ID" class="textbox"value="<?= $objFunction->getNameUnitByIdUnitList($this->iUnitId,'') ?>" onchange="ResetSearch();"/></td>
					<?php } ?>
				</tr>
				<tr>
					<td align="left"><label class="normal_label"><?=$arrConst['_TU_NGAY']?></label></td>
					<td colspan="2">
						<input tabindex ="5" style="width:75%;" id="fromDate" name="fromDate" type="text" isdate="true" value="<?=$this->fromDate?>" option = "false" onkeyup = "DateOnkeyup('fromDate',this,event)" message="<?php echo "NGAY THANG NAM khong dung dinh dang";?>">
					</td>
					<td align="center"><label class="normal_label"><?=$arrConst['_DEN_NGAY']?></label></td>
					<td>
						<input tabindex ="6" style="width:75%;" id="toDate" name="toDate" type="text" isdate="true" value="<?=$this->toDate?>" option = "false" onkeyup = "DateOnkeyup('toDate',this,event)" message="<?php echo "NGAY THANG NAM khong dung dinh dang";?>">
						
					</td>
					<td colspan="2"><input tabindex ="7" style="width:97%;" type="text" id="txtfullTextSearch" name="txtfullTextSearch" size="40%" value="<?= $this->sfullTextSearch ?>" /></td>
					<td align="left"><input tabindex ="8" type="checkbox" id="chkadvan" onclick="advandSearch(this)" /><label for='chkadvan' class="normal_label">Tìm kiếm nâng cao</label></td>
					<td align="center">
						<input tabindex ="9" <?=$disablebtn?> style="margin-top:-2px;" tabindex ="6" type="button" name="timkiem" id="timkiem" value="Tìm Kiếm" class="add_large_button"  onclick="actionUrl('');">
					</td>
				</tr>
			</table>
		</div>
	</div>
	<div style="height:20px;"></div>
	<table cellpadding="0" cellspacing="0" border="0" width="98%" align="center" class="list_table2" id="table1">
		<?php			
		$delimitor = $this->delimitor;//Lay ky tu phan cach giua cac phan tu
		//Hien thi cac cot cua bang hien thi du lieu
		$StrHeader = explode("!~~!",$this->GenerateHeaderTable("10%". $delimitor ."10%". $delimitor . "30%" . $delimitor . "20%" . $delimitor . "20%" . $delimitor . "10%"
										,$arrConst['_NGAY_DEN']. $delimitor . $arrConst['_SO_KY_HIEU'] . $delimitor . $arrConst['_TRICH_YEU'] . $delimitor . $arrConst['_Y_KIEN_CHI_DAO'] . $delimitor . $arrConst['_DON_VI_XU_LY'] . $delimitor . $arrConst['_HAN_XU_LY']
										,$delimitor));
		echo $StrHeader[0];					
		echo $StrHeader[1]; //Hien thi <col width = 'xx'><...		
			//Dinh nghia URL
			$sUrlView  = "../view/";
			$v_current_style_name = "round_row";
			$arrResul = $this->arrResul;	
			for($index = 0;$index < sizeof($arrResul);$index++){
				$sDocumentId 		= $arrResul[$index]['PK_RECEIVED_DOC'];		
				$sreceivedDate		= $objFunction->searchCharColor($this->sfullTextSearch,$arrResul[$index]['C_RECEIVED_DATE']) .'&nbsp;';								
				$sSymbol			= $objFunction->searchCharColor($this->sfullTextSearch,$arrResul[$index]['C_SYMBOL']) .'&nbsp;';			
				$strFileName 		= $arrResul[$index]['C_FILE_NAME'];
				$sFile 				= Sys_Library::_getAllFileAttach($strFileName,"!#~$|*","!~!",$this->baseUrl . "attach-file/");
				if($strFileName == '' || $strFileName == null){
					$sSubject		= $objFunction->searchStringColor($this->sfullTextSearch,$arrResul[$index]['C_SUBJECT']) .'&nbsp;';	
				}else {
					$sSubject		= $objFunction->searchStringColor($this->sfullTextSearch,$arrResul[$index]['C_SUBJECT']) .'<br>'. $sFile;
					$sFile 			= "";
				}
				$ssLeaderUnitIdea 	= $objFunction->searchStringColor($this->sfullTextSearch,$arrResul[$index]['C_LEADER_UNIT_IDEA']) .'&nbsp;';	
				$sProcessUnitName 	= $objFunction->searchStringColor($this->sfullTextSearch,$arrResul[$index]['C_PROCESS_UNIT_NAME_LIST']) .'&nbsp;';
				$sAppointedDate 	= $objFunction->searchStringColor($this->sfullTextSearch,$arrResul[$index]['C_APPOINTED_DATE']) .'&nbsp;';
				if ($v_current_style_name == "odd_row"){
					$v_current_style_name = "round_row";
				}else{
					$v_current_style_name = "odd_row";					
				}?>
				<tr class="<?=$v_current_style_name?>">	
					<td style="display:none;" align="center" style="padding-left:3px;padding-right:3px;" class="normal_label">
						<?=$this->formCheckbox('chk_item_id',$arrResul[$index]['PK_RECEIVED_DOC'], array('checked' => false,'onclick' =>'selectrow(this)'));?>					
					</td>
					<td ondblclick="item_onclick('<?=$sDocumentId?>','<?=$sUrlView?>')" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$sDocumentId?>');" align="center" valign="middle"  style="padding-left:3px;padding-right:3px;" class="normal_label"><?=$sreceivedDate;?></td>
					<td ondblclick="item_onclick('<?=$sDocumentId?>','<?=$sUrlView?>')" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$sDocumentId?>');" align="center" style="padding-left:3px;padding-right:3px;" class="normal_label"><?=$sSymbol?></td>	
					<td ondblclick="item_onclick('<?=$sDocumentId?>','<?=$sUrlView?>')" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$sDocumentId?>');" align="left" valign="middle" style="padding-left:3px;padding-right:3px;" class="normal_label"><?=$sSubject?></td>	
					<td ondblclick="item_onclick('<?=$sDocumentId?>','<?=$sUrlView?>')" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$sDocumentId?>');" align="left" valign="middle" style="padding-left:3px;padding-right:3px;" class="normal_label"><?=$ssLeaderUnitIdea?></td>	
					<td ondblclick="item_onclick('<?=$sDocumentId?>','<?=$sUrlView?>')" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$sDocumentId?>');" align="left" valign="middle" style="padding-left:3px;padding-right:3px;" class="normal_label"><?=$sProcessUnitName?></td>	
					<td ondblclick="item_onclick('<?=$sDocumentId?>','<?=$sUrlView?>')" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$sDocumentId?>');" align="center" valign="middle" style="padding-left:3px;padding-right:3px;" class="normal_label"><?=$sAppointedDate?></td>	
				</tr><?php
			}					
			//Tu dien cac dong trang trong truong hop du lieu tra ve < so row _CONST_NUMBER_OF_ROW_PER_LIST		
			if(sizeof($arrResul) < 15){	
				echo $this->addEmptyRow($this->iCountElement,15 - sizeof($arrResul),$v_current_style_name,6);		
			}	
		?>			
	</table>	
	<!--Hien thi trang can xem!-->
	
	<table width="100%" cellpadding="0" cellspacing="0" border="0" class='select_option_button'>
		<tr>
			<td style="color:red;width:30%;padding-left:1%;" class="small_label">
				<small class="small_starmark"><?=$this->sdocpertotal;?></small>
			</td>
			<td align="center" style="width="50%">
				<table width="10%"><?php
					//Hien thi danh sach so trang
					echo $this->generateStringNumberPage;?>
				</table>
			</td>
			<td width="30%" align="right" style="font-size:13px; padding-right:1%; font:tahoma" class="normal_label"><?php
				//Hien thi so trang
				echo $this->generateHtmlSelectBoxPage;?>
			</td>
		</tr>
	</table>
	<table width='100%'  border='0' cellspacing='0' cellpadding='0' align="center">
		<tr>
			<td style="padding-top: 10px; padding-bottom: 10px;" align="center" valign="middle">
				<?php 
					$iLeaderId	 = $objFunction->convertStaffNameToStaffId($sLeaderPositionName);
					$iUnitId 	 = $objFunction->convertUnitNameListToUnitIdList($this->iUnitId);
				?>
				<input type="button" class="add_large_button" value="&nbsp;&nbsp;&nbsp;<?=$arrConst['_IN']?>&nbsp;&nbsp;&nbsp;" onclick="btn_print_rop_onclick('../print/','<?=$sLeaderPositionName?>','<?=$this->iUnitId?>','<?=$this->sStatus?>','<?=$this->sDocType?>','<?=$this->fromDate?>','<?=$this->toDate?>','<?=$this->sfullTextSearch?>','<?=$this->sadvandeSearch?>');">
			</td>	
		</tr>
	</table>
</div>
</form>
<?php echo $this->search_textselectbox_doc_type;?>
<?php echo $this->search_textselectbox_leader;?>
<?php
	if($_SESSION['arrStaffPermission']['THEO_DOI_KQXL_VBDEN'] == 1)
		echo $this->search_textselectbox_unit;
?>
<script type="text/javascript">
$(document).ready(function() {
	document.getElementById('C_STATUS').value = '<?=$this->sStatus?>';
	if(document.getElementById('hdn_advande_search').value == 'yes'){
		$('tr#1').removeClass('dspnone');
		$('tr#2').removeClass('dspnone');
		document.getElementById('chkadvan').checked = true;
	}else{
		$('tr#1').addClass('dspnone');
		$('tr#2').addClass('dspnone');
		document.getElementById('hdn_advande_search').value = 'no';
		document.getElementById('chkadvan').checked = false;
	}
});
function advandSearch(obj){
	if(obj.checked){
		$('tr#1').removeClass('dspnone');
		$('tr#2').removeClass('dspnone');
		document.getElementById('hdn_advande_search').value = 'yes';
	}else{
		$('tr#1').addClass('dspnone');
		$('tr#2').addClass('dspnone');
		document.getElementById('hdn_advande_search').value = 'no';
	}
}
shortcut.add("Ctrl+K",function() {
	document.getElementById('txtfullTextSearch').focus();
	document.getElementById('txtfullTextSearch').select();
});
function ResetSearch(){
	document.getElementById('hdn_current_page').value = "1";
}
function checkvalue(){
	actionUrl('');
}
</script>
<style>
	.dspnone{
		display:none;
	}
</style>
<script type = "text/javascript">
$(function() {
	$( "#fromDate" ).datepicker({
		changeMonth: true,
		gotoCurrent: true,
		maxDate: '+1m +1w',
		minDate: new Date(1945, 1 - 1, 1),
		changeYear: true
	});
	$( "#toDate" ).datepicker({
		changeMonth: true,
		gotoCurrent: true,
		maxDate: '+1m +1w',
		minDate: new Date(1945, 1 - 1, 1),
		changeYear: true
	});
});
</script>

