<form action="index" method="POST" id="frmAddReceived" enctype="multipart/form-data">
<table cellpadding="0" cellspacing="0" width="100%" border="0">
		<!--tao tac hidden!-->
		<tr>
			<td class="large_title" style="padding-left:7px;text-align:left;">
				<?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null); ?>
				<?php echo $this->formHidden("hdn_deleted_new_file_id_list","",null); ?>
				<?php echo $this->formHidden("hdnCode","",null); ?>
				<?php echo $this->formHidden("hdn_xml_tag_list","",null); ?>
				<?php echo $this->formHidden("hdn_xml_value_list","",null); ?>
				<?php echo $this->formHidden("hdn_XmlTagValueList","",null); ?>
				<?php echo $this->formHidden("hdh_option",$this->option,null); ?>
				<!--Sinh mot hidden luu ID VB!-->
				<?php echo $this->formHidden("hdn_object_id",$this->sentID,null); ?>	
				<!--Bien hdn_deleted_new_file_id_list dung de luu Id cua nhung doi tuong file dinh kem se xoa-->	
				<?php echo $this->formHidden("hdn_deleted_new_file_id_list","",null); ?>	
				<!--Bien hdn_deleted_exist_file_id_list dung de ...-->	
				<?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null); ?>	
				<?php echo $this->formHidden("hdnListId","",null); ?>
				<?php echo $this->formHidden("hdn_doc_type","",null); ?>
				<?php echo $this->formHidden("hdn_signer_position_name","",null); ?>
				<?php echo $this->formHidden("showModalDialog","",null); ?>
				<?php echo $this->formHidden("FullTextSearch",$this->sFullTextSearch,null);?>
				<?php echo $this->formHidden("hdn_function_modul",$this->getModulLeft,null);?>
				<?=$this->bodyTitle;?>
			</td>
		</tr>
	</table>
		<?php 
		$arrSent = $this->arrSent;
		$urlCalendar = $this->urlCalendar;
		$arrConst = $this->arrConst;
	?>
	<script type="text/javascript">
		$(function(){$('#body_conten1').equalHeights();});
	</script>
	<!--HIen thi tieu de man hinh danh sach!-->
<div id ="content">
	<div id="header_conten" style="height: 10px;border:none;border-bottom:1px solid #3399FF;"></div>
	<div  id="body_conten1">
				<div id ="body_conten1_left">
					<div>
						<label>1.&nbsp;<?=$arrConst['_LOAI_VAN_BAN'] ?></label>
						<?= $arrSent[0]['C_DOC_TYPE'] ?>&nbsp;
					</div>
					<div>
						<label>2. &nbsp;<?=$arrConst['_NGAY_SOAN_THAO'] ?></label>
						<?= $arrSent[0]['C_SENT_DATE'] ?>&nbsp;
					</div>
					<div>
						<label>3. &nbsp;<?=$arrConst['_TRICH_YEU'] ?></label>
						<div class="content" style="clear:right;float:left;display:block;width:65%;text-align:justify;margin-right:2%;"><?= $arrSent[0]['C_SUBJECT']?></div>
					</div>
					<div>
						<label>4. &nbsp;<?=$arrConst['_LINH_VUC'] ?></label>
						<?= $arrSent[0]['C_DOC_CATE'] ?>&nbsp;
					</div>
				</div><!-- End #body_conten1_left-->
				<div id="body_conten1_right">
					<div>
						<label>5. &nbsp;<?=$arrConst['_TINH_CHAT'] ?></label>
						<?= Sys_Library::_getNameByCode($this->arrNature,$arrSent[0]['C_NATURE'],'C_NAME')?>&nbsp;
					</div>
					<div>
						<label >6. &nbsp;<?=$arrConst['_DO_KHAN'] ?></label>
						<?= $arrSent[0]['C_TEXT_OF_EMERGENCY'] ?>&nbsp;					
					</div>
					<div>
						<label>7. &nbsp;<?=$arrConst['_SO_BAN'] ?></label>
						<?=$arrSent[0]['SO_BAN'] ?>	&nbsp;	
						<label style="float:none;clear:none; display:inline;"><?=$arrConst['_SO_TRANG'] ?></label>
						<?=$arrSent[0]['SO_TRANG'] ?>&nbsp;
					</div>
					<div>
						<label style="width:98%">8. &nbsp;<?=$arrConst['_FILE_DINH_KEM'] ?></label>
					</div>		
							<?php	
								$strFileName 	= $arrSent[0]['C_FILE_NAME'];
								$sFile = Sys_Library::_getAllFileAttach($strFileName,"!#~$|*","!~!",$this->baseUrl . "attach-file/");
								echo $sFile;
							?>
				</div>
		</div>		
		<div id="body_conten4" > 
			<div style="float:left; width:50%">
					<label style="width:160px;">9.&nbsp;<?=$arrConst['_PHONG_BAN_SOAN_THAO'] ?></label>
					<?= $arrSent[0]['C_UNIT_NAME'] ?>&nbsp;
			</div>
			<div style="float:left; width:50%">
				<label style="width:160px;">10.&nbsp;<?=$arrConst['_CAN_BO_SOAN_THAO'] ?></label>
				<?= $arrSent[0]['C_STAFF_POSITION_NAME'] ?>&nbsp;
			</div>
            
			<div>
				<label style="width:160px;">11. &nbsp;<?=$arrConst['_NOI_NHAN'] ?></label>
				<?= $arrSent[0]['C_RECEIVE_PLACE'] ?>&nbsp;
			</div>
			<div>
					<label style="width:160px;">12. &nbsp;<?=$arrConst['_NGUOI_KY'] ?></label>
					<?= $arrSent[0]['C_SIGNER_POSITION_NAME'] ?>&nbsp;	
			</div>
			<?php
				$arrUnitName = explode(';!#~$|*', $arrSent[0]['C_IDEA_NAME']);
			?>

			<div >
				<label style="width:160px;">13. &nbsp;<?=$arrConst['_CAN_BO_Y_KIEN'] ?></label>
				<?= $arrUnitName[1] ?>&nbsp;
			</div>
			<div >
				<label style="width:160px;">14. &nbsp;<?=$arrConst['_PHONG_BAN_Y_KIEN'] ?></label>
				<?= $arrUnitName[0] ?>&nbsp;
			</div>
			<div>
				<label>15. &nbsp;<?=$arrConst['_HAN_TRA_LOI'] ?></label>
				<?= $arrSent[0]['C_APPOINTED_DATE'] ?>&nbsp;
			</div>
			<div style="border-top:1px solid #ccc;">
				<label style="width:160px;">16. &nbsp;<?=$arrConst['_VB_LIEN_QUAN'] ?></label>
			</div>	
            <br clear="all" />
			<div id="viewAllSentDocument" style="padding:0 0 10px 0;">	
						<table cellpadding="0" cellspacing="0" border="0" width="75%" align="center" class="list_table2" id="table1">
						<?php			
						$delimitor = $this->delimitor;//Lay ky tu phan cach giua cac phan tu
						//Hien thi cac cot cua bang hien thi du lieu
							$StrHeader = explode("!~~!",$this->GenerateHeaderTable("3%" . $delimitor . "15%" . $delimitor . "14%" . $delimitor . "45%" . $delimitor . "26%"
															,'' . $delimitor .$arrConst['_NGAY_SOAN_THAO']  . $delimitor . $arrConst['_SO_KY_HIEU'] . $delimitor . $arrConst['_TRICH_YEU'] . $delimitor . $arrConst['_DON_VI_PHAT_HANH'] 
															,$delimitor));
						echo $StrHeader[0];				
						echo $StrHeader[1]; //Hien thi <col width = 'xx'><...		
						//Dinh nghia URL
						$sUrView  = "../../view/";
						$sCurrentStyleName = "round_row";
						$arrRelate = $this->arrRelate	;
						for($index = 0;$index < sizeof($arrRelate);$index++){	
							//lay file dinh kem
							$strFileName 				= $arrRelate[$index]['C_FILE_NAME'];
							$sFile = Sys_Library::_getAllFileAttach($strFileName,"!#~$|*","!~!",$this->baseUrl . "attach-file/");
							$documentId 				= $arrRelate[$index]['PK_DOCUMENT'];				
							$sDate						= $arrRelate[$index]['C_DATE'] .'&nbsp;';	
							$sNumber					= $arrRelate[$index]['C_NUMBER'] ;
							$sSymbol					= $arrRelate[$index]['C_SYMBOL'].'&nbsp;';	
							//$sSubject					= $arrRelate[$index]['C_SUBJECT'].'&nbsp;';		
							$sUnitName					= $arrRelate[$index]['C_UNIT_NAME'] .'&nbsp;';					
							//Tai lieu kem theo ho so
							if($strFileName == '' || $strFileName == null){
								$sSubject				= $arrRelate[$index]['C_SUBJECT'] .'&nbsp;';
							}else {
								$sSubject				= $arrRelate[$index]['C_SUBJECT']. '<br>'.$sFile;
								$sFile = "";
							}
							if ($sCurrentStyleName == "odd_row"){
								$sCurrentStyleName = "round_row";
							}else{
								$sCurrentStyleName = "odd_row";					
							}?>					
							<tr class="<?=$sCurrentStyleName?>">	
								<td align="center" style="padding-left:3px;padding-right:3px;" class="normal_label">					
									
								</td>
								<td align="center" ondblclick="item_onclick('<?=$documentId?>','<?=$sUrView?>')" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$documentId?>');" style="padding-left:3px;padding-right:3px;" class="normal_label">
									<?=$sDate?>
								</td>								
								<!--Hien thi trich yeu!-->					
								<td ondblclick="item_onclick('<?=$documentId?>','<?=$sUrView?>')" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$documentId?>');"  style="padding-left:3px;padding-right:3px;" class="normal_label"><?=$sNumber.$sSymbol ?></td>
								<!--Hien ket qua xu ly!-->	
								<td align="left" ondblclick="item_onclick('<?=$documentId?>','<?=$sUrView?>')" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$documentId?>');"  style="padding-left:3px;padding-right:3px;" class="normal_label"><?=  $sSubject?></td>
								<td align="center" ondblclick="item_onclick('<?=$documentId?>','<?=$sUrView?>')" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$documentId?>');"  style="padding-left:3px;padding-right:3px;" class="normal_label"><?=  $sUnitName?></td>	
							</tr><?php
						}		
						//Tu dien cac dong trang trong truong hop du lieu tra ve < so row _CONST_NUMBER_OF_ROW_PER_LIST	
						echo $this->addEmptyRow($this->iCountElement,2,$sCurrentStyleName,5);			
						?>
					</table>	
			</div>	
			<div style="border-top:1px solid #ccc;">
				<label style="width:160px;">17. &nbsp;<?=$arrConst['_GHI_CHU'] ?></label>
				<?= $arrSent[0]['C_NOTE'] ?>
			</div>
			<br clear="all">
	</div>
			
		<table width='99%'  border='0' cellspacing='0' cellpadding='0' align='center' class='normal_label'>
		<tr><td style="height:20px;"><hr width='100%' color='#3399FF' size='1'></td></tr>		
		<tr>
			<td align="center" style="padding-bottom:10px;">	
				<input id="btn_print" name="btn_print" type="button" class="add_large_button" value="In" onclick="btn_print_infor_onclick(document.getElementById('hdn_object_id'),'print');">
				<?=$this->formsubmit('button','Quay lại',array("onClick"=>"document.getElementById('hdh_option').value='QUAY_LAI';actionUrl('index/modul/".$this->getModulLeft."');","class"=>"add_large_button"))?>
			</td>
		</tr>			
	</table>	
</div>		
</form>
<?php 
	 echo $this->search_textselectbox_signer;  
	 echo $this->search_doc_cate_name; 
	 echo $this->search_doc_type_name; 
	 echo $this->search_idea_staft_name ;
	 echo $this->search_idea_unit_name;
?>
