<form action="index" method="POST" id="frmSent" a>
<div><?php
	$arrConst = $this->arrConst;
	$arrSmsReceived = $this->arrSmsReceived;
	?>
	<table width='100%'  border='0' cellspacing='0' cellpadding='0' class="table_title">
		<tr>
			<td class="large_title" style="padding-left:7px;text-align:left;">
				<!--Cac doi tuong hidden tren form-->
				<?php echo $this->formHidden("hdn_current_page",$this->currentPage,null); ?>
				<?php echo $this->formHidden("cbo_nuber_record_page",$this->numRowOnPage,null); ?>
				<?php echo $this->formHidden("hdn_object_id_list","",null); ?>
				<?php echo $this->formHidden("hdn_filter_xml_tag_list",$this->filterXmlTagList,null); ?>
				<?php echo $this->formHidden("hdn_filter_xml_value_list",$this->filterXmlValueList,null); ?>
				<?php echo $this->formHidden("hdn_record_number_page",$this->numRowOnPage,null); ?>	
				<?php echo $this->formHidden("hdn_object_id",'',null); ?>
				<?php echo $this->formHidden("hdn_XmlTagValueList",$this->XmlTagValueList,null); ?>
				<!--Bien hdn_deleted_new_file_id_list dung de luu Id cua nhung doi tuong file dinh kem se xoa-->	
				<?php echo $this->formHidden("hdn_deleted_new_file_id_list","",null); ?>	
				<!--Bien hdn_deleted_exist_file_id_list dung de ...-->	
				<?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null); ?>	
				<?php echo $this->formHidden("htn_leftmodul","RECEIVED"); ?>	
				
				<!--Cac doi tuong hidden tren form-->
				<?=
					$this->bodyTitle ;
				?>
			</td>
		</tr>
	</table>	
	<table width='99%'  border='0' cellspacing='0' cellpadding='0' class="table_title">
		<tr>
			<td class="large_title" style="padding-left:7px;text-align:left;">&nbsp;
				
			</td>
			<td style="text-align:right;" valign="bottom">
					<a style="cursor:pointer;color:#0000FF;" onclick="btn_delete_onclick(document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id_list'),'../delete','','','');">Xóa</a>
			</td>
		</tr>
	</table>
	<div id="viewAllSentDocument">
		<table cellpadding="0" cellspacing="0" border="0" width="98%" align="center" class="list_table2" id="table1">
			<?php			
			$delimitor = $this->delimitor;//Lay ky tu phan cach giua cac phan tu
			//Hien thi cac cot cua bang hien thi du lieu
				$StrHeader = explode("!~~!",$this->GenerateHeaderTable("3%" . $delimitor . "20%" . $delimitor . "22%" . $delimitor . "15%" . $delimitor."15%" . $delimitor . "25%"
												,'<input type="checkbox" name="chk_all_item_id" value="" onclick="checkbox_all_item_id(document.forms[0].chk_item_id);">' . $delimitor .$arrConst['_TEN_CAN_BO'] . $delimitor . $arrConst['_DON_VI'] . $delimitor . $arrConst['_DIEN_THOAI'] . $delimitor. $arrConst['_THOI_GIAN_NHAN'] . $delimitor . $arrConst['_NOI_DUNG'] 
												,$delimitor));
			echo $StrHeader[0];				
			echo $StrHeader[1]; //Hien thi <col width = 'xx'><...		
			//Dinh nghia URL
			$sUrView  = "view";
			$sCurrentStyleName = "round_row";
			$objFunction =	new	Sys_Function_DocFunctions()	;	
			for($index = 0;$index < sizeof($arrSmsReceived);$index++){	
				$iId			 			= $arrSmsReceived[$index]['ID'];		
				$sReceived					= Sys_Publib_Library::_yyyymmddToDDmmyyyyhhmmss($arrSmsReceived[$index]['receivedtime']);					
				$sMsg 						= $arrSmsReceived[$index]['msg'];	
				$sPhone						= $arrSmsReceived[$index]['sender'];	
				$sStaffName					= $objFunction->convertTelMobileToName($arrSmsReceived[$index]['sender']);
				if(trim($sStaffName) !=''){
					$sUnitName					= $objFunction->getNameUnitByIdUnitList(Sys_Publib_Library ::_getItemAttrById($_SESSION['arr_all_staff'],$objFunction->convertStaffNameToStaffId($sStaffName),'unit_id'));	
				}else{
					$sStaffName = 'Tin lạc danh';
					$sUnitName = '';
				}
				
				if ($sCurrentStyleName == "odd_row"){
					$sCurrentStyleName = "round_row";
				}else{
					$sCurrentStyleName = "odd_row";					
				}?>					
				<tr class="<?=$sCurrentStyleName?>">	
					<td align="center" style="padding-left:3px;padding-right:3px;" class="normal_label">					
						<?=$this->formCheckbox('chk_item_id',$iId, array('checked' => false,'onclick' =>'selectrow(this)'));?>					
					</td>
					<td align="left" ondblclick="item_onclick('<?=$iId?>','<?=$sUrView?>')" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$iId?>');" style="padding-left:3px;padding-right:3px;" class="normal_label">
						<?=$sStaffName?> &nbsp; 
					</td>								
					<!--Hien thi trich yeu!-->					
					<td align="left"  ondblclick="item_onclick('<?=$iId?>','<?=$sUrView?>')" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$iId?>');"  style="padding-left:3px;padding-right:3px;" class="normal_label"><?=$sUnitName ?></td>
					<td align="center"  ondblclick="item_onclick('<?=$iId?>','<?=$sUrView?>')" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$iId?>');"  style="padding-left:3px;padding-right:3px;" class="normal_label"><?=$sPhone ?></td>
					<!--Hien ket qua xu ly!-->	
					<td align="center" ondblclick="item_onclick('<?=$iId?>','<?=$sUrView?>')" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$iId?>');"  style="padding-left:3px;padding-right:3px;" class="normal_label"><?=  $sReceived ?></td>
					<td align="left" ondblclick="item_onclick('<?=$iId?>','<?=$sUrView?>')" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$iId?>');"  style="padding-left:3px;padding-right:3px;" class="normal_label"><?=  $sMsg?></td>	
				</tr><?php
			}					
			//Tu dien cac dong trang trong truong hop du lieu tra ve < so row _CONST_NUMBER_OF_ROW_PER_LIST	
				echo $this->addEmptyRow($this->iCountElement,15 -sizeof($arrSmsReceived),$sCurrentStyleName,6);
			?>
		</table>	
		<!--Hien thi trang can xem!-->
			<?=$this->SelectDeselectAll;?>
		<table width="100%" cellpadding="0" cellspacing="0" border="0">
				<tr>
					<td  class="normal_label"style="color:red;width:23%;padding-left:1%;">
						<?=$this->sdocpertotal;?>
					</td>
					<td align="center" style="width:48%;.">
						<table width="10%"><?php
							//Hien thi danh sach so trang
							echo $this->generateStringNumberPage;?>
						</table>
					</td>
					<td width="25%" align="right" style="font-size:13px; padding-right:1%; font:tahoma" class="normal_label"><?php
						//Hien thi so trang
						echo $this->generateHtmlSelectBoxPage;?>
					</td>
				</tr>
		</table>
	</div>
	<table width='100%'  border='0' cellspacing='0' cellpadding='0' align="center">
		<tr>
			<td style="padding-top: 5px; padding-bottom: 5px;" align="center" valign="middle">
				<input type="button" class="add_large_button" value="Xóa" onclick="btn_delete_onclick(document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id_list'),'../delete');">
			</td>	
		</tr>
	</table>
</div>
</form>
<script>
function checkvalue(){};
</script>
