<form action="index" method="POST" id="frmAddReceived" enctype="multipart/form-data">
<table cellpadding="0" cellspacing="0" width="100%" border="0">
		<tr>			
			<!--Bien luu id nguoi co quyen xem-->			
			<?php echo $this->formHidden("hdn_view_staff",'',null); ?>	
			<?php echo $this->formHidden("hdn_option_view",'TAT_CA',null); ?>		
			<!--Bien luu trang thai ung voi tung nut "Ghi va Them moi;..."!-->
			<?php echo $this->formHidden("hdh_option",$this->option,null); ?>	
			<?php echo $this->formHidden("hdn_object_id",$this->sRecordArchivedId,null); ?>
			<?php echo $this->formHidden("htn_leftModule",$this->currentModulCodeForLeft,null); ?>
		</tr>
</table>
<?php 
	$arrConst = $this->arrConst;
	$urlCalendar = $this->urlCalendar; 
	//Thong tin nguoi tao van ban
	$StaffPositionCode 	= $this->sStaffPosition;
	$staffName			= $this->sStaffName;
	$sUnitName			= $this->sUnitName;
	$Creater 			= $StaffPositionCode.'-'.$staffName.' ,'.$sUnitName;
?>
<div id="content" style="border-bottom:1px solid #3399FF;padding-bottom:5px;margin-bottom:10px;">
	
	<table style="width:100%; border-bottom: 1px solid #3399FF;">
		<tr>
			<td class="large_title" style="padding-left:0px;text-align:left; width:30%;">
					<?=$this->bodyTitle;?>
				</td>
				<!-- 
				<td style="text-align:right; float:right; width:auto;">
					<a class="small_link" onClick="document.getElementById('hdh_option').value='GHI_THEMMOI';btn_save_record(document.getElementsByName('chk_staff_id'),document.getElementById('hdn_view_staff'),document.getElementById('hdn_option_view'),'');"><?=$arrConst['_GHI_THEM_MOI']?> </a> 
					<a class="small_link" onClick="document.getElementById('hdh_option').value='GHI_THEMTIEP';btn_save_record(document.getElementsByName('chk_staff_id'),document.getElementById('hdn_view_staff'),document.getElementById('hdn_option_view'),'');"><?=$arrConst['_GHI_THEM_TIEP']?> </a> 
					<a class="small_link" onClick="document.getElementById('hdh_option').value='GHI_QUAYLAI';btn_save_record(document.getElementsByName('chk_staff_id'),document.getElementById('hdn_view_staff'),document.getElementById('hdn_option_view'),'');"><?=$arrConst['_GHI_QUAY_LAI']?> </a> 
					<a class="small_link" onClick="document.getElementById('hdh_option').value='GHI_TAM';btn_save_record(document.getElementsByName('chk_staff_id'),document.getElementById('hdn_view_staff'),document.getElementById('hdn_option_view'),'');"><?=$arrConst['_GHI_TAM']?></a> 
					<a class="small_link" onclick="btn_back_onclick('../index/')"><?=$arrConst['_QUAY_LAI']?></a>	
				</td>
				 -->
			</tr>
	</table>	
	
	<div id="body_content">
		<div>
			<label class="lbl_title normal_label"><?=$arrConst['_NGUOI_TAO_LAP']?></label>
			<label class="normal_label"><?=$Creater?></label>
		</div>
		<div>
			<label class="lbl_title normal_label"><?=$arrConst['_NGAY_TAO']?><span class="requiein">*</span></label>
			<input value="<?=date('d/m/Y')?>" id ="C_CREATE_DATE" name="C_CREATE_DATE" type="text" isdate="true" option = "false"  xml_tag_in_db="" xml_data="false" column_name="C_CREATE_DATE" message="<?php echo "NGAY TAO khong dung dinh dang ngay/thang/nam!";?>" onKeyDown="change_focus(document.forms[0],this)" />			
		</div>
		<div>
			<label class="lbl_title normal_label"><?=$arrConst['_MA_HO_SO']?></label>
			<input autocomplete="off" style="width:30%;" id ="C_RECORD_ID" name="C_RECORD_ID" type="text" optional = "true"  xml_tag_in_db="" xml_data="false" column_name="C_RECORD_ID" message="">
		</div>
		<div>
			<label class="lbl_title normal_label"><?=$arrConst['_TEN_HO_SO']?><span class="requiein">*</span></label>
			<input autocomplete="off" style="width:88%;" id ="C_RECORD_NAME" name="C_RECORD_NAME" type="text"  option = "false"  xml_tag_in_db="" xml_data="false" column_name="C_RECORD_NAME" message="<?php echo "Phai xac dinh TEN HO SO!";?>" >
		</div>
		<div>
			<label class="lbl_title normal_label"><?=$arrConst['_GHI_CHU']?></label>
			<textarea style="width:88%;"  class="normal_textarea" id="C_NOTES" optional = "true" rows="2" name="C_NOTES"></textarea>
		</div>
		<div>
			<label class="lbl_title normal_label"><?=$arrConst['_QUYEN_XEM']?></label>
			<input type="radio" id="all1" value="all" name="quyen_xem" onclick="dsp_view(this.value)" checked /><label for = "all1" class="normal_label"><?=$arrConst['_TAT_CA']?></label>
			<input type="radio" id="unit" value="unit" name="quyen_xem" onclick="dsp_view(this.value)" /><label for = "unit" class="normal_label"><?=$sUnitName?></label>
			<input type="radio" id="other" value="other" name="quyen_xem" onclick="dsp_view(this.value)" /><label for = "other" class="normal_label"><?=$arrConst['_KHAC']?></label>
		</div>
	</div>
	<div id="option_view" style="display:none;">
		<div style="width:88%;margin-left:11%">
			<?php echo $this->generateFormHtml; ?>
		</div>
	</div>
</div>
<!--Hien thi nut!-->		
<table width='99%'  border='0' cellspacing='0' cellpadding='0' align='center' class='normal_label'>
	<tr>
		<td align="center" style="padding-bottom:10px;">	
			<button name="btn_ghivathemmoi" id="btn_ghivathemmoi" type="button" value="Ghi&amp;Thêm mới" class="add_large_button" onClick="document.getElementById('hdh_option').value='GHI_THEMMOI';btn_save_record(document.getElementsByName('chk_staff_id'),document.getElementById('hdn_view_staff'),document.getElementById('hdn_option_view'),'');"><?=$arrConst['_GHI_THEM_MOI']?></button>
			<button name="btn_ghivathemtiep" id="btn_ghivathemtiep" type="button" value="Ghi&amp;Thêm tiếp" class="add_large_button" onClick="document.getElementById('hdh_option').value='GHI_THEMTIEP';btn_save_record(document.getElementsByName('chk_staff_id'),document.getElementById('hdn_view_staff'),document.getElementById('hdn_option_view'),'');"><?=$arrConst['_GHI_THEM_TIEP']?></button>
			<button name="btn_ghivaquaylai" id="btn_ghivaquaylai" type="button" value="Ghi&amp;Quay lại" class="add_large_button" onClick="document.getElementById('hdh_option').value='GHI_QUAYLAI';btn_save_record(document.getElementsByName('chk_staff_id'),document.getElementById('hdn_view_staff'),document.getElementById('hdn_option_view'),'');"><?=$arrConst['_GHI_QUAY_LAI']?></button>
			<!--<button name="btn_ghitam" id="btn_ghitam" type="button" value="Ghi tạm" class="add_large_button" onClick="document.getElementById('hdh_option').value='GHI_TAM';btn_save_record(document.getElementsByName('chk_staff_id'),document.getElementById('hdn_view_staff'),document.getElementById('hdn_option_view'),'');"><?=$arrConst['_GHI_TAM']?></button> -->
			<input type="submit" style="margin-left:0px;" name="quaylai" id="quaylai" value="<?=$arrConst['_QUAY_LAI']?>" onClick="btn_back_onclick('../index/')" class="add_large_button">
		</td>
	</tr>			
</table>	
</form>

<script type="text/javascript">
	//Bat su kien khi NSD nhan cac phim tat sau
	shortcut.add("Ctrl+M",function() {
		document.getElementById('hdh_option').value='GHI_THEMMOI';
		btn_save_record(document.getElementsByName('chk_staff_id'),document.getElementById('hdn_view_staff'),document.getElementById('hdn_option_view'),'');
	});
	
	shortcut.add("Ctrl+E",function() {
		document.getElementById('hdh_option').value='GHI_THEMTIEP';
		btn_save_record(document.getElementsByName('chk_staff_id'),document.getElementById('hdn_view_staff'),document.getElementById('hdn_option_view'),'');
	});
	shortcut.add("Ctrl+Q",function() {
		document.getElementById('hdh_option').value='GHI_QUAYLAI';
		btn_save_record(document.getElementsByName('chk_staff_id'),document.getElementById('hdn_view_staff'),document.getElementById('hdn_option_view'),'');
	});
	
	shortcut.add("Ctrl+G",function() {
		document.getElementById('hdh_option').value='GHI_TAM';
		btn_save_record(document.getElementsByName('chk_staff_id'),document.getElementById('hdn_view_staff'),document.getElementById('hdn_option_view'),'');
	});
	function dsp_view(value){
		if(value == 'all'){
			document.getElementById('hdn_option_view').value = 'TAT_CA';
			document.getElementById('option_view').style.display = 'none';
			document.getElementsByName('hdn_view_staff').value = '';
		}
		if(value == 'other'){
			document.getElementById('hdn_option_view').value = 'KHAC';
			document.getElementById('option_view').style.display = 'block';
		}
		else{
			document.getElementById('hdn_option_view').value = 'PHONG_BAN';
			document.getElementById('option_view').style.display = 'none';
			document.getElementsByName('hdn_view_staff').value = '';
		}
	}
</script>
<script type = "text/javascript">
$(function() {
	$( "#C_CREATE_DATE" ).datepicker({
		changeMonth: true,
		gotoCurrent: true,
		maxDate: '+1m +1w',
		minDate: new Date(1945, 1 - 1, 1),
		changeYear: true
	});
	$( "#toDate" ).datepicker({
		changeMonth: true,
		gotoCurrent: true,
		maxDate: '+1m +1w',
		minDate: new Date(1945, 1 - 1, 1),
		changeYear: true
	});
});</script>