<form action="index" method="POST" id="frmAddReceived" enctype="multipart/form-data" autocomplete="off">
<?php 
	$urlCalendar = $this->urlCalendar;
	$arrConst = $this->arrConst; 
	$sStatus = $this->sStatus;
?>
	<table cellpadding="0" cellspacing="0" width="100%" border="0">
		<!--tao tac hidden!-->
		<tr>
			<td>
				<?php echo $this->formHidden("hdn_object_id_list","",null); ?>
				<?php echo $this->formHidden("hdn_xml_tag_list","",null); ?>
				<?php echo $this->formHidden("hdn_xml_value_list","",null); ?>
				<?php echo $this->formHidden("hdn_XmlTagValueList","",null); ?>
				<!--Sinh mot hidden luu ID VB!-->
				<?php echo $this->formHidden("hdn_object_id",$this->sReceiveDocumentId,null); ?>	
				<?php echo $this->formHidden("hdn_work_id",$this->sPkDocWorkId,null); ?>	
				<!--Bien hdn_deleted_new_file_id_list dung de luu Id cua nhung doi tuong file dinh kem se xoa-->	
				<?php echo $this->formHidden("hdn_deleted_new_file_id_list","",null); ?>	
				<!--Bien hdn_deleted_exist_file_id_list dung de ...-->	
				<?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null); ?>	
		
				<?php echo $this->formHidden("hdn_current_page",$this->currentPage,null); ?>
				<?php echo $this->formHidden("hdn_record_number_page",$this->numRowOnPage,null); ?>
				 
				<?php echo $this->formHidden("FullTextSearch",$this->FullTextSearch,null); ?>
				<?php echo $this->formHidden("status",$this->sStatus,null); ?>
				
			</td>
		</tr>
	</table>
	<!--HIen thi tieu de man hinh danh sach!-->
	<?= Sys_Function_DocFunctions::DocShowInfoDocument($this->sReceiveDocumentId);?>
	<div id ="content">
		<div id="header_conten" style="height:20px;">
			<div class="large_title" style="padding-left:1px;text-align:left;float:left;"> <?=$this->bodyTitle;?> </div>
			<div style="text-align:right;float:right;">
				<a style="cursor:pointer;" class="small_link" onClick="btn_save_doc_received_process('<?=date("d/m/Y");?>');"><?=$arrConst['_GHI'] ?>&nbsp;</a> 
				<a style="cursor:pointer;" class="small_link" onClick="btn_back_onclick('<?=$this->historyBack?>')">&nbsp;<?=$arrConst['_QUAY_LAI']?></a>
			</div>
		</div>
		<div id="body_conten1" style="padding-top:5px;">		 
				<div>
					<label>1.&nbsp;<?=$arrConst['_NGAY_THUC_HIEN']?><span class="requiein">*</span></label> 
					<input id ="C_WORK_DATE" name="C_WORK_DATE" type="text" isdate="true" value=""  option = "true"  xml_tag_in_db="" xml_data="false" column_name="C_WORK_DATE" message="NGAY THUC HIEN khong dung dinh dang ngay/thang/nam!" onKeyDown="change_focus(document.forms[0],this)">						 				
				</div>				
				<div>
					<label>2.&nbsp;<?=$arrConst['_KET_QUA_XU_LY'] ?><span class="requiein">*</span></label>
					<textarea  class="textbox normal_textarea" id="C_RESULT" name="C_RESULT"  option = "true" rows="2" message="Phai xac dinh KET QUA XU LY!" ></textarea>
				</div>
				<div>
					<label style="width:30%;">3. &nbsp;<?=$arrConst['_FILE_DINH_KEM'] ?></label>
					<div style="width:68.6%;float:right;"><?=$this->AttachFile;?></div>
				</div>
				<?php if($sStatus == 'CAN_XU_LY' || $sStatus == 'DA_XU_LY' ){?>		
					<div style="clear:both;">
						<label style="width:31%;">4. &nbsp;<?=$arrConst['_TRANG_THAI_XU_LY'] ?><span class="requiein">*</span></label>
							<?php if($sStatus == 'CAN_XU_LY'){?>
							<input type="radio" name= 'C_PROCESS_STATUS' id ='C_PROCESS_STATUS'  value = 'DANG_XU_LY' checked><span class="normal_label"><?=$arrConst['_DANG_XU_LY'] ?> </span>
							&nbsp;&nbsp;<input type="radio" name= 'C_PROCESS_STATUS' id ='C_PROCESS_STATUS' value = 'DA_XU_LY' ><span class="normal_label">  <?=$arrConst['_KET_THUC_XU_LY'] ?></span>
							<?php }if ($sStatus == 'DA_XU_LY'){ ?>
							&nbsp;&nbsp;<input type="radio" name= 'C_PROCESS_STATUS' id ='C_PROCESS_STATUS' value = 'KHOI_PHUC_XU_LY' checked ><span class="normal_label" ><?=$arrConst['_KHOI_PHUC_XU_LY'] ?></span>
							<?php } ?>
					</div>
				<?php } ?>		
				<div style="clear:both;"></div>							
		</div>
		
	</div>	
	<!--Hien thi nut!-->		
	<table width='99%'  border='0' cellspacing='0' cellpadding='0' align='center' class='normal_label'>
		<tr><td style="height:20px;"><hr width='100%' color='#3399FF' size='1'></td></tr>		
		<tr>
			<td align="center" style="padding-bottom:10px;">	
				<button name="btn_ghivaquaylai" id="btn_ghivaquaylai" type="button" value="Ghi" class="add_large_button" onClick="btn_save_doc_received_process('<?=date("d/m/Y");?>');"><?=$arrConst['_GHI'] ?></button>
				<?=$this->formsubmit('button',$arrConst['_QUAY_LAI'],array("onClick"=>"btn_back_onclick('" . $this->historyBack . "')","class"=>"add_large_button"))?>
			</td>
		</tr>			
	</table>
	<div style="margin-left:1%;text-align:right;width:98%;">
	<div class="large_title" style="padding-left:1px;text-align:left;float:left;"> <?=$this->WorkTitle;?> </div>
		<label> 
			<a style="cursor:pointer;" class="small_link" onclick="editSingleWorkValue(document.getElementsByName('chk_item_id'));">&nbsp;<?=$arrConst['_SUA']?>&nbsp;</a> 
			<a style="cursor:pointer;"  class="small_link" onclick="deleteWork(document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id_list'),'../../delete/status/<?=$this->sStatus?>','<?=$this->UrlAjax?>','VB_DEN','T_DOC_WORK');">&nbsp;<?=$arrConst['_XOA']?>&nbsp;</a> 
		</label>
	</div>	
	<table cellpadding="0" cellspacing="0" border="0" width="98%" align="center" class="list_table2" id="table1">
		<?php			
		$delimitor = $this->delimitor;//Lay ky tu phan cach giua cac phan tu
		//Hien thi cac cot cua bang hien thi du lieu
		$StrHeader = explode("!~~!",$this->GenerateHeaderTable("5%" . $delimitor . "15%" . $delimitor . "50%" . $delimitor . "30%" 
									,'<input type="checkbox" name="chk_all_item_id" value="" onclick="checkbox_all_item_id(document.forms[0].chk_item_id);">' . $delimitor . $arrConst['_NGAY_THUC_HIEN'] . $delimitor . $arrConst['_KET_QUA_XU_LY']. $delimitor . $arrConst['_CAN_BO_XU_LY'] 
									,$delimitor));
		echo $StrHeader[0];	
									
		echo $StrHeader[1]; //Hien thi <col width = 'xx'>
			$v_current_style_name = "round_row";
			$arrWorkAll = $this->arrWorkAll;
			$sUnitNameGroup = '';		
			for($index = 0;$index < sizeof($arrWorkAll);$index++){
				//Lay file dinh kem
				$strFileName 				= $arrWorkAll[$index]['C_FILE_NAME'];
				$sFile 	= Sys_Library::_getAllFileAttach($strFileName,"!#~$|*","!~!",$this->baseUrl . "attach-file/");
				//ID CONG VIEC
				$sPkDocWorkId 				= $arrWorkAll[$index]['PK_DOC_WORK'];	
				//Noi xu ly 
				$sUnitName					= $arrWorkAll[$index]['C_UNIT_NAME'].'&nbsp;';				
				//Ngay thuc hien
				$dImplementationDate		= $arrWorkAll[$index]['C_WORK_DATE'].'&nbsp;';								
				//Ket qua xu ly
				if($strFileName == '' || $strFileName == null){
					$sResult				= $arrWorkAll[$index]['C_RESULT'].'&nbsp;';
				}else {
					$sResult				= $arrWorkAll[$index]['C_RESULT'] .'<br>'. $sFile;
					$sFile = "";
				}
				//Can bo xu ly
				$sStaffPositionName 		= $arrWorkAll[$index]['C_STAFF_POSITION_NAME'] .'&nbsp;';				
				//Disable doi vs nhung cong viec khong phai do can bo dang nhap hien thoi tao lap ra
				$sDisable = "";
				//echo $_SESSION['staff_id'].'<br>'.$arrWorkAll[$index]['FK_STAFF'];
				if($arrWorkAll[$index]['FK_STAFF'] != '{'.$_SESSION['staff_id'].'}'){
					$sDisable = "disabled";
				}
				if ($v_current_style_name == "odd_row"){
					$v_current_style_name = "round_row";
				}else{
					$v_current_style_name = "odd_row";					
				}
				if ($sUnitName != $sUnitNameGroup){?>		
					<tr style="background:#DBDEE9">					
					<td colspan="5" align="left" style="padding-left:3px;padding-right:3px;" class="normal_label"><b><?=$sUnitName?></b></td>													
					</tr><?php
					$sUnitNameGroup = $sUnitName;
				}?>				
				<tr class="<?=$v_current_style_name?>">		
					<td align="center" style="padding-left:3px;padding-right:3px;" class="normal_label">
						<?=$this->formCheckbox('chk_item_id',$sPkDocWorkId, array('checked' => false,'onclick' =>'selectrow(this)',$sDisable=>true));?>					
					</td>													
					<td  onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_work_id'),'<?=$sPkDocWorkId?>');" align="center"  style="padding-left:3px;padding-right:3px;" class="normal_label"><?=$dImplementationDate;?></td>
					<td  onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_work_id'),'<?=$sPkDocWorkId?>');" align="left"  style="padding-left:3px;padding-right:3px;" class="normal_label"><?=$sResult;?></td>
					<td  onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_work_id'),'<?=$sPkDocWorkId?>');" align="left" style="padding-left:3px;padding-right:3px;" class="normal_label"><?=$sStaffPositionName?></td>		
				</tr><?php	
			}
			//onclick = "getSingleWorkValue('<?=$sPkDocWorkId						
			//Tu dien cac dong trang trong truong hop du lieu tra ve < so row _CONST_NUMBER_OF_ROW_PER_LIST		
			if(sizeof($arrWorkAll) < 7){	
				echo $this->addEmptyRow($this->iCountElement,7 - sizeof($arrWorkAll),$v_current_style_name,4);		
			}	
		?>			
	</table>
	<table width='100%'  border='0' cellspacing='0' cellpadding='0' align="center">
		<tr>
			<td style="padding-top: 10px; padding-bottom: 10px;" align="center" valign="middle">
				<input type="button" class="add_large_button" value="<?=$arrConst['_SUA'] ?>" onclick="editSingleWorkValue(document.getElementsByName('chk_item_id'));">
				<input type="button" class="add_large_button" value="<?=$arrConst['_XOA'] ?>" onclick="deleteWork(document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id_list'),'../../delete/status/<?=$this->sStatus?>','<?=$this->UrlAjax?>','VB_DEN','T_DOC_WORK');">			
			</td>	
		</tr>
	</table>	
<script type="text/javascript"> 
if(document.getElementById('C_WORK_DATE').value == ''){
	document.getElementById('C_WORK_DATE').value = '<?=date("d/m/Y");?>';		
}
// Ham lay lai thong tin chi tiet mot cong viec
function getSingleWorkValue(pWorkId){
	<?php
	$arrWorkAll = $this->arrWorkAll;
	for($i =0; $i <sizeof($arrWorkAll); $i ++){?>
		if("<?=$arrWorkAll[$i]["PK_DOC_WORK"]?>" == pWorkId){
			document.getElementById('C_WORK_DATE').value = "<?=$arrWorkAll[$i]["C_WORK_DATE"]?>";
			document.getElementById('C_RESULT').value = "<?=$arrWorkAll[$i]["C_RESULT"]?>";
		}<?php
	}?>
	//Gan lai cac gia tri vao Hidden
	document.getElementById('hdn_work_id').value = pWorkId;		
	//Lay lai file dinh kem 
	try{
		var key = 'hdn_work_id=' + pWorkId;
		postAJAXHTTPText('<?=$this->UrlAjax;?>' + '/received/generatehtml/documents/editWork.php', key, document.getElementById('fileUpload'), null);
	}catch(e){;}		
	//Set focus ve muc "Ket qua xu ly"
	document.getElementById('C_RESULT').focus();			
}
function editSingleWorkValue(p_checkbox_obj){
	v_value_list = checkbox_value_to_list(p_checkbox_obj,",");
	if (!v_value_list){
		alert("Chua co cong viec nao duoc chon!");
	}else{
		arr_value = v_value_list.split(",");
		if (arr_value.length > 1){
			alert("Tai mot thoi diem chi duoc phep SUA MOT CONG VIEC!")
			return;
		}
		else
			getSingleWorkValue(v_value_list);
	}
}
function deleteWork(p_checkbox_obj, p_hidden_obj,p_url,UrlAjax, DocType, TableName){
	if (!checkbox_value_to_list(p_checkbox_obj,",")){
		alert("Chua co cong viec nao duoc chon!");
	}
	else{
		if(confirm('Ban thuc su muon xoa cong viec da chon ?'))
		{	
			//Xoa file dinh kem 
			var Delimitor   = '!#~$|*';
			value_list = checkbox_value_to_list(p_checkbox_obj,",");
			var key = 'ListIdDoc=' + value_list + '&DocType='+ DocType +'&TableName='+ TableName +'&delimitor=' + Delimitor;
			arrUrl = UrlAjax.split('/');
			postAJAXHTTPText('/' + arrUrl[3] + '/public/ajax/deleteAllFile.php',key,'', null);	
			//Thuc hien action xoa cong viec
			p_hidden_obj.value = value_list; //Xac dinh cac phan tu duoc checked va luu vao bien hidden p_hidden_obj
			actionUrl(p_url);
		}
	}
}
</script>
</form>
<script type = "text/javascript">
$(function() {
	$( "#C_WORK_DATE" ).datepicker({
		changeMonth: true,
		gotoCurrent: true,
		maxDate: '+1m +1w',
		minDate: new Date(1945, 1 - 1, 1),
		changeYear: true
	});
});
</script>
