<?php 
$arrPermission = $_SESSION['arrStaffPermission'];
if($arrPermission['CAP_NHAT_LOAI_DM'] || $arrPermission['CAP_NHAT_DM_DOI_TUONG'] || $arrPermission['CAP_NHAT_QUYEN'])
{?>
<form action="index" method="POST" id="frmlist">
	<table cellpadding="0" cellspacing="0" width="100%" border="0">
		<!--tao tac hidden!-->
		<tr>
			<!--Sinh mot hidden luu list ID ma NSD chon!-->
			<?php echo $this->formHidden("hdn_object_id_list","",null); ?>
			<!--Sinh mot hidden luu ID loai danh muc!-->
			<?php echo $this->formHidden("hdn_id_listtype",$this->iIdListType,null); ?>	
			<!--Sinh mot hidden luu ID danh muc doi tuong!-->
			<?php echo $this->formHidden("hdn_list_id","",null); ?>
			<!--Sinh mot hidden luu gia tri xac dinh so ban ghi / 1 trang!-->	
			<?php echo $this->formHidden("hdn_record_number_page",$this->numRowOnPage,null); ?>				
			<!--Bien hdn_xml_file dung de luu ten file XML cua loai danh muc hien thoi-->
			<?php echo $this->formHidden("hdn_xml_file",$this->xmlFileName,null); ?>	
			<!--Bien hdn_xml_tag_list dung de luu danh sach cac THE XML tuong ung voi cac THUOC TINH cua mot doi tuong dang duoc cap nhat-->			
			<?php echo $this->formHidden("hdn_xml_tag_list",'',null); ?>			
			<!--Bien hdn_xml_value_list dung de luu danh sach cac gia tri cua cac THE XML tuong ung voi cac THUOC TINH cua mot doi tuong-->			
			<?php echo $this->formHidden("hdn_xml_value_list",'',null); ?>	
			<!--Bien hdn_page dung de luu chi so trang hien thi hien thoi-->			
			<?php echo $this->formHidden("hdn_current_page",$this->currentPage,null); ?>
			<!--Bien hdn_filter_xml_tag_list dung de luu danh sach cac THE XML tuong ung voi cac tieu thuc loc tren giao dien DANH SACH DOI TUONG-->
			<?php echo $this->formHidden("hdn_filter_xml_tag_list",$this->filterXmlTagList,null); ?>
			<!--Bien hdn_filter_xml_tag_list dung de luu gia tri cua cac THE XML tuong ung voi cac tieu thuc loc tren giao dien DANH SACH DOI TUONG-->	
			<?php echo $this->formHidden("hdn_filter_xml_value_list",$this->filterXmlValueList,null); ?>
		</tr>
	</table>
	<!--HIen thi tieu de man hinh danh sach!-->
	<table width='100%'  border='0' cellspacing='0' cellpadding='0' class="table_title">
		<tr>
			<td class="large_title" style="padding-left:7px;text-align:left;">
				<?=$this->bodyTitle;?><br>				
			</td>
		</tr>
	</table>
	<table cellpadding="0" cellspacing="0" width="98%" align="center" border="0">
		<col width="88%"><col width="12%">
		<tr>
			<td class="normal_label">
				<?=$this->generateFilterForm;?>
			</td>
			
			<td align="center" valign="bottom" style="padding-left:5px">
				<?php
					echo $this->formButton("btn_filter","Tìm kiếm",array("type"=>"button","class"=>"add_large_button","onClick"=>"btn_query_data_onclick(document.getElementById('hdn_filter_xml_tag_list'),document.getElementById('hdn_filter_xml_value_list'),document.getElementById('hdn_current_page'),'');")) . "&nbsp;";
				?>
			</td>			
		</tr>
		
	</table>	
	<table cellpadding="0" cellspacing="0" border="0" width="98%" align="center">		
		<!--Hien thi du lieu!-->
		<tr>
			<td style="padding-top:10px">
				<?php	
					//Hien thi ket qua		
					echo $this->generateHtmlList;
				?>
			</td>
		</tr>			
	</table>	
	<!--Hien thi trang can xem!-->			
	<table width="98%" cellpadding="0" cellspacing="0" border="0">		
			
			<tr>
				<td style="padding-left:10px;padding-right:8px;">
					<?=$this->SelectDeselectAll;?>
				</td>
			</tr>
			
			</tr>							
			<!--!-->
			<tr>
				<td align="right" style="font-size:13px; padding-right:8px; font:tahoma" class="normal_label"><?php		
						//Hien thi so trang	
						echo $this->generateHtmlSelectBoxPage;?>
				</td>
			</tr>		
	</table>
	<table width="98%" align="center" cellpadding="0" cellspacing="0" border="0">				
		<tr>

			<td align="center" height="10px">			
			</td>
		</tr>
	</table>
	<table width="98%" align="center" cellpadding="0" cellspacing="0" border="0" class="buton_table">				
		<tr>
			<td align="center" class="body">
			<?php
				//Nut "Them"
				echo $this->formButton("btn_add","Thêm",array("type"=>"button","class"=>"add_large_button","onClick"=>"actionUrl('../add/');")) . "&nbsp;";
				//Nut "Xoa"
				echo $this->formButton("btn_delete","Xóa",array("type"=>"button","class"=>"add_large_button","onClick"=>"btn_delete_onclick(document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id_list'),'../delete/');")). "&nbsp;";
				//Nut Xuat ra file XML
				echo $this->formButton("btn_exportXml","Xuất XML",array("type"=>"button","class"=>"add_large_button","onClick"=>"actionUrl('../xml/');")) . "&nbsp;";
			?>			
			</td>
		</tr>
	</table>
</form>
<?php } 
else 
	echo '<div class ="warning"><h1>Bạn không có quyền truy cập chức năng này :(</h1></div>';
?>