<form action="index" method="POST" id="frmReceived">
<div>
	<table width='100%'  border='0' cellspacing='0' cellpadding='0' class="table_title">
		<tr>
			<td class="large_title" style="padding-left:7px;text-align:left;">
				<!--Cac doi tuong hidden tren form-->
				<?php echo $this->formHidden("hdn_current_page",$this->currentPage,null); ?>
				<?php echo $this->formHidden("hdn_record_number_page",$this->numRowOnPage,null); ?>
				<?php echo $this->formHidden("hdn_object_id_list","",null); ?>
				<?php echo $this->formHidden("hdn_filter_xml_tag_list",$this->filterXmlTagList,null); ?>
				<?php echo $this->formHidden("hdn_filter_xml_value_list",$this->filterXmlValueList,null); ?>
				<?php echo $this->formHidden("hdn_object_id",$this->sTaskWorkId,null); ?>
				<?php echo $this->formHidden("hdn_object_check_id","",null); ?>
				<?php echo $this->formHidden("hdn_search_check",$this->sSearchCheck,null); ?>
				<?php echo $this->formHidden("hdn_search_file",$this->sSearchFile,null); ?>
				<?php echo $this->formHidden("hdn_XmlTagValueList",$this->XmlTagValueList,null); ?>
				<!--Bien hdn_deleted_new_file_id_list dung de luu Id cua nhung doi tuong file dinh kem se xoa-->	
				<?php echo $this->formHidden("hdn_deleted_new_file_id_list","",null); ?>	
				<!--Bien hdn_deleted_exist_file_id_list dung de ...-->	
				<?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null);?>
				<?php echo $this->formHidden("hdn_history_back",$this->sUrl,null); ?>
				<?=$this->bodyTitle;?>	
			</td>
		</tr>
	</table>
	<?php
		$arrConst = $this->arrConst; 
	?>
	<div class="box container c1">
		<div class="pad">			
			<table cellpadding="0" cellspacing="0" width="98%" border="0">
				<col width="15%"/><col width="85%"/>
				<tr>
					<td class="normal_label" align="left">
						&nbsp;<?=$arrConst['_TU_NGAY'] ?>
					</td>
					<td class="normal_label" align="left">
						<input class="textbox c3" id ="fromDate" name="fromDate" type="text" isdate="true" value="<?=$this->fromDate?>" option = "false" message="<?php echo "NGAY THANG NAM khong dung dinh dang";?>" onKeyDown="change_focus(document.forms[0],this)">
						&nbsp;&nbsp;<?=$arrConst['_DEN_NGAY'] ?> &nbsp;&nbsp;
						<input class="textbox c3" id ="toDate" name="toDate" type="text" isdate="true" value="<?=$this->toDate?>" option = "false" message="<?php echo "NGAY THANG NAM khong dung dinh dang";?>" onKeyDown="change_focus(document.forms[0],this)">
						<!-- &nbsp;&nbsp;<?=$arrConst['_TRANG_THAI'] ?> &nbsp;&nbsp;
						<select style="width:20%;" id="C_STATUS" name="C_STATUS" onchange="actionUrl('');" class="textbox normal_label" >
						<option id="" name = "" value="">-- Chọn trạng thái --</option>
						<?php
							$arrStatus= $this->arrStatus;
							echo Sys_Library::_generateSelectOption($arrStatus,'C_CODE','C_CODE','C_NAME',$this->iStatus);?>
						</select> -->
					</td>
				</tr>
				<tr>
					<td class="normal_label" align="left">
						&nbsp;Từ khóa tìm kiếm
					</td>
					<td class="normal_label" align="left">
						<input size="80%" id="FullTextSearch" name="FullTextSearch" value="<?=$this->FullTextSearch?>">
						<input type="button" value="<?=$arrConst['_TIM_KIEM'] ?>" class="add_large_button" onclick="actionUrl('');">
					</td>
				</tr>
			</table>
		</div>
	</div>
	<!-- 
	<div style="margin-left:1%;text-align:right;width:98%;">
		<label>  
			<a style="cursor:pointer;" class="small_link" onclick="btn_update_onclick(document.getElementsByName('chk_item_id'),'../feedback/');">&nbsp;Phản hồi&nbsp;</a> 	
			<a style="cursor:pointer;" class="small_link" onclick="btn_update_onclick(document.getElementsByName('chk_item_id'),'../forward/');">&nbsp;Chuyển tiếp</a> 
		</label>
	</div>	
	 -->	
	<table cellpadding="0" cellspacing="0" border="0" width="98%" align="center" class="list_table2" id="table1">
		<?php			
		$delimitor = $this->delimitor;//Lay ky tu phan cach giua cac phan tu
		$sSearchCheck = $this->sSearchCheck;
		if($sSearchCheck == 0){
			$sUrlSearchCheck = '<img src = "'.$this->baseUrl.'images/uncheck.gif" onclick="searchcheck(1);" >';
		}else{
			$sUrlSearchCheck = '<img src = "'.$this->baseUrl.'images/check.gif" onclick="searchcheck(0);" >';
		}
		if($this->sSearchFile == 0){
			$sUrlSearchFile = '<img src = "'.$this->baseUrl.'images/nau.gif" onclick="searchfile(1);" >';
		}else{
			$sUrlSearchFile = '<img src = "'.$this->baseUrl.'images/vang.gif" onclick="searchfile(0);" >';
		}
		$sUrlSearchCheck = $sUrlSearchCheck.'&nbsp;'.$sUrlSearchFile;
		//Hien thi cac cot cua bang hien thi du lieu
		$StrHeader = explode("!~~!",$this->GenerateHeaderTable("7%" . $delimitor ."15%". $delimitor . "52%" . $delimitor . "14%" . $delimitor . "12%"
										,'<input type="checkbox" name="chk_all_item_id" value="" onclick="checkbox_all_item_id(document.forms[0].chk_item_id);">'.$sUrlSearchCheck. $delimitor . 'Người gửi' . $delimitor . 'Công việc' . $delimitor . 'Thời gian gửi' . $delimitor . 'Trạng thái'
										,$delimitor));
		echo $StrHeader[0];					
		echo $StrHeader[1]; //Hien thi <col width = 'xx'><...		
			//Dinh nghia URL
			$sUrlView  = "../feedback/";
			$v_current_style_name = "round_row";
			$arrResul = $this->arrResul;
			$objFunction =	new	Sys_Function_DocFunctions()	;
			//var_dump($arrResul);
			for($index = 0;$index < sizeof($arrResul);$index++){
				$staskwork = $arrResul[$index]['PK_TASK_WORK'];
				//Check
				$urlcheck = '<img src = "'.$this->baseUrl.'images/check.gif" onclick="set_check(\''.$staskwork.'\');" >';
				$urluncheck = '<img src = "'.$this->baseUrl.'images/uncheck.gif" onclick="set_check(\''.$staskwork.'\');" >';
				//file
				$urlfile = $arrResul[$index]['C_FILE_NAME'];
				if($urlfile!=''){
					$urlcheck = $urlcheck .'&nbsp;<img src = "'.$this->baseUrl.'images/den.gif" >';
					$urluncheck = $urluncheck .'&nbsp;<img src = "'.$this->baseUrl.'images/den.gif" >';
				}else{
					$urlcheck = $urlcheck .'&nbsp;&nbsp;&nbsp;';
					$urluncheck = $urluncheck .'&nbsp;&nbsp;&nbsp;';
				}
				//Nguoi gui
				$sNguoigui = Sys_Function_DocFunctions::getNamePositionStaffByIdList($arrResul[$index]['FK_CREATE_STAFF']);
				//Cong viec
				$sTieude =  $objFunction->searchCharColor($this->FullTextSearch,$arrResul[$index]['C_TITLE'] ).'&nbsp;';
				if(strlen($arrResul[$index]['C_CONTENT']) > 70){
					$sNoidung =  substr($objFunction->searchCharColor($this->FullTextSearch,$arrResul[$index]['C_CONTENT'] ),0,70);
					$iEndTrim = strrpos($sNoidung, " ");
					if($iEndTrim > 0){
						$sNoidung =  substr($objFunction->searchCharColor($this->FullTextSearch,$arrResul[$index]['C_CONTENT'] ),0,$iEndTrim).'&nbsp;';	
					}
					$sTieude =  $sTieude.'<span style="color:#999999;"> - '.$sNoidung.'...</span>';
				}else{
					if($arrResul[$index]['C_CONTENT']!=''){
						$sTieude =  $sTieude.'<span style="color:#999999;"> - '.$arrResul[$index]['C_CONTENT'].'</span>';	
					}
				}
				//echo $sNoidung;
				//Thoi gian gui
				$sThoigian =  $objFunction->searchCharColor($this->FullTextSearch,$arrResul[$index]['C_SEND_DATE'] ).'&nbsp;';
				//trang thai
				$iTinhchat = $arrResul[$index]['C_NATURE'];
				//echo $iTinhchat;
				if(($iTinhchat=='GIAO_VIEC')&&($arrResul[$index]['FK_PROCESS_STAFF'] == $_SESSION['staff_id'])){
					$iTrangthai = $arrResul[$index]['C_STATUS'];
					if($iTrangthai=='CONG_VIEC_MOI'){
						$sTrangthai = 'Chưa xử lý';
					}
					if($iTrangthai=='DANG_XU_LY'){
						$sTrangthai = 'Đang xử lý';
					}
					if($iTrangthai=='DA_XU_LY'){
						$sTrangthai = 'Đã xử lý';
					}
					//ngay hen
					$sNgayhen = $arrResul[$index]['C_APPOINTED_DATE'];
					if(($sNgayhen<>'')&&($sNgayhen<>'01/01/1900')&&($iTrangthai!='DA_XU_LY')){
						$sTrangthai = $sTrangthai.'<br><span style="color:#FF0000;">'.$sNgayhen.'</span>';
					}
				}else{
					$sTrangthai = 'Trao đổi';
				}
				$sTrangthai = $sTrangthai .'&nbsp;';
				//Check
				$iCheck = $arrResul[$index]['C_CHECK_REC'];
				if ($v_current_style_name == "odd_row"){
					$v_current_style_name = "round_row";
				}else{
					$v_current_style_name = "odd_row";					
				}?>
				<tr class="<?=$v_current_style_name?>">	
					<td align="center" style="padding-left:3px;padding-right:3px;" class="normal_label">
						<?=$this->formCheckbox('chk_item_id',$arrResul[$index]['PK_TASK_WORK'], array('checked' => false,'onclick' =>'selectrow(this)'));
						if($iCheck == 0){
							echo $urluncheck;
						}else{
							echo $urlcheck;
						}
						?>					
					</td>
					<?php if($arrResul[$index]['C_VIEW_STATUS']){?>
						<td ondblclick="item_onclick('<?=$staskwork?>','<?=$sUrlView?>')" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$staskwork?>');" align="left"  style="padding-left:3px;padding-right:3px;" class="normal_label" ><?=$sNguoigui?></td>													
						<td ondblclick="item_onclick('<?=$staskwork?>','<?=$sUrlView?>')" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$staskwork?>');" align="left"  style="padding-left:3px;padding-right:3px;" class="normal_label"><?=$sTieude;?></td>
						<td ondblclick="item_onclick('<?=$staskwork?>','<?=$sUrlView?>')" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$staskwork?>');" align="center"  style="padding-left:3px;padding-right:3px;" class="normal_label"><?=$sThoigian;?></td>
						<td ondblclick="item_onclick('<?=$staskwork?>','<?=$sUrlView?>')" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$staskwork?>');" align="center" style="padding-left:3px;padding-right:3px;" class="normal_label"><?=$sTrangthai?></td>
					<?php }else{?>		
						<td ondblclick="item_onclick('<?=$staskwork?>','<?=$sUrlView?>')" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$staskwork?>');" align="left"  style="padding-left:3px;padding-right:3px;" class="normal_label" ><b><?=$sNguoigui?></b></td>													
						<td ondblclick="item_onclick('<?=$staskwork?>','<?=$sUrlView?>')" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$staskwork?>');" align="left"  style="padding-left:3px;padding-right:3px;" class="normal_label"><b><?=$sTieude;?></b></td>
						<td ondblclick="item_onclick('<?=$staskwork?>','<?=$sUrlView?>')" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$staskwork?>');" align="center"  style="padding-left:3px;padding-right:3px;" class="normal_label"><b><?=$sThoigian;?></b></td>
						<td ondblclick="item_onclick('<?=$staskwork?>','<?=$sUrlView?>')" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$staskwork?>');" align="center" style="padding-left:3px;padding-right:3px;" class="normal_label"><b><?=$sTrangthai?></b></td>
					<?php }?>	
				</tr><?php
				
			}					
			//Tu dien cac dong trang trong truong hop du lieu tra ve < so row _CONST_NUMBER_OF_ROW_PER_LIST		
			if(sizeof($arrResul) < 15){	
				echo $this->addEmptyRow($this->iCountElement,15 - sizeof($arrResul),$v_current_style_name,5);		
			}	
		?>			
	</table>	
	<!--Hien thi trang can xem!-->	
	<table width="100%" cellpadding="0" cellspacing="5" border="0">
		<tr>
			<td width="30%" style="color:red;padding-left:1%;" class="normal_label">
				<?=$this->sdocpertotal;?>
			</td>
			<td align="center" style="width="50%">
				<table width="10%"><?php
					//Hien thi danh sach so trang
					echo $this->generateStringNumberPage;?>
				</table>
			</td>
			<td width="30%" align="right" style="font-size:13px; padding-right:1%; font:tahoma" class="normal_label"><?php
				//Hien thi so trang
				echo $this->generateHtmlSelectBoxPage;?>
			</td>
		</tr>
	</table>
	
	<table width='100%'  border='0' cellspacing='0' cellpadding='0' align="center">
		<tr>
			<td style="padding-top: 10px; padding-bottom: 10px;" align="center" valign="middle">			
				<input id="btn_print" name="btn_print" type="button" class="add_large_button" value="Phản hồi" onclick="btn_update_onclick(document.getElementsByName('chk_item_id'),'../feedback/');">			
				<input type="button" class="add_large_button" value="Chuyển tiếp" onclick="btn_update_onclick(document.getElementsByName('chk_item_id'),'../forward/');">
			</td>	
		</tr>
	</table>
</div>
</form>
<script type = "text/javascript">
$(function() {
	$( "#fromDate" ).datepicker({
		changeMonth: true,
		gotoCurrent: true,
		maxDate: '+1m +1w',
		minDate: new Date(1945, 1 - 1, 1),
		changeYear: true
	});
	$( "#toDate" ).datepicker({
		changeMonth: true,
		gotoCurrent: true,
		maxDate: '+1m +1w',
		minDate: new Date(1945, 1 - 1, 1),
		changeYear: true
	});
});
</script>