<form action="index" method="POST" id="frmAddSent" enctype="multipart/form-data" autocomplete="off">
	<table cellpadding="0" cellspacing="0" width="100%" border="0">
		<!--tao tac hidden!-->
		<tr>
			<td class="large_title" style="padding-left:7px;text-align:left;">
				<?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null); ?>
				<?php echo $this->formHidden("hdn_deleted_new_file_id_list","",null); ?>
				<?php echo $this->formHidden("hdnCode","",null); ?>
				<?php echo $this->formHidden("hdn_object_id_list","",null); ?>
				<?php echo $this->formHidden("hdn_xml_tag_list","",null); ?>
				<?php echo $this->formHidden("hdn_xml_value_list","",null); ?>
				<?php echo $this->formHidden("hdn_filter_xml_tag_list",$this->filterXmlTagList,null); ?>
				<?php echo $this->formHidden("hdn_filter_xml_value_list",$this->filterXmlValueList,null); ?>
				<?php echo $this->formHidden("hdn_XmlTagValueList","",null); ?>
				<?php echo $this->formHidden("hdh_option",$this->option,null); ?>
				<?php echo $this->formHidden("hdn_deleted_new_file_id_list","",null); ?>	
				<?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null); ?>	
				<?php echo $this->formHidden("hdnListId","",null); ?>	
				<?php echo $this->formHidden("number",'',null); ?>
				<?php echo $this->formHidden("hdn_object_id",$this->sentID,null); ?>		
				<?php echo $this->formHidden("hdn_work_id","",null); ?>		
				<?php echo $this->formHidden("hdn_function_modul",$this->getModulLeft,null);?>
				<?php echo $this->formHidden("hdn_idea_unit_name","",null); ?>
				<?php echo $this->formHidden("hdn_list_id","",null); ?>
				<?php echo $this->formHidden("hdn_position_leader_name","",null); ?>
				<?php echo $this->formHidden("hdn_pb_name","",null); ?>
				<?php echo $this->formHidden("hdn_ub_name","",null); ?>
				<?php echo $this->formHidden("hdn_px_name","",null); ?>
				<?php echo $this->formHidden("hdn_vp_name","",null); ?>
				<?= $this->bodyTitle1  ;?>
			</td>
		</tr>
	</table>
	<?php  
		$arrSent = $this->arrSent;
		$arrConst = $this->arrConst;
		$urlCalendar = $this->urlCalendar;
		$arrWork = $this->arrWork;
		//Kiem tra NSD hien thoi co phai la 
		$sPermissionDepartment = Sys_Function_DocFunctions::docTestUser($_SESSION['staff_id']);
		//echo 'xxx:' . $sPermissionDepartment . '<br>';
	?>
	<!-- Thong tin co ban cua VB du thao -->
	<table class="table_detail_doc" border="1" width="100%">
	<col width="25%" align="left"/><col width="75%" align="left"/>
		<tr>
			<td style="border-right:1px solid #CCC">
				<?=$arrConst['_LOAI_VAN_BAN'] ?>
			</td>
				
			<td>
				<?= $arrSent[0]['C_DOC_TYPE'] ?>
			</td>
		</tr>	
		<tr>
			<td style="border-right:1px solid #CCC">
				<?=$arrConst['_PHONG_BAN_DU_THAO'] ?>
			</td>
				
			<td>
				<?= $arrSent[0]['C_UNIT_NAME'] ?>
			</td>
		</tr>
		<tr>
			<td style="border-right:1px solid #CCC">
				<?=$arrConst['_TRICH_YEU'] ?>
			</td>
				
			<td>
				<?= $arrSent[0]['C_SUBJECT'] ?>
			</td>
		</tr>
		<?php
			$strFileName = $arrSent[0]['C_FILE_NAME'];
			if($strFileName != ''){
				$sFile = Sys_Library::_getAllFileAttach($strFileName,"!#~$|*","!~!",$this->baseUrl . "attach-file/");
			}	
		?>
		<tr>
			<td style="border-right:1px solid #CCC">
				<?=$arrConst['_FILE_DINH_KEM'] ?>
			</td>
				
			<td>
				<?= $sFile ?>
			</td>
		</tr>
	</table>
	<table cellpadding="0" cellspacing="0" width="100%" border="0">
		<tr>
			<td class="large_title" style="padding-left:7px;text-align:left;">
				<?= $this->bodyTitle2 ; ?>
			</td>
		</tr>
	</table>
	<div id="body_conten1" style="padding-top:5px;">
			<div>
				<label>1.&nbsp;<?=$arrConst['_NGAY_TRINH']?><span class="requiein">*</span></label> 
				<input id ="C_WORK_DATE" name="C_WORK_DATE" type="text" isdate="true" value="" option = "true"  xml_tag_in_db="" xml_data="false" column_name="C_WORK_DATE" message="NGAY TRINH khong dung dinh dang ngay/thang/nam!" onKeyDown="change_focus(document.forms[0],this)">					 					
			</div>				
			<div>
				<label>2.&nbsp;<?=$arrConst['_VAN_DE_TRINH'] ?><span class="requiein">*</span></label>
				<textarea  class="textbox normal_textarea" id="C_SUBMIT_CONTENT" name="C_SUBMIT_CONTENT"  option = "true" rows="2" message="Phai xac dinh noi dung VAN DE TRINH KY!" ></textarea>
			</div>
			<div>
				<label style="width:31%" >3. &nbsp;<?=$arrConst['_FILE_DINH_KEM'] ?></label>
				<?=$this->AttachFile;?>
			</div>		
			<div>
				<label style="width:31%">4. &nbsp;<?=$arrConst['_TRINH_KY'] ?></label><?php 
				//echo $sPermissionDepartment; 	
				if($this->search_doc_lanh_dao_px == ''){?>
					<input type="radio" name= 'C_STATUS' id ='C_STATUS'  value = 'TRINH_LDPB' onclick='getLeaderDraff(this)' "><span class="normal_label"><?=$arrConst['_LANH_DAO_PHONG'];?> </span>
					<div id='ld_pb' style="display:none;"><textarea class="normal_textarea" id="C_PB_NAME"   rows="1" name="C_PB_NAME" message="Phai xac dinh LANH DAO de trinh ky"></textarea></div><br clear="all"><?php
						
					if ($sPermissionDepartment == 2 || $sPermissionDepartment == 3 || $sPermissionDepartment == 4){// = 2: Vai tro lanh dao phong ban; = 3: Vai tro lanh dao Van phong (CVP/PCVP); = 4: Vai tro lanh dao don vi (CT/PCT; GD/PGD; ...)?> 
								<input  type="radio"  name= 'C_STATUS' id ='C_STATUS'  value = 'TRINH_LDUB'  style='margin-left:32%' onclick='getLeaderDraff(this)' ">																			
									<span class="normal_label">  <?=$arrConst['_LANH_DAO_UB'] ?></span>
										<div id='ld_ub' style="display:none;margin-left:32%">
											<textarea class="normal_textarea" id="C_UB_NAME"   rows="1" name="C_UB_NAME" message="Phai xac dinh LANH DAO de trinh ky"></textarea>
										</div>
						<!-- Truong hop Phuong Xa --><?php 
					}
									
				}else{?>
					<input type="radio" name= 'C_STATUS' id ='C_STATUS'  value = 'TRINH_LDPX' onclick='getLeaderDraff(this)' "><span class="normal_label"> <?=$arrConst['_LANH_DAO_PHUONG_XA'] ?> </span>
					<br><div id='ld_px' style="display:none;"><textarea class="normal_textarea" id="C_PX_NAME"   rows="1" name="C_PX_NAME" message="Phai xac dinh LANH DAO de trinh ky"></textarea></div><br clear="all"><?php  
				}?>
			</div>	
	</div>
	<table 	width='99%'  border='0' cellspacing='0' cellpadding='0' align="center" class="table_title">
		<tr><td style="height:20px;"><hr width='100%' color='#ffffff' size='1'></td></tr>			
		<tr>
			<td align="center" style="padding-bottom:1px;">				
				<button name="btn_ghivaquaylai" id="btn_ghivaquaylai" type="button" value="" class="add_large_button" onClick="document.getElementById('hdh_option').value='GHI';submitorder_save_period(document.getElementById('C_WORK_DATE'),'<?=date("d/m/Y" )?>',document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'');"><?=$arrConst['_GHI'] ?></button>
				<?=$this->formsubmit('button','Quay lại',array("onClick"=>"actionUrl('index');","class"=>"add_large_button"))?>
			</td>
		</tr>			
	</table>			
	</div>
	
	<div id="getSysbolforNowYear" style="display:none;"></div>
</div>	
<?php
	echo $this->search_doc_lanh_dao_pb;
	echo $this->search_doc_lanh_dao_ub;
	echo $this->search_doc_lanh_dao_px;
	echo $this->search_doc_lanh_dao_vp;	
?>
</form>
<script type="text/javascript">
	document.getElementById('C_WORK_DATE').value = '<?=date("d/m/Y" ) ;?>';
function getLeaderDraff(code){
	try{
		if(code.value == 'TRINH_LDUB'){
			document.getElementById('ld_pb').style.display = "none"; 
			document.getElementById('ld_ub').style.display = "block";
			document.getElementById('C_PB_NAME').value ='';
			document.getElementById('C_UB_NAME').setAttribute("option","false");
			document.getElementById('C_UB_NAME').setAttribute("optional","");
			document.getElementById('C_PB_NAME').setAttribute("option","");
			document.getElementById('C_PB_NAME').setAttribute("optional","true");
		}
	}catch(e){;}	
	try{
		if(code.value == 'TRINH_LDPB'){
			document.getElementById('ld_pb').style.display = "block"; 
			document.getElementById('ld_ub').style.display = "none"; 
			document.getElementById('C_UB_NAME').value ='';
			document.getElementById('C_PB_NAME').setAttribute("option","false");
			document.getElementById('C_PB_NAME').setAttribute("optional","");
			document.getElementById('C_UB_NAME').setAttribute("option","");
			document.getElementById('C_UB_NAME').setAttribute("optional","true");
		}
	}catch(e){;}
	try{
		if(code.value == 'TRINH_LDPX'){
			document.getElementById('ld_px').style.display = "block"; 
			document.getElementById('C_PX_NAME').setAttribute("option","false");
			document.getElementById('C_PX_NAME').setAttribute("optional","");
		}
	}catch(e){;}	
}	
</script>
<script type = "text/javascript">
$(function() {
	$( "#C_WORK_DATE" ).datepicker({
		changeMonth: true,
		gotoCurrent: true,
		maxDate: '+1m +1w',
		minDate: new Date(1945, 1 - 1, 1),
		changeYear: true
	});	
});
</script>